### ISSUE TITLE
Recording of points without meeting the conditions of the distance and speed filters

### ISSUE THREAD

**Issue by vlmendz** [OpenTracksApp/OpenTracks#1007]
**Describe the bug**
These unnecessary points are recorded following a pattern:

Before each point that meets the conditions of the filters, the previous point received is recorded (see images):

![Captura_cs_ot_5m_0s](https://user-images.githubusercontent.com/91810638/139786965-5d261485-57cd-479f-974f-879bdd20d761.PNG)
![Captura_qgis_ot_5m_0s](https://user-images.githubusercontent.com/91810638/139786985-b865db5a-c80c-4145-bb77-bab8e39484e2.PNG)
☝️Points of a fragment of a recorded track (distance interval=5m)

![Captura_cs_ot_5m_0s_dist](https://user-images.githubusercontent.com/91810638/139787225-72ecd191-d3ad-44b7-87bb-09870c09d01c.PNG)
☝️Distances between the points of a fragment of a recorded track (distance interval=5m)

Examining the TrackRecordingManager.onNewTrackPoint() function, I see a possible cause of this behavior:

	void onNewTrackPoint(TrackPoint trackPoint, Distance thresholdHorizontalAccuracy) {

        //TODO Figure out how to avoid loading the lastValidTrackPoint from the database

        TrackPoint lastValidTrackPoint = getLastValidTrackPointInCurrentSegment(trackId);

        //Storing trackPoint

        // Always insert the first segment location
        if (!currentSegmentHasTrackPoint()) {
            insertTrackPoint(trackId, trackPoint);
            lastTrackPoint = trackPoint;
            
            // Posible 2nd modification:   ******************************
            // Posible solution for TODO above?
            lastValidTrackPoint = trackPoint; 
            
            return;
        }

        Distance distanceToLastTrackLocation = trackPoint.distanceToPrevious(lastValidTrackPoint);
        if (distanceToLastTrackLocation != null) {
            if (distanceToLastTrackLocation.greaterThan(maxRecordingDistance)) {
                
                // Remove also this?  ******************************              
                insertTrackPointIfNewer(trackId, lastTrackPoint);

                trackPoint.setType(TrackPoint.Type.SEGMENT_START_AUTOMATIC);
                insertTrackPoint(trackId, trackPoint);

                lastTrackPoint = trackPoint;
                
                // Posible 2nd modification:   ******************************
                // Posible solution for TODO above?
                lastValidTrackPoint = trackPoint; 
                
                return;
            }
            
            
            if (trackPoint.hasSensorData() || (draistanceToLastTrackLocation.greaterOrEqualThan(recordingDistanceInterval) && trackPoint.isMoving())) {
                
                //************************************
                // 1st modification:   ******************************
                // Remove next line. Next function (combined with the last line of onNewTrackPoint) appears to be the cause of the unwanted recording:
                //insertTrackPointIfNewer(trackId, lastTrackPoint);
                //************************************

                insertTrackPoint(trackId, trackPoint);

                lastTrackPoint = trackPoint;
                
                // Posible 2nd modification:   ******************************
                // Posible solution for TODO above?
                lastValidTrackPoint = trackPoint; 
                
                return;
            }
        }

      
        Log.d(TAG, "Not recording TrackPoint, idle");
        lastTrackPoint = trackPoint;
    }
**To Reproduce**
Record a track at low speed.

**Technical information**
 - Device: Redmi Note 7
 - OS: MIUI 12.5.1 (Android 10 based)
 - Version OpenTracks 3.21.0

P.s. This appears to be a leftover from the already removed idle/non-idle code.

**Comment by dennisguse** [comment]
The pasted code is not the most recent version.

@vlmendz In any case: creating a PR makes our discussions way easier :)

**Comment by vlmendz** [comment]
The pasted code is not the most recent version.

I see 🤦

    @vlmendz In any case: creating a PR makes our discussions way easier :)

How I create it? (sorry for my GitHub shortcomings)
