### ISSUE TITLE
Move buttons to bottom bar

### ISSUE THREAD

**Issue by contrapunctus-1** [OpenTracksApp/OpenTracks#1078]
**Is your feature request related to a problem? Please describe.**
Buttons being placed along the top make one-handed use difficult and require more hand movement than a bottom-bar-oriented design.

**Describe the solution you'd like**
Ideally, all buttons would be moved to a bottom bar. The ones that affect me the most (and are probably easiest to relocate) are "Show on map", "Share", and the overflow menu items in the track details view.

**Comment by dennisguse** [comment]
Agreed.

@contrapunctus-1 Any suggestions on the how the final result should look like?

**Comment by contrapunctus-1** [comment]
@dennisguse I made some quick and dirty mockups. Five buttons between the record and stop buttons looks a little cluttered, but there's enough space for them on my 5.5" screen phone. (That said, there are smaller screen phones too...) Alternatively, the stop button could be removed while no track is recording, since it does nothing at that time...

![opentracks mockup](https://user-images.githubusercontent.com/8513118/148292352-a68240bf-0d8e-4236-9ce4-04fc0d29b56b.jpg)
![opentracks mockup track](https://user-images.githubusercontent.com/8513118/148292363-16c71761-80de-43bd-81f0-1cf8470472b4.jpg)

**Comment by rgmf** [comment]
I was thinking in something similar to FOSS Browser. I mean, move bar from top to bottom.

What do you think?

**Comment by dennisguse** [comment]
I am all for reworking the UI; just don't want to spent too much time on it ;)
Having these overflow menu spread out looks very promising!

**Comment by rgmf** [comment]
Only for notes: here it's documented a solution for this:

https://material.io/components/app-bars-bottom

**Comment by rgmf** [comment]
I'm working on this. I copy/paste here some prototypes (it takes me some time so if this is not what you all expect, please let me know :smile: ):

PS/ The idea is remove pause button too (the pause function). So the only button it shows is recording and stop ones, depending it's recording or not.

![imagen](https://user-images.githubusercontent.com/4819612/156920440-136f1d82-b0f7-4b2e-b193-a716eff3b5d5.png)


![imagen](https://user-images.githubusercontent.com/4819612/156920452-e205dd42-8126-4195-9d67-08c54327483d.png)

**Comment by dennisguse** [comment]
Looks neat!

Neat! 
Why not start with the simple solution to just move the bar down and center the start/stop button? We can add fancyness later (aka transparency, overlay layout). ;)

And could we add the current total time left of the button? 

About pause: I don't use it that often, but sometimes it is useful. 
Should we overload the button?
Aka start -> long press -> pause.
Pause -> short press -> resume.
Pause -> long press -> stop.

PS I would love to remove the pause functionality from TrackRecordingService as it makes it kind of complicated... If we only handle it in the UI our life would be way simpler.

**Comment by rgmf** [comment]
I was thinking on this use case:

![imagen](https://user-images.githubusercontent.com/4819612/156931023-eceecd26-0150-4a19-923d-65c6425906b3.png)

On stopped layout user can:
- Change name and activity type before save (and before auto-import).
- Back to recording (it's a logic pause but we can remove the pause functionality from TrackRecordingService).

**Comment by rgmf** [comment]
> Why not start with the simple solution to just move the bar down and center the start/stop button? We can add fancyness later (aka transparency, overlay layout). ;)
> 

Yes, that could be great, but I have to look into the possibility of add to FAB buttons on that bottom bar.

> And could we add the current total time left of the button?
> 

I hope so :smile: 

> About pause: I don't use it that often, but sometimes it is useful. Should we overload the button? Aka start -> long press -> pause. Pause -> short press -> resume. Pause -> long press -> stop.
> 
> PS I would love to remove the pause functionality from TrackRecordingService as it makes it kind of complicated... If we only handle it in the UI our life would be way simpler.

I hardly ever use it. But the use case described on my last thread do the same and also reduce the impact of: #824 and #983

**Comment by dennisguse** [comment]
Amazing - I would definitely use it this way!
