### ISSUE TITLE
`StringUtilsTest.testFormatDateTime()` failing

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1082]
`StringUtilsTest.testFormatDateTime()`.

Using `DateTimeFormatter.FormatStyle.MEDIUM` appends if the time is before lunch (e.g., AM); it even does this for ES and DE.

Test fails on CI and my machine.

In addition, the default locale of the device is modified and thus subsequent tests may fail afterwards.

_Originally posted by @dennisguse in https://github.com/OpenTracksApp/OpenTracks/issues/1081#issuecomment-1006940238_

**Comment by dennisguse** [comment]
@rgmf Any ideas?

**Comment by rgmf** [comment]
In Spanish we never add AM and PM after time, in fact nobody knows what that mean 😅

I'd modify that test to be more flexible with that.

**Comment by rgmf** [comment]
PS/ in my local machine all tests passes (using AVD and real phones).

**Comment by dennisguse** [comment]
In German, we also don't ;)

I get:
For US: AM
For ES: a. m.
For DE: vorm.

Kind of weird; never seen this in German.
I got this consistently in the emulator as well as on a LineageOS device.

And my LineageOS device behaves differently than my emulator as it produces some commas differently. 
I am mindblown...

PS/ the assert has the expectation first and as 2nd actual

**Comment by dennisguse** [comment]
Can we simplify the expectation by defining it as string and not creating it from LocaleDateTime?
