### ISSUE TITLE
Continue a stopped track

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#11]
At the moment, after stopping a track it cannot be continued.
This behavior, however, is quite annoying if you stopped tracking by mistake.

**Comment by dennisguse** [comment]
As mentioned in #136 merging multiple tracks would also be nice (thanks @pieplu).

For continuing:
The only internal change required is to modify `TrackRecordingService.startRecording()` and pass the `trackId` (in difference to creating a new `Track`).
For the UI, first #103 should be implemented and then probably menu item could be added to continue a (not recording) track.

**Comment by dennisguse** [comment]
PR merged.

**Comment by DevRonin** [comment]
Third party utility to concatenate tracks? like GPSBabel

**Comment by dennisguse** [comment]
@DevRonin ?
