### ISSUE TITLE
Vocal announcement of the time in French is incorrect

### ISSUE THREAD

**Issue by solfred** [OpenTracksApp/OpenTracks#1101]
Hi, 

I am a French user of OpenTracks. 
The vocal annoucements of time is incorrect

The term "second" is replaced by "minute"

For example instead of saying 15 minutes and 30 **seconds**, OpenTracks is saying 14 minutes and 30 **minutes**.

**Comment by dennisguse** [comment]
You are right.
Should it be "seconde" and "secondes"?

Translations are handled via Weblate: https://weblate.bubu1.eu/engage/OpenTracks/
If you find anything else... my French is almost non-existing...

PS/ was my fault; I introduced this problem last year....

**Comment by solfred** [comment]
In French "Seconde" and "Secondes" sound the same. You can use "Seconde".

**Comment by dennisguse** [comment]
@solfred using the same value for singular and plural leads to errors while linting.
Thanks for reporting the issue; will be fixed with the next release.
Or you start using the nightly build (fix will be included tomorrow).

**Comment by solfred** [comment]
Thanks a lot for the change.
