### ISSUE TITLE
Android 12: test device 2 device transfer

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1110]
More details here: https://developer.android.com/about/versions/12/behavior-changes-12#backup-restore

**Comment by dennisguse** [comment]
After reading the actual changes: from Android 12 onward, Google Drive backup and device2device transfer are separated and can be deactivated individually.
So, it should just work...

@pstorch @rgmf Do you have devices to test this?
I am still running Android 11 and it might be take quite a while before I get an upgrade to 12.

**Comment by pstorch** [comment]
My device is still on Android 11.

**Comment by rgmf** [comment]
Yes, I can test it on Android 12.

**Comment by rgmf** [comment]
Reading this: https://support.google.com/pixelphone/answer/7129955

It seems you only can transfer data app from one device to another the first time you start your destination Android device, right? In such a case I'd have to reset my phone to test it.

**Comment by pstorch** [comment]
Oh, and I hoped local (adb) Backups will be allowed then. 😔

**Comment by dennisguse** [comment]
@pstorch ... me too :/

**Comment by dennisguse** [comment]
If this works, it works - if not then not.
