### ISSUE TITLE
Type: Swimming Open Water Workout

### ISSUE THREAD

**Issue by MrS1R1US** [OpenTracksApp/OpenTracks#1119]
Please add activity type: Swimming (Without GPS) and Swimming in open water (with GPS).

**Comment by dennisguse** [comment]
Do you need two different ones? OpenTracks does not have a profile support. So the activity does not affect what and how data get recorded (eg which BLE sensor, with or/without GPS).

**Comment by dennisguse** [comment]
@pstorch Do you have an icon available?

**Comment by MrS1R1US** [comment]
`Do you need two different ones?`

Need activity - icon)

**Comment by pstorch** [comment]
Two different icons for "Swimming" and "Swimming in open water"?

**Comment by MrS1R1US** [comment]
> Two different icons for "Swimming" and "Swimming in open water"?

Yes please) And "Fitness" if you can. (Need for workout with use heart monitor)

**Comment by pstorch** [comment]
I'm not a designer, but I like playing with Inkscape. I don't want to copy something from the "internet" to not run into copyright issues, so I tried my own interpretation of these activities.

Swimming in the open:
![ic_activity_swimming_open](https://user-images.githubusercontent.com/5598124/152653766-269e4a36-d575-4660-ad9f-887ace7d1ee4.png)

Swimming:
![ic_activity_swimming](https://user-images.githubusercontent.com/5598124/152653768-2008f5e4-1898-4c52-aa40-76e512227edc.png)
This should depict a swimming pool. But I'm not happy with it. Maybe the general swimming should be the first icon and "swimming in the open" should have some extra characteristic. But I'm not sure what. Maybe bigger waves or a small island with a palm tree :wink:

Workout activity with heart-rate monitoring:
![ic_activity_workout](https://user-images.githubusercontent.com/5598124/152653769-10463007-3eaf-49f6-b03d-9908f5413ad5.png)

PS: ignore the different background color. This will be transparent later in the app.

**Comment by rgmf** [comment]
@pstorch they are fantastic!!! I love them.

Anyway, I agree with you: I'd use "swimming in the open" for swimming and for swimming in the open I'd add a sun or something like this, a simple detail like this would be enough IMHO.

I love workout activity.

Great use of Inkscape ;)

**Comment by MrS1R1US** [comment]
> This should depict a swimming pool. But I'm not happy with it. Maybe the general swimming should be the first icon and "swimming in the open" should have some extra characteristic. But I'm not sure what. Maybe bigger waves or a small island with a palm tree wink

Very cool) For open water, I think you can leave this logo, just add a small palm tree to the background. And for fitness, maybe some a man with biceps or a icon - dumbbell?) What do you think?

**Comment by MrS1R1US** [comment]
> Workout activity with heart-rate monitoring:

I suggest this for crossfit ))

**Comment by pstorch** [comment]
Standard swimming:
![ic_activity_swimming](https://user-images.githubusercontent.com/5598124/152657410-fea14fad-8e7d-4166-9479-877fd1beb9b3.png)

Swimming open water:
![ic_activity_swimming_open](https://user-images.githubusercontent.com/5598124/152657411-c3af023d-9cf4-4bfd-8070-3b867f0b62ca.png)

Workout: 
![ic_activity_workout](https://user-images.githubusercontent.com/5598124/152657409-d8a10682-651c-46e4-8281-fb54edc4fd70.png)

Now with one muscle arm and a dumbbell. It looks a bit funny :laughing:

**Comment by MrS1R1US** [comment]
> Now with one muscle arm and a dumbbell. It looks a bit funny laughing

:D
Maybe try two muscle?)))


Swimming good :)

**Comment by pstorch** [comment]
Ok, let's settle the swimming icons.

The muscle man with more muscles:
![ic_activity_workout2](https://user-images.githubusercontent.com/5598124/152660658-29cdfd90-2a3b-4422-8acd-5567a9a2d8a2.png)

Maybe it's a bit too much.

Or back to sticky figure with straight lines:
![ic_activity_workout 01](https://user-images.githubusercontent.com/5598124/152660657-5244fd3f-2c2e-45a8-a8af-864daa187925.png)

**Comment by MrS1R1US** [comment]
I think the second option matches the general style of the icons:
![](https://user-images.githubusercontent.com/5598124/152660657-5244fd3f-2c2e-45a8-a8af-864daa187925.png)

**Comment by pstorch** [comment]
I think so too.
Other question: despite I like the heart, is it really necessary on this specific activity? I mean most of the sports activities we have affect your heart beat.

**Comment by MrS1R1US** [comment]
> I think so too. Other question: despite I like the heart, is it really necessary on this specific activity? I mean most of the sports activities we have affect your heart beat.

The heart symbolizes that this workout can actually record only heartbeat and time, because speed and distance do not make sense. Here, as you wish, you can remove, you can leave.

**Comment by pstorch** [comment]
Ah sure, that is the difference to the others where movement is the main thing we track.

@dennisguse and @rgmf what do you think?

**Comment by rgmf** [comment]
@pstorch about the workout I like the last version, without muscle and with heartbeat. Also, I think the heartbeat focuses that it's a hr/time activity.

**Comment by pstorch** [comment]
I've opened a PR: https://github.com/OpenTracksApp/OpenTracks/pull/1121
