### ISSUE TITLE
Statistics: analyze all tracks

### ISSUE THREAD

**Issue by mwip** [OpenTracksApp/OpenTracks#112]
This feature was removed a couple of versions ago. However, I think that it would be very useful to get a quick overview of the training effort. 

Also, it would be nice to be able to group by year, month or week. 

Do you think this would be a valuable feature?

**Comment by dennisguse** [comment]
For sure - I would love to see this implementation properly!
I removed the available implementation as it was just summing up all recorded tracks: there was no differentiation by activity type, filtering or anything else.

**Comment by mwip** [comment]
Awesome. I'd love to help, but unfortunately I am not much of a java developer myself. So if there is anything I could do besides coding, e.g. testing or reviewing, I'd be happy to do this.

**Comment by dennisguse** [comment]
Coding is actually not that complicated in this case.
It is basically about accessing the database (via SQL) and hand the data to the UI (which is actually the complicated part).
What would be great if you could define the goals that you want to achieve (why do want statistics?) as well as a draft of a possible UI design.

Then somebody can just take and implement it.
One technical requirement: try to avoid introducing additional libraries for visualization.

**Comment by dennisguse** [comment]
An API for external plugins is now available: https://github.com/OpenTracksApp/OpenTracks/commit/a3eb1070686fe3a377ab50c4a9bb1c91bd62c279
