### ISSUE TITLE
Running training does not show pace

### ISSUE THREAD

**Issue by MrS1R1US** [OpenTracksApp/OpenTracks#1120]
**Describe the bug**
Running training does not show pace. Need choice pace/speed on ready workout for analyze past workouts.

**To Reproduce**
1. Go to 'Ready workout'
2. See error "Speed"

If applicable:
![image](https://user-images.githubusercontent.com/2820825/152602627-10262654-82bb-4883-9fd8-6d18ee83fff9.png)

**Technical information**
 - Device: All devices
 - OS: All OS
 - OpenTracks version: Current version

**Comment by dennisguse** [comment]
i don't understand. You can show the pace - both while recording (customize UI feature) and for past recordings (speed/pace can be changed in the settings).

**Comment by MrS1R1US** [comment]
Sorry! I didn't see this setting! Done, the pace is on the run, and the speed on the bike) Please close this appeal)

**Comment by dennisguse** [comment]
:D

PS/ you can also close issues yourself :)
