### ISSUE TITLE
Migrating to Material Design Components (MDC) to Material 3.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#1122]
**Is your feature request related to a problem? Please describe.**
I was looking into improve checkboxes in Filter Fragment (inside Aggregated Stats) because they are not the best option for touch screen:

![imagen](https://user-images.githubusercontent.com/4819612/152698222-74a1f6f8-e61c-4024-8b9c-bc7b3d4f124f.png)

We need better widgets for that and I stumbled upon MaterialButton and MDC.

According to these links:
- https://material.io/blog/migrate-android-material-components
- https://medium.com/androiddevelopers/migrating-to-material-components-for-android-ec6757795351

it's recommended to migrate from legacy Design Support Library to MDC.

Anyway, the last version of design library is Material 3, so it's recommended to migrate from MDC to Material3.

So we ¿should? to migrate from `legacy Design Support Library` to `MDC` to `Material3`.

https://m3.material.io/

**Describe the solution you'd like**
I can spend time to look into this and try to migrate to MDC and to Material3. I think we'll have widgets that will be useful for UI/UX improvements, day/night mode and other stuffs.

**The question is**
@pstorch @dennisguse do you think it worth spend time on this? I'm not designer and I don't know if I'll bear this, but I can try :smile:

**Comment by dennisguse** [comment]
Cool idea! Didn't know about it.
Have fun 😊
