### ISSUE TITLE
Hours on the main page are on 12H format instead of 24H

### ISSUE THREAD

**Issue by pihug12** [OpenTracksApp/OpenTracks#1140]
**Describe the bug**
On the main page, the 24H format is not applied. It's the 12H format that is used. (_see screenshot below_)

**To Reproduce**
Go on the main page with runs between 12h00 and 23h59.

If applicable:
![Screenshot_20220225-200315_OpenTracks_2](https://user-images.githubusercontent.com/678038/155774919-411383bc-7f5b-469e-ba2e-8cb7febd8681.jpg)

**Technical information**
 - Device: Samsung Galaxy S7
 - OpenTracks version: v3.25.0

**Comment by rgmf** [comment]
I'll check it out. Thank you for open this Issue ;)

I gues in your phone 24h format is set, right? And it's the default format in your language, right?
