### ISSUE TITLE
Need new icon for markers

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#115]
The summary icon for markers is the KML blue push pin (`@drawable/ic_marker_blue_pushpin`).
However, this icon only available as a _low resolution PNG_ and the colors do not really fit the UI.

So, we need a replaced (best case SVG).

This is how it looks like currently:
![Screenshot_20200104-142243_OpenTracks__Debug_](https://user-images.githubusercontent.com/2820825/71766236-02b1d080-2efe-11ea-8716-9c55aa7f7649.png)

**Comment by dennisguse** [comment]
We can replace it with the OpenTracks logo.

**Comment by DeusFigendi** [comment]
Here I vectorized it (manually). Colors could be changed easy.
License is cc0

[(sadly I cannot upload SVG in this issue nor .gz or .zip so I used gist for it).](https://gist.github.com/DeusFigendi/ace7c40e438be9dff262168020ba6a3a)

[![KMLbluepushpin](https://user-images.githubusercontent.com/1711504/87447528-fb7d2500-c5fa-11ea-826f-7820c0fe30a6.png)](https://gist.github.com/DeusFigendi/ace7c40e438be9dff262168020ba6a3a)

**Comment by dennisguse** [comment]
@DeusFigendi Nice!
It would be great if you could create a pull request and put the SVG into this folder:
https://github.com/OpenTracksApp/OpenTracks/tree/main/drawable-svg/

If you any suggestions for a different coloring - please feel free to make suggestions.

**Comment by DeusFigendi** [comment]
> If you any suggestions for a different coloring - please feel free to make suggestions.

Dude, no idea, I just mentioned that recolouring is easy, because you wrote it wouldn't fit the UI.
To be honest I don't even know this project, so I don't know which color scheme would fit the needs XD.

>  It would be great if you could create a pull request and put the SVG into this folder:
sure I can do so.

**Comment by dennisguse** [comment]
@DeusFigendi I have no clue about colors - I always hope that somebody else has ><
The current color is black (or a really dark gray) + orange.
Thx

**Comment by dennisguse** [comment]
We now have a working SVG in #320 that was already merged.
Now, we "just" need:
* to replace the blue push pin
* check that the color fits
