### ISSUE TITLE
Pause Recording Automatically After Idle Period

### ISSUE THREAD

**Issue by nthh** [OpenTracksApp/OpenTracks#117]
This feature could exist and I have overlooked it, but it would be nice for the app to automatically stop tracking after some period of idle time. I often find myself forgetting to stop the recording and it records too long of a period.

Example: 
After n minutes of inactivity (device not moving more than n distance), stop recording current track

**Comment by dennisguse** [comment]
Thanks for the request - this functionality is not implemented (you are right).
One issues for this functionality would be that a stopped track cannot be continued (see #11).

Nevertheless, setting the track on pause would be possible.
What do you think?

**Comment by nthh** [comment]
That seems acceptable, as pausing probably fits in better here anyways.

How would idle time be determined?

**Comment by dennisguse** [comment]
The idle time (i.e., the timeout).  could be defined as by the user (creating a settings).
Thissetting could also be used to disable this functionality.

From an implementation perspective the `TrackRecordingService` themself could to take care of this.

NOTE: Pausing might have the disadvantage that the GPS may stay active (I guess; need to be checked). This would drain the battery...

**Comment by DevRonin** [comment]
To determine idle time check speed, if below a certain level (ex. 0.5m/s) for 5 sec, then auto pause.

**Comment by dennisguse** [comment]
@DevRonin that is actually done to compute moving time.

**Comment by dennisguse** [comment]
I guess this is outdated, please re-open if still valid.
