### ISSUE TITLE
Add more granular distance intervals in voice announcements and split intervals

### ISSUE THREAD

**Issue by frasty** [OpenTracksApp/OpenTracks#1195]
Currently OpenTracks only allows to select a minimum distance interval of 1km. This is way too much for activities like swimming. Would be nice if the user could select a more appropriate distance interval of 100m or so, at least for swimming and open water swimming.

**Comment by dennisguse** [comment]
What do you mean?
We have 1m until 100m with a default of 10m.

Or do we have some wrong translation?
For which language?

![image](https://user-images.githubusercontent.com/2820825/164379342-a7220ea5-5d5c-4f17-9649-2949fb46ea42.png)

**Comment by pstorch** [comment]
Maybe the distance interval of voice announcements?

**Comment by frasty** [comment]
Yes, I mean distance interval of voice announcements and split intervals in the stats. Both have a minimum selectable distance of 1km which is useless for workouts in the range of 2-3km, a fair common distance for swimming workouts, I believe.

**Comment by dennisguse** [comment]
I thought that would be quick and easy, but it affects the translations `value_integer_kilometer` and `value_integer_mile` that do not yet support decimal digits...

**Comment by serpico** [comment]
#1159

**Comment by dennisguse** [comment]
@serpico ?

**Comment by serpico** [comment]
I haven't seen the look/screenshot of the last PR but I was thinking a slider button might cover a wider range of options, from 100 m to, maybe, 5 km...how many options would be too many ? ( 100, 200, 500m, 1km, 5km )

**Comment by dennisguse** [comment]
We can add as many as we want.
Currently, it is a list and you will just need to scroll longer ;)

**Comment by serpico** [comment]
Thanks 

> @serpico ?

I mentioned the issue because it sounded about the same parameters : How often do we hear the voice announcement ( every X meters/kilometers and/or every Y minutes ) and the _split intervals in the stats_ ( if announced every kilometer then averaged over the last kilometer ; if announced every minute then averaged over the last minute, if announced every 2 minutes then averaged over the last 2 minutes, and so on...)
