### ISSUE TITLE
Add real max speed peek

### ISSUE THREAD

**Issue by grrosminet** [OpenTracksApp/OpenTracks#1209]
The max speed is not truly a max but a max segment's speed.
Yesterday I did some cycling and for a short time I had current speed = 55km/h whereas max speed was displaying 28km/h.
It would be nice to record the real max speed of the trip.

**Comment by dennisguse** [comment]
Sadly that is not that simple.
Same longer explanation is here: #1003.
And you can try out this #1185.

PS/ long story short: GPS speed is very noisy and there is quite some filtering done.

**Comment by dennisguse** [comment]
@ae5960e8-a6fc-491f-b252-898ecf59af95 that's true. The speed processing also applies to BLE sensor provided speed.
