### ISSUE TITLE
Xiaomi MIUI11 Android 10: Launcher icon is too small

### ISSUE THREAD

**Issue by licaon-kter** [OpenTracksApp/OpenTracks#121]
...in all launchers except those based on the Google Pixel one.

Eg. For these https://search.f-droid.org/?q=launcher&page=1&lang=en only Rootless Pixel Launcher and Lawnchair have it full size, all the others (KISS, BlissLauncher, Essential Launcher, Simple App Launcher, etc) show it at 25% or thereabout

![vmfR-zK_QjOmw-Nuw1baUg](https://user-images.githubusercontent.com/2282799/71907204-71439800-3163-11ea-806e-070f1e64f77d.jpg)

**Technical information**
 - Device: Xiaomi
 - OS:  MIUI11 Android 10
 - Version: 3.3.1 F-Droid

Same as https://github.com/bilde2910/Hauk/issues/52 I guess, maybe the fixes applied there can help.

**Comment by dennisguse** [comment]
I cannot reproduce this behavior on a LineageOS 14.1 nor a LineageOS 16.0 with none of the launchers.

I just added the change made by https://github.com/bilde2910/Hauk/issues/52.
Could you test if this fixes the icon size for you?

I only changed the icon that is used for the debug version (it is black then):
https://github.com/OpenTracksApp/OpenTracks/tree/icon

**Comment by licaon-kter** [comment]
No joy :(

**Comment by dennisguse** [comment]
Then I don't know what to do next.
@licaon-kter if you could try find a solution.
What I don't want to do is adding PNGs - I prefer vector graphics.

**Comment by dennisguse** [comment]
I can confirm this issue: tested on another Xioami device using the default launcher.
Could it be that the Android operating system behaves different on Xioami devices encountering vector icons for the launcher?

**Comment by licaon-kter** [comment]
I don't know, was that on Android 10 or 9 or?

**Comment by lennartschoch** [comment]
Hey there,
I was able to reproduce this behaviour together with @dennisguse on my Xiaomi Mi Mix 3 (MIUI 11.0.4 by xiaomi.eu, based on Android 9). To make sure this issue actually originates from the MIUI launcher, I installed the Pixel launcher and had a look at the launcher icon there:

![Screenshot](https://user-images.githubusercontent.com/32903783/72917910-0094a200-3d45-11ea-9b7b-9082f5a360c8.jpg)

Yup, everything's fine there. Seems like the MIUI launcher is indeed doing something weird to the SVG.

**Comment by dennisguse** [comment]
@lennartschoch Could you check again?
I might have found the issue: an actual invalid logo size.
Standard defines 108dp instead of 24dp; actually even 48dp up to Android 7.1.

More details here: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?hl=en

https://github.com/OpenTracksApp/OpenTracks/tree/logoSize%23121

[OpenTracksUpstream-releasePlayStore.zip](https://github.com/OpenTracksApp/OpenTracks/files/4738562/OpenTracksUpstream-releasePlayStore.zip)

**Comment by lennartschoch** [comment]
@dennisguse this seems to have done the trick! :)

Before:
![before](https://user-images.githubusercontent.com/32903783/83949065-084f7180-a822-11ea-9d28-3ef4a80d7f66.jpg)

After:
![after](https://user-images.githubusercontent.com/32903783/83949070-11d8d980-a822-11ea-8f3b-479e34c5b73c.jpg)

**Comment by dennisguse** [comment]
@lennartschoch Thx!
We will merge the fix ;)
