### ISSUE TITLE
Android 13 adapations

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1210]
New things in Android 13: https://developer.android.com/about/versions/13/features

https://developer.android.com/about/versions/13/summary

- [x] Themed icon
- [x] Upgrade targetSdk and compileSdk to 33 (to be released)
- [x] Check if we need POST_NOTITIFICATIONS: notification will not be shown without this
- [x] Check we need block non-matching intent filters
- [x] Check if we can use developer downgradable permissions: needs an application restart; not really cool. And we only have location + Bluetooth; so it does not really matter
- [x] Check if we can use new photo picker (in MarkerEditActivity.takePictureFromGallery)

**Comment by dennisguse** [comment]
Regarding POST_NOTIFICATION: without this permission, our services create a notification, but it won't be shown anywhere.
We now have two options (on Android13): 
a) that's okay and users will have less clutter
b) we think this notification is important (to show that a recording is running; users can use it to go back to OpenTracks)
Then we have to request this permission from the user (and s/he has to approve - I guess)

@rgmf @pstorch Any opinions?
PS/ will affected almost nobody until mid-2024 :sunglasses: 
(I am still on Android 11 ><)

**Comment by pstorch** [comment]
If it is annoying to ask for permission, we can make it optional (again another setting). On the other hand the user might be asked only once.

**Comment by dennisguse** [comment]
I am thinking about building some welcome screen/ carousel where we can give some basic intro and get all the permissions.
Currently, we ask on first startup already for Bluetooth and Location permission; adding a third doesn't improve it.

**Comment by rgmf** [comment]
> I am thinking about building some welcome screen/ carousel where we can give some basic intro and get all the permissions. Currently, we ask on first startup already for Bluetooth and Location permission; adding a third doesn't improve it.

That sounds like a good idea as I think is important the notification and permissions are getting more complex and uncomfortable.
