### ISSUE TITLE
AFTER v3.28.0: Public API stop does not auto export

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1225]
@dennisguse
Looks like auto export doesn't happen on StopRecording. New ticket or do you reopen this here?

_Originally posted by @sgofferj in https://github.com/OpenTracksApp/OpenTracks/issues/1215#issuecomment-1124007123_

**Comment by dennisguse** [comment]
Happens AFTER v3.28.0 only (aka nightly)
The issue is that we trigger the export now from the TrackStoppedActivity rather than the TrackRecordingService.
When receiving the stop intent, StopActivity just tells the service to stop and then nothing is happening anymore.

Relevant code to look for `ExportUtils.postWorkoutExport(this, trackId);`

**Comment by sgofferj** [comment]
@dennisguse 
Refering to your question in #1215, with the latest nightly (just updated) it does autoexport on stop after OK'ing the file info dialog.

**Comment by pstorch** [comment]
I also stumbled upon this new dialog. Can this be skipped?

**Comment by dennisguse** [comment]
@pstorch It's a feature :)
It more or less replaces the pause functionality and thus saves some screen space.
And it "enables" me to properly enter data (which I otherwise rarely did).

**Comment by pstorch** [comment]
Ah, I see. For me it is an extra click at the end of a workout. Not a big issue.
