### ISSUE TITLE
Since v3.28.0, Settings > Default Units > Preferred Units > Imperial (mi, ft) no longer recognized

### ISSUE THREAD

**Issue by mbrehon** [OpenTracksApp/OpenTracks#1228]
**Describe the bug**
All distances and elevations displayed in metric no matter how Settings > Default Units > Preferred Units is set.

**To Reproduce**
1. Set Settings > Default Units > Preferred Units to Imperial (mi, ft)
2. Go to any screen that displays distances or elevations
3. See units always in metric

**Technical information**
 - Device: Samsung Galaxy s10e
 - OS: Android v12
 - OpenTracks version: v3.28.0-PlayStore / v 3.27.0-13-g36b6cd3c9, Version code: 4829

Edit to add:
- also tried shutting down and restarting app
- also tried rebooting phone
- problem persists

**Comment by dennisguse** [comment]
@mbrehon it is "just" a UI issue; data is handled internally in metric units.
It might take some more days until the next release as we have to fix the problems described in #1224 first.
