### ISSUE TITLE
TrackRecordingService: remove pause functionality

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1233]
We don't need the pause functionality anymore, so we can rip out some technical complexity. :partying_face:

**Comment by dennisguse** [comment]
Original plan by @rgmf ; and we had a commit for this somewhere.

**Comment by vsevjednom-cz** [comment]
😲😲😲
I'm using pause often.

**Comment by rgmf** [comment]
> astonishedastonishedastonished I'm using pause often.

Don't worry, you still can "pause" OT. When you need to pause then stop the track and OT will show you an Activity with some stats. From there you can continue with your track or simply stop it.

In short: from user perspective pause functionality still works.

**Comment by dennisguse** [comment]
... but it will simplify TrackRecordingService a lot - and simple is good :)

Only difference: the new implementation will not keep the sensors on (like GPS) when not recording.
Advantage: saves energy
Disadvantage: re-connect or acquiring the fix again might take some time.

**Comment by vsevjednom-cz** [comment]
> the new implementation will not keep the sensors on (like GPS) when not recording.

Yesss 🎉😋.

**Comment by vsevjednom-cz** [comment]
Pause button is away. Select unpause from menu is too complicated. But it can be like this.

There's short time of wait for pause/stop. I'm affraid of stop tracking by mistake. And app crashes and export nothing. I'll create new issue about it today.

**Comment by dennisguse** [comment]
@vsevjednom-cz I am confused.
You can just continue a recording from the 2nd screen (TrackStoppedActivity) or decide to no to.
Then you can still resume via the overflow menu in TrackRecordedActivity.
What's the problem?

PS/ export was broken in v3.28.0 (never was build by F-Droid as I tagged the wrong commit).

**Comment by vsevjednom-cz** [comment]
I don't see `TrackStoppedActivity` because crash 🤪.
