### ISSUE TITLE
Reset settings while recording?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1247]
I know that the settings should not be reset while recording as we used the store trackId in a preference.
This enabled us to restart a track on device reboot.

... but we don't have this feature anymore, so we can reset while recording, right?

**Comment by dennisguse** [comment]
@rgmf Any ideas?

**Comment by rgmf** [comment]
@dennisguse it can be interesting to reset settings while recording. Maybe it's an edge case but imagine you've touched a lot of settings and recording is on when you look that something is not working like you want.

Beside old trackid issue I don't know another impact. Create a PR and we'll see with real tests...
