### ISSUE TITLE
Feedback UI: Stop Button

### ISSUE THREAD

**Issue by Der-Flip** [OpenTracksApp/OpenTracks#1266]
based on #1264, paragraph 4

**Is your feature request related to a ~~problem~~? Please describe.**
Stop Button repurposed effectively as Pause button with new UI Update.  

**Describe the solution you'd like**
Within the App's Settings a possibility to chose the behaviour of the Stop Button:
- [default] have it as effectively a Pause Button (current state) [Stop>edit Name, Type, Description> save {+ export}]
- have it as pre-update actual Stop Button [Stop> immediate save {+ export}] with increased hold-to-stop-time (~1s or above)

**Additional context**
The new Edit Track Screen after stopping a track is great and I do like the fact it reminds you to double check whether name and type of activity are set correctly, yet, I can see this getting a bit of an annoyance fairly quickly, especially when one does only one activity which is set as default already.

**Comment by dennisguse** [comment]
How would the user discover this feature?

**Comment by dennisguse** [comment]
Seems to work :)
