### ISSUE TITLE
Feedback UI: "Pause"/ Stop Screen: Delete / Disregard Track

### ISSUE THREAD

**Issue by Der-Flip** [OpenTracksApp/OpenTracks#1267]
based on #1264, paragraph 5

**Context**
Sometimes it may not be desirable to save (and therefore possibly export to the filesystem) the recorded track due to testing or possibly inaccuracies during GPS initialization. 

**Describe the solution you'd like**
on the new Stop / Pause screen an additional Button to disregard the current track.
In order to declutter the UI for regular use the display of this button could be limited to any stopped track that is below 100m in length or 1 minute of recording duration.

**Comment by rgmf** [comment]
What about something like this?

![imagen](https://user-images.githubusercontent.com/4819612/171343961-91e54f87-edd6-4710-9042-9d1e9e0cc06b.png)
