### ISSUE TITLE
Missing additional voice announcement settings

### ISSUE THREAD

**Issue by delcier** [OpenTracksApp/OpenTracks#1275]
@spacecowboy once posted this image (https://github.com/OpenTracksApp/OpenTracks/pull/1132) that includes additional settings for voice announcements:

![image](https://user-images.githubusercontent.com/106830411/171909056-fb5c5da3-87bb-4659-a8e9-5bd5a0fb0926.png)

As far as I can tell, these should have made their way into the app in March. However, I don't see these options on my end, only "Report heart rate". By default, the announcement only informs me about the distance. Unfortunately, this info is pretty useless in my case (I need average pace) and I'm sure other people could benefit from additional customization as well.

Is this a bug, or are/aren't there plans to implement these additional settings?

**Comment by dennisguse** [comment]
@delcier You are right.

It could be that @spacecowboy never opened a PR for this.

It seems as if this branch contains the changes: https://github.com/spacecowboy/OpenTracks/tree/configurable_announce
This commit adds toggles: https://github.com/OpenTracksApp/OpenTracks/commit/2f29da2046cb12f3492ef8e1fa8ff4a63ee38372

**Comment by dennisguse** [comment]
I included the changes; only some minor adjustments were necessary.
Changes will be in the next nightly build.

**Comment by delcier** [comment]
Thanks, guys!
