### ISSUE TITLE
Voice announcements incorrectly round the fractional part

### ISSUE THREAD

**Issue by WPettersson** [OpenTracksApp/OpenTracks#1285]
I'm using v4.0.1 (code 4926) from f-droid, and occasionally I'll notice that when I'm running around a 10km/h pace, the voice announcements will say 9.0km/h. This happens most noticeably with the lap announcements, for some reason. I know my pace well enough to know that it must mean 10.0km/h, based on overall track statistics. I did some digging and found https://github.com/OpenTracksApp/OpenTracks/blob/1c3a2bd2e419dc9f5cf3446d2e8316e0b90a8996/src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java#L110

I see what the intention with this line is, but it seems Java does by default using rounding when using String.format. This can be seen with the following Java test:

```
public class Main
{
    public static void main(String[] args) {
        double speed  = 9.9999;
        long integral = (long)speed;
        String frac = String.format("%.1f", speed - integral);
        System.out.println("speed: " + speed + " integral: "  + integral + " frac: " + frac);
    }
}
```
The output is `speed: 9.9999 integral: 9 frac: 1.0` which would explain the odd announcements. This can be tested online at https://www.online-java.com/6XT9vwJcZi as well.

I think I see a few possible solutions. One is to disable rounding in String.format somehow (I had a search, but couldn't work out how to do this properly). Another might be to print the value to a string, and then extract integral and decimal portions from the string itself. Or even use BigDecimal which might be an easier way.

**Comment by dennisguse** [comment]
Actually yes :)
The use of `String.format()` didn't feel very nice.

https://www.baeldung.com/java-separate-double-into-integer-decimal-parts

@WPettersson do you have time to fix this?

**Comment by WPettersson** [comment]
I've thrown a bug fix to https://github.com/OpenTracksApp/OpenTracks/pull/1286 which "should" be correct. However, I don't have any android dev environment setup so I haven't actually run the tests or checked the formatting.

**Comment by WPettersson** [comment]
Okay, seems test 30 worked, test 24 failed (looks unrelated to my changes) and linting passed :)

**Comment by dennisguse** [comment]
@WPettersson welcome to the world of Android in CI; tests are flacky as hell - especially the UI tests :)
