### ISSUE TITLE
Open map in OpenTracks Dashboard without select

### ISSUE THREAD

**Issue by vsevjednom-cz** [OpenTracksApp/OpenTracks#1287]
Hi, how to set `OpenTracks Dashboard` as default for opening map and don't show select? Maybe something in `show_on_map_format_key`?

**Comment by pstorch** [comment]
When the dialog pops up, choose `OpenTracks Dashboard API` and click on the `Always` button.

**Comment by vsevjednom-cz** [comment]
I know but is possible to don't show this dialog and set `always` automatically?

**Comment by pstorch** [comment]
You want to change the default setting programatically?

**Comment by pstorch** [comment]
Then you have to set the preference `showOnMapFormatKey` to the value  `Intent.OpenTracks-Dashboard`.
You can do this via `PreferenceUtils.getShowOnMapFormat()`in line 816 and use the constant `IntentDashboardUtils.PREFERENCE_ID_DASHBOARD`.

> But... there may be a problem when OpenTracks Dashboard isn't installed..?

Probably an error message, try it out :wink:

**Comment by vsevjednom-cz** [comment]
Thanks! But can I do it automatically in `settings.xml`?

**Comment by vsevjednom-cz** [comment]
Oh, I understand. User must do something.
