### ISSUE TITLE
Split interval dropdown options are only in metric

### ISSUE THREAD

**Issue by andmagdo** [OpenTracksApp/OpenTracks#1288]
**Describe the bug**

**To Reproduce**

![IMG_20220617_170517](https://user-images.githubusercontent.com/62532857/174407359-aa2cf277-a496-4bd5-a46d-008eef04856b.jpg)

**Technical information**
 - Device: Google Pixel 6
 - OS: GrapheneOS latest stable version (build SQ3A.220605.009.B1.2022061600)
 - OpenTracks version: v4.0.1 (latest on F-droid)

**Comment by dennisguse** [comment]
Issue should be in `IntervalsFragment.setIntervalsDropdownText()`.

**Comment by rgmf** [comment]
This is a bug from the begining... I overlooked it.

Intervals dropdown values are always showed as metrics values.

I get it.

**Comment by rgmf** [comment]
@andmagdo thank you so much for reporting this bug ;)
