### ISSUE TITLE
[Bug] OpenTracks always stops tracking after a few seconds.

### ISSUE THREAD

**Issue by pempek** [OpenTracksApp/OpenTracks#1295]
Device: Samsung A52s 5G
Android version: 12
Android security patch level: May 1, 2022

The issue:
After starting new recording, I place the phone in my pocket. When I check the phone after a few minutes, I find that OpenTracks has stopped recording. It usually only records for a few seconds

![image](https://user-images.githubusercontent.com/36126710/175463825-a93ff5d8-6051-45b8-8468-a01fabaa4f05.png)

Expected:
I expect the app to continue tracking my activities until I manually stop the recording.

**Comment by dennisguse** [comment]
Not something we can do about; it is a power management issue of the Android OS introduced by your vendor.
At least I hope it is.
Please check: https://dontkillmyapp.com/

We have a cpu wakelock and a foreground service.
And that is all we can do to make it work.
