### ISSUE TITLE
Incorrect timezone handling for import/export GPX

### ISSUE THREAD

**Issue by qwerty287** [OpenTracksApp/OpenTracks#1296]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I import tracks that do not contain proper timezone information. The times are then interpreted as CE(S)T (my system’s timezone) while they actually use UTC.

**Describe the solution you'd like**
A setting that allows me to set UTC as default timezone for imports.

**Describe alternatives you've considered**
Changing the GPX file to  contain proper dates.

**Additional context**
This usually happens when importing from [komoot](https://www.komoot.com/).

An example timestamp: `2022-06-25T14:58:37.146Z`. Opentracks imports this as 14:58 (as CEST), while it was actually recorded at 16:58 (the time as UTC converted to CEST).

**Comment by dennisguse** [comment]
You are right: we should not overwrite the timezone.
If the file states UTC it is UTC end of story.

Anyhow: the exporting tool may include it; so I would recommend contacting Komoot and requesting this feature.

**Comment by dennisguse** [comment]
Almost.

GPX has timestamps as xsd:datetime (supports timezones).
And yes, OpenTrack should only fallback to default timezone if none is present.
If one is present (like Z) then we should take it.
Still komoot could export the recording timezone as well instead of UTC only.

**Comment by dennisguse** [comment]
So... I just checked the code and we only set the timezone to UTC if it is missing.
We do not fallback to device local timezone.
Code is in `StringUtils.parseTime()`.
Importing and exporting should lead to the same timestamp.

So, what is the actual problem?

**Comment by dennisguse** [comment]
I am somehow confused.
While importing we honor the timezone data from the timestamp and if not present use UTC.

Could it be that you mean that we do not show the timezone in the UI properly?

**Comment by dennisguse** [comment]
Take a look at `TrackImporter.setTrack(...)` and the two classes that are calling it.

**Comment by dennisguse** [comment]
And `ExportImportTest` might be helpful for debugging.

**Comment by dennisguse** [comment]
We should show the timezone as it is otherwise confusing.
