### ISSUE TITLE
Positive (and negative) elevation covered

### ISSUE THREAD

**Issue by PhiPhi84120** [OpenTracksApp/OpenTracks#131]
Thanks for this very good app. 

On the main window, when recording the track, we can see the minimum, and the maximum altitude.

Would it be possible to have the total positive and negative elevation covered? 

Thanks.

**Comment by dennisguse** [comment]
It is on the roadmap, but it is not an easy task.
The main issue that the elevation gain/loss needs to derived from the barometric sensor as the GPS is far too imprecise for this.
The complicated part is the sensor fusion between the barometer and the GPS as both are providing data differently (interval, relative vs. absolute).

This feature is tracked in issue #10.

I really would love to get this feature (again)!
That is actually an advantage of the Google Play Service as those do some fancy sensor fusion to derive an absolute location incl. elevation.
However, that is out of question...

If you want to contribute please feel free to so.
My main pain point is the sensor fusion (and a severe lack of time until April 2020).
