### ISSUE TITLE
Play Protect reported possible threath on F-droid 4.0.2 version (Oreo)

### ISSUE THREAD

**Issue by Jroghidno** [OpenTracksApp/OpenTracks#1311]
While normal update through F-droid client, from 4.0.1 to 4.0.2, Play Protect on Android 8.0 warns before installing possible information tracking of user.

1. F-droid announces available update
2. Update as always I do.
3. Before installing confirmation, Play Protect adverts possible threat
4. You choose if install update or not
![imagen](https://user-images.githubusercontent.com/64704541/176938549-b435108b-dcd8-49b4-9cf8-a1e9e18a5f87.png)

 - Device: Galaxy A7 2017
 - OS: Android 8.0, official without root
 - OpenTracks version: 4.0.2
 Note: Update on Android 11 through F-droid client, Play Protect (activated) doesn't show any warn.

**Comment by dennisguse** [comment]
(Sadly) nothing we can do about (easily); the PlayStore (done by me) and F-Droid (done by the F-Droid build server) APK should be (almost) identical (except for the package name).
Don't know what Google Antivirus thing is actually triggered by.
Happens every now and then for things from F-Droid.
