### ISSUE TITLE
"Privacy-proof" in F-droid logo is inaccurate

### ISSUE THREAD

**Issue by zetaomegagon** [OpenTracksApp/OpenTracks#1317]
![Screenshot_20220704-203707_1_1](https://user-images.githubusercontent.com/24728279/177228876-0c6f97ed-1771-47c2-88ec-15a929a981f3.jpg)

"[Privacy-proof](https://en.m.wiktionary.org/wiki/-proof)" means the opposite of what you want it to. Maybe use "Privacy respecting" or "[Privacy-safe](https://en.m.wiktionary.org/wiki/-safe#English) "?

**Comment by dennisguse** [comment]
PR welcome - it is just a svg :)

**Comment by dennisguse** [comment]
Finished by #1444.

**Comment by zetaomegagon** [comment]
Wow! Good job all :)
