### ISSUE TITLE
Elevation gain and loss should be always in meters/feets (basic unit)

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#1319]
**Is your feature request related to a problem? Please describe.**
When elevation gain or loss reach a threshold then the value is converted to km/mi instead of stays in meters/feets.

![imagen](https://user-images.githubusercontent.com/4819612/177492887-713ecfd6-4973-4b31-8355-a85005b4fc78.png)

**Describe the solution you'd like**
Elevation gain and loss should be always in a base unit.

**Comment by dennisguse** [comment]
This is prepared in #1310.
The DistanceFormatter gets threshold for km/miles etc (default 0.5). If set to infinite it will just never happen :)

**Comment by rgmf** [comment]
> This is prepared in #1310. The DistanceFormatter gets threshold for km/miles etc (default 0.5). If set to infinite it will just never happen :)

Ops!!! I overlooked it :+1:

**Comment by dennisguse** [comment]
@rgmf I am not sure, it was done - it just easily doable with #1310 ;)

**Comment by rgmf** [comment]
Okay, so we are going to wait #1310 was merged.
