### ISSUE TITLE
Pace wrong in plots

### ISSUE THREAD

**Issue by marcelmindemann** [OpenTracksApp/OpenTracks#1332]
**Describe the bug**
I think the plotting of my pace against time/distance is broken. I did a run yesterday where my average pacr was around 7 min/km. This is consistent with the breakdown into 1km intervals.

However the graphs show my pace averaging around 8.6 min/km. That's constantly too high when compared with the interval screen.

**Screenshots**
![Screenshot_20220719-125744](https://user-images.githubusercontent.com/12549786/179735704-a47f2c22-4e09-4f84-9008-686578a275eb.png)
![Screenshot_20220719-125747](https://user-images.githubusercontent.com/12549786/179735717-326e0457-af31-4268-ab47-4f936f6a499d.png)
![Screenshot_20220719-125754](https://user-images.githubusercontent.com/12549786/179735726-2d7f13db-9073-4755-acf8-dd74e58d848a.png)

**Technical information**
 - OpenTracks version: 4.0.2

**Comment by dennisguse** [comment]
I have no good explanation for this behavior.
Two options:
* the pace computation is broken in the charts
* or the rendering of the chart is broken (code is ancient ;) )

**Comment by SlidingHorn** [comment]
I'm not sure if this is what I'm dealing with or not, so before making a new ticket, I'll describe my issue and let you tell me whether it belongs here or in its own issue:

I recently started using OT for my run/walk intervals (had been using it for a while for my cycling), and if I stop for any period of time to rest, adjust my knee brace, etc., it shows up as a *huge* spike in my graph. This results in my Pace plotting having a scale up to 600 min/mi, which makes reading that data on the graph impossible. 

Screenshot: https://i.postimg.cc/nh811MnH/Screenshot-20221003-202857.png

**Comment by dennisguse** [comment]
@marcelmindemann just had some time to look I to this. The problem are the labels on the y-axis. It should start with a 0 for pace/speed. The actual plot seems correct when taking this i to account. Labels should be 0, 5, 10, etc.

Don't know exactly why this looks this way for you.

**Comment by dennisguse** [comment]
So, this might be relevant: https://github.com/OpenTracksApp/OpenTracks/issues/795
BUT I didn't see a relevant change in the commits (yet).

@marcelmindemann Can you send me an example track to `opentracks-play@dennisguse.de`?
I cannot reproduce the problem locally.
And does this problem only occur with pace or also with speed?

**Comment by dennisguse** [comment]
Please re-open if this is still an issue.
