### ISSUE TITLE
Spikes in charts

### ISSUE THREAD

**Issue by JakubMakarewicz** [OpenTracksApp/OpenTracks#1333]
I am sorry if duplicate, or if I am an idiot.
Hello, I don't know, what happened but my charts were smooth and now they have millions of spikes.
I have tried to change every setting thinking that I have changed something, but I cannot revert it to the previous state.
It happens in both the time and distance chart.

**To Reproduce**
1. Go to any track
2. Open chart (time or distance)
3. See error

**Technical information**
 - Device: Xiaomi mi10t pro
 - OS: LineageOS 18.1
 - OpenTracks version: v4.0.3

 Screenshot I have taken in May
![Screenshot from may](https://user-images.githubusercontent.com/78924900/179811884-1c394802-3289-4e1f-bd8f-6735a1903254.png)
The same track, screenshot from today
![The above track, screenshot from today](https://user-images.githubusercontent.com/78924900/179811886-bf4dce05-4121-4c08-b844-7ef002dbe437.png)
Another track, screenshot from today
![Another track, screenshot from today](https://user-images.githubusercontent.com/78924900/179812031-7cd8667b-e99f-4d17-914a-79a2006cd3ed.png)

**Comment by JakubMakarewicz** [comment]
Okay, thank you.
Yeah, I figured out that the GPS isn't the best, so as I understand, on other phones the charts still look kind of alright?
Anyways, thank you for this amazing app

**Comment by dennisguse** [comment]
It depends on the chipset, the antenna, your location (mountains or not), weather and all the other things that might affect GPS reception.
But it often looks like this: https://github.com/OpenTracksApp/OpenTracks/issues/1332

Nothing you can do about it (except using another phone).
For OpenTracks, we could introduce some smoothing again (less fancy).
