### ISSUE TITLE
Altitude shown as 'null' despite being recorded

### ISSUE THREAD

**Issue by xfarrow** [OpenTracksApp/OpenTracks#1338]
**Describe the bug**
In the tab 'intervals' tab, all the altitude mesurements are shown as null, despite being recorded, because it is shown in the graphs rendered in the following tabs.

**To Reproduce**
1. Start recording
2. Stop recording
3. Go to the 'intervals' tab

If applicable:
* add screenshots
* add logcat output

**Technical information**
 - Device: Huawei Mate20 Lite
 - OS: Android 10
 - OpenTracks version: 4.0.3
 - OpenTracks commit id (only for nightly builds): no nightly

**Comment by dennisguse** [comment]
Problem is somewhere in StringUtils.getAltitudeParts()

**Comment by dennisguse** [comment]
Thanks for the info.
Will be in tomorrows nightly.
