### ISSUE TITLE
Elevation data missing on stats/interval views

### ISSUE THREAD

**Issue by Cyruz143** [OpenTracksApp/OpenTracks#1344]
**Describe the bug**
Using a OnePlus Nord, it should have a barometer sensor according to the specs. Elevation data seems to be recording as it's visible in by time/by distance views but missing from interval/stats views.

Wondering if that elevation data is from GPS rather than barometer readings?

**To Reproduce**
1. Record data
2. See missing elevation data on stats/interval 
3. Swipe across to by time/by distance 
4. Elevation data seems to be visible there

If applicable:
![Screenshot_20220804-000648](https://user-images.githubusercontent.com/7225500/182727955-d10f6492-a389-40bb-bed0-b07a1a2581d5.jpg)
![Screenshot_20220804-000653](https://user-images.githubusercontent.com/7225500/182727961-0261b599-964a-41d7-8e46-b6de82e9b446.jpg)
![Screenshot_20220804-000658](https://user-images.githubusercontent.com/7225500/182727971-b4b7a737-1fe6-4cb5-b508-58b505e9b279.jpg)

**Technical information**
 - Device: OnePlusNord
 - OS: Oxygen OS 11.1.10.10
 - OpenTracks version: 4.0.5

**Comment by dennisguse** [comment]
You can check with Trail Sense.
Most likely scenario: the phone has no such sensor.
Alternative (unlikely): the OS did not report the sensor or the sensor did not send any data.

The barometer is actually not that widely built-in.
The Fairphone's also come without.

**Comment by Cyruz143** [comment]
You are correct, more digging today, no barometer... Sorry for the time waste.

**Comment by dennisguse** [comment]
@Cyruz143 all good ;)
