### ISSUE TITLE
[Suggestion] Review voice output for consistency

### ISSUE THREAD

**Issue by sgofferj** [OpenTracksApp/OpenTracks#1346]
I noticed that the voice output is somewhat inconsistent. While it specifies "average heart rate" and "current heart rate", the speed is referred to as "speed" (without any specification) and "lap speed".
It might be worth introducing some consistency if anybody looks at the voice output anyway.

**Comment by dennisguse** [comment]
Good idea!
This can be done via weblate.

I don't know how consistent the naming of the translation keys are - so it might be time consuming to figure out what to change.
