### ISSUE TITLE
feature: Get listed in Awesome Quantified Self

### ISSUE THREAD

**Issue by gdt** [OpenTracksApp/OpenTracks#1351]
There are a group of people who wish to examine their own data while remaining in control of it, and there's a list of pointers.
OpenTracks fits squarely but is missing.

https://github.com/woop/awesome-quantified-self

**Comment by dennisguse** [comment]
Sounds good!
@gdt Are you opening a PR with them?

**Comment by gdt** [comment]
https://github.com/woop/awesome-quantified-self/pull/85

**Comment by dennisguse** [comment]
The repo seems to be in rarely maintained state; hope they merge the PR at some point in the future.
@gdt thanks for the effort!
