### ISSUE TITLE
Android 13: Notifications not showing

### ISSUE THREAD

**Issue by GlitzSmarter** [OpenTracksApp/OpenTracks#1353]
**Describe the bug**
When starting a activity, there is no notification on notifications dropdown or on the lock screen.

**To Reproduce**
Either start tracking location, or start a session, then pull down in notifications (or lock the device) and you won't see OpenTracks anywhere.

**Technical information**
 - Device: Pixel 4A
 - OS: Android 13
 - OpenTracks version: 4.0.6

**Potential Solution**
In Android 13 there is a runtime permission for sending notifications from the app (POST_NOTIFICATIONS) that needs to be declared and the user needs to "Allow".

See [Android Developers Documentation](https://developer.android.com/guide/topics/ui/notifiers/notification-permission) (for a technical detail) or [a post on Medium](https://umang91.medium.com/android-13-notification-runtime-permission-c3d122e4fd35) (for a simple read of this) for how to enable this.

**Comment by dennisguse** [comment]
Follow-up to #1210.

**Comment by dennisguse** [comment]
Is this the only problem on Android 13?
