### ISSUE TITLE
Constant crashes in the background

### ISSUE THREAD

**Issue by bentolor** [OpenTracksApp/OpenTracks#1359]
Thank you very much for this great tool respecting my privacy and following FOSS values.

I'm using OpenTracks in Combination with Gadgetbridge. There i configured the right package name for OpenTracks.

Honestly I don't have a clou on the exact purpose of this integration as it never worked.

Now i regularly get this error after unlocking my lock screen.

Any ideas?

**Comment by dennisguse** [comment]
Which version? 
We had some issues (to start) until 4.0.6 and not yet released is a fix to stop properly.
Problem affected Android 8+ and if OpenTracks was not already running.
I am not using this functionality, so my testing during implementation is rather limited.

**Comment by dennisguse** [comment]
PS which error message?

**Comment by bentolor** [comment]
Hi Dennis and thanks for your quick supply.

I created this ticket out of a crash screen and assumed it would provide more technical details right away. Not sure what tool eventually even created this ticket now. 

You're right: I'm using the F-Droid version which currently is OpenTracks  4.0.6 and Gadgetbridge 0.68.0. Also Lineage OS 18.1 / Android 11.

Will wait for an update and see if that helps.

**Comment by dennisguse** [comment]
The the stop will be crashing, but start should be working (so data should be recorded).
Please reopen, if this is not true for you.
