### ISSUE TITLE
GPX track opened in osmand does not have time information

### ISSUE THREAD

**Issue by vibrys** [OpenTracksApp/OpenTracks#1370]
Hi

opentracks version: v4.0.7
osmand plus: 4.1.11

GPX track saved and exported from OpenTracks, then opened in OsmAnd, keeps info about distance but neither time nor speed as a consequence is available

regards

**Comment by dennisguse** [comment]
Can you share a screenshot how it should look like?

**Comment by dennisguse** [comment]
Reported to OSMAnd: https://github.com/osmandapp/OsmAnd/issues/15271
