### ISSUE TITLE
Icon set via PublicAPI isn't used in track details

### ISSUE THREAD

**Issue by arjan-s** [OpenTracksApp/OpenTracks#1377]
**Describe the bug**
When a track icon is set via the PublicAPI, it is only used in the list of all tracks. When tapping on the track it opens the track details, and instead of the correct icon, it shows the generic icon. When setting the category/icon manually, it shows the icon in both screens correctly. 

Btw: love this feature already! Thank you! 

**Technical information**
 - Device: Samsung Galaxy Fold3 
 - OS: Samsung OneUI 4.1 (android 12)
 - OpenTracks version: 4.0.8

**Comment by dennisguse** [comment]
Thx. I can confirm this by trying to use a different category than icon (via edit functionality).

PS/ IIRC I am not even sure that we export the icon to KML/GPX (and also not import).
So, this feature slightly broken anyhow ;)

**Comment by dennisguse** [comment]
Note: icon export/import is NOT supported by our GPX implementation.
KML should work fine.

**Comment by dennisguse** [comment]
This is hopefully fixed by #1608.
If not, please re-open.
