### ISSUE TITLE
please add “android.permission.ACCESS_BACKGROUND_LOCATION”

### ISSUE THREAD

**Issue by SunDaSora** [OpenTracksApp/OpenTracks#1382]
on “miui”，you need “android.permission.ACCESS_BACKGROUND_LOCATION” to keep it work。
 Detail：在小米手机上，没有这项权限的话，会导致关闭屏幕后应用无法获取GPS位置。由于其权限管理组件只会给请求了此项权限的应用添加“始终允许”的选项，而没有请求此权限的应用只能在前台使用GPS，并且无法手动更改。

**Comment by dennisguse** [comment]
We should not need this permission (due to the use of a ForegroundService).
Can you provide a link to their documentation?
Or were you found this suggestion?

**Comment by SunDaSora** [comment]
（My English is not very good. If something confuses you, please ignore it.）
OK，you are right.I found what happend.On MIUI you need the Permission to use GPS when app background(The system will consider your app to be in the background after closing the screen.)，it named “省电策略”，“无限制” 。 I think it also named “Battery Optimization”。There is 2 Picture，one is your app tell me noGPS,the other is “省电策略”. it sad “It can only identify the application state and take restrictive measures to restrict background networking, positioning,  sensor access and CPU usage。”I changed it from smart limit to unlimited, and the application works normally.
![SAVE_20221004_122739](https://user-images.githubusercontent.com/49709661/193734295-0fa8c083-f456-450e-88e3-c18861d327d0.jpg)
![Screenshot_2022-10-04-12-16-07-236_com miui powerkeeper](https://user-images.githubusercontent.com/49709661/193734327-ac572f16-60b0-48f5-af70-d0a1a23f670a.jpg)

**Comment by dennisguse** [comment]
Thanks for the feedback - it is on the Todo list.

PS don't worry about your English.
You can just your native language (and also post an automatic translation).
That's sufficient.
And the worst case, we ask questions (hopefully simple) or somebody will be able to translate.
