### ISSUE TITLE
app being blocked by play protect

### ISSUE THREAD

**Issue by mneko** [OpenTracksApp/OpenTracks#1383]
**Describe the bug**
I'm trying to install from fdroid from the official repo. It pops up with a "This app can collect data that may be used to track you" message and blocks the install.

**Technical information**
 Samsung Galaxy Note 10+
Android 12
Occurs with opentracks versions 4.0.7 thru 4.1.0

According to https://stackoverflow.com/questions/49092689/app-installation-blocked-with-a-pop-up-saying-app-may-collect-data-to-track-user you might just have an out of date ssl certificate or something of the sort

**Comment by dennisguse** [comment]
Can you provide a screenshot?

We are not using any network...

**Comment by dennisguse** [comment]
If you saw this message: ![Blocked-by-Play-Protect-Play-Store-740x493](https://user-images.githubusercontent.com/2820825/192437833-29c365f8-7755-4aad-acf4-6393e8a1c474.png)

... this happens every now and then.
Google PlayServices "virus/malware scanner" is not really non-PlayStore friendly.
Nothing we can do about.

**Comment by nourkagha** [comment]
Same issue here. Here's a screenshot. ![Screenshot_20221001_121747_com.android.vending.jpg](https://user-images.githubusercontent.com/50773468/193404680-e8b78750-87d4-459a-ad16-29b5b3f506d3.jpg)

**Comment by dennisguse** [comment]
If you enable PlayProtect, you have to live with it's features/ malfunctions.

Nothing we can do about.
You may check with the Fdroid people (but I guess they have the same problem).

Sorry.
