### ISSUE TITLE
Any stoppage results in huge spikes in pace graph

### ISSUE THREAD

**Issue by SlidingHorn** [OpenTracksApp/OpenTracks#1389]
I recently started using OT for my run/walk intervals (had been using it for a while for my cycling), and if I stop for any period of time at a crosswalk, stop to rest, adjust my knee brace, etc., it shows up as a huge spike in my graph. This results in my Pace plotting having a scale up to 600 min/mi, which makes reading that particular data on the graph impossible.

Screenshot: https://i.postimg.cc/nh811MnH/Screenshot-20221003-202857.png

So far, the only "fix" I can think of is to dig my phone out of my pocket and pause the track before stopping and resuming as I get going again.

**Technical information**
 - Device: Pixel 6
 - OS: Android 13 (security update 10/5/2022)
 - OpenTracks version: v. 4.1.1 (version code 5051)

**Comment by dennisguse** [comment]
Just read the issue.
And actually that is expected behavior: according to the screenshot the pace is shown (aka the duration for a km).
And if you stop that will increase as the speed goes to zero.
