### ISSUE TITLE
Polar HR sensor use / recording mode

### ISSUE THREAD

**Issue by tomdeck** [OpenTracksApp/OpenTracks#1391]
I was thinking abut buying a Polar Verity Sense heart rate sensor and using it with OpenTracks. The Polar website says the device needs to be paired via their app before use, especially if one wants to use the sensor in recording mode or swimming mode (i.e. storing the sensor readings and downloading them later, very handy if you don't want to take your phone with you). But the manual also says it is possible to use this device with 3rd party apps. I don't want to share my data with Polar so my idea would be to use OpenTracks only.
My question is: can OpenTracks use this device without pairing via the official app? And if yes, can OpenTracks use it in recording and swimming modes?

**Comment by dennisguse** [comment]
Don't know this device but I have Polar OH1.
Live recording heart rate works well. No software from Polar required (standard BLE protocol).

The OH1 also has a standalone mode where it can  store data itself.
... but I don't know how to fetch the data from the device. And likely it is a proprietary protocol.
Other Polar products may use the same.

**Comment by dennisguse** [comment]
PS code for this is here by provided by Polar SDK. Didn't read their license.
They call this Polar Measurement Device service (PMD).
Code: https://github.com/polarofficial/polar-ble-sdk/blob/master/sources/Android/android-communications/library/src/main/java/com/polar/androidcommunications/api/ble/model/gatt/client/pmd/BlePMDClient.kt

**Comment by dennisguse** [comment]
Not cool to implement proprietary protocols.
If somebody wants to do it: have fun :partying_face:
