### ISSUE TITLE
Migrate weblate 

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1396]
From https://weblate.bubu1.eu to https://translate.codeberg.org/

[ ] Update Link in Fdroid metadata

**Comment by dennisguse** [comment]
@pstorch FYI

**Comment by comradekingu** [comment]
@dennisguse
I implore you not to use Codeberg on account of their stance against freedom https://codeberg.org/Codeberg/org/src/branch/main/TermsOfUse.md
This rug-pull operation was neither mentioned up front, or to users later.
After that there is no tangible reason to use Codeberg, as that was its one and only premise to operate by.

https://hosted.weblate.org OTOH has a great record in the service of freedom, and is maintained by Weblate staff.
Its community is also greater.
Its services are on offer for libre projects via https://hosted.weblate.org/hosting

**Comment by dennisguse** [comment]
@comradekingu I am open for discussion (and dont care too much where to host the translations as I am not using these systems that often(.

I just went briefly through Codeberg's terms and conditions and have not seen any obvious red flags.

Can you elaborate in the problems that you are seeing?


@pstorch @mondlicht-und-sterne @rgmf FYI

**Comment by pstorch** [comment]
@comradekingu what Do you mean by "tug pull operation"? I only remember the discussion as codeberg clarified the usage of their service to  FOSS projects and they don't allow a misuse as private cloud storage, which is a legit move IMHO. 
Is there anything else you have in mind?

**Comment by rgmf** [comment]
I didn't read carefully the terms and conditions of Codeberg but I thought it was a great service for libre software. It's a sorprised for me reading complaints about it.

**Comment by mondlicht-und-sterne** [comment]
Oh kingu, he hATe me.  Because I had translated another project into norwegian, I got angry emails from him all the time.
Maybe it's enough if I don't translate this language for OpenTracks.

**Comment by dennisguse** [comment]
@comradekingu what about hosting the translation on both weblate instances?
We can just configure both to automatically create pull requests and thus may avoid most conflicts due to diverging changes.

@mondlicht-und-sterne I guess it is not hate, but rather a different perspective on how to solve a problem. And then frustration and communication  is spiraling downwards.

**Comment by comradekingu** [comment]
@dennisguse 
Why would you want anything hosted on the Codeberg Weblate I wonder?
There is no upside there, and it makes communication between translators worse. I rely on that.

**Comment by dennisguse** [comment]
As we had no real discussion here, I flipped a coin.
`Weblate.org` won.

**Comment by Bubu** [comment]
Your f-droid metadata still points to weblate.bubu1.eu: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.dennisguse.opentracks.yml#L8

**Comment by dennisguse** [comment]
@Bubu thanks for the reminder :)

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12748
