### ISSUE TITLE
Add new activity types (incl. icons)

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#14]
- [x] MTB
- [x] eScooter
- [x] Motorcycle
- [x] Skateboard
- [x] Sailing
- [x] Inlineskater
- [x] Skiing (was removed)
- [x] Snowboarding (was removed)
- [x] Climbing

**Comment by dennisguse** [comment]
A friend of mine takes care of this - this might take some time.

**Comment by dennisguse** [comment]
Currently, available icons.

![Screenshot from 2020-07-14 22-11-30](https://user-images.githubusercontent.com/2820825/87471682-11044600-c61f-11ea-9aea-4d8e8994dabc.png)

**Comment by mbblp** [comment]
[icons.zip](https://github.com/OpenTracksApp/OpenTracks/files/4947606/icons.zip)
these are the 4 icons for testing

**Comment by dennisguse** [comment]
@mbblp I just had the time to check the images.
Nice work!

While trying ot import I get the following error message: `WARNING @ line 229: Scaling of the stroke width is ignored`.
Some infos to fix this can be found here: https://stackoverflow.com/questions/36453520/inconsistence-between-svg-file-and-android-studio-vector-asset

Do you know how to fix this?

**Comment by pstorch** [comment]
All listed activity types are added. If we need more, we can open a new issue.
