### ISSUE TITLE
Perfect App! Thanks!

### ISSUE THREAD

**Issue by marsch1975** [OpenTracksApp/OpenTracks#1405]
Hi,

it seams this is the only way to say thank you!

It tried a lot of apps and most do not tell you the real accurate distance you made. Open Tracks keeps up with the best I found before I found OpenTracks...

Today I even walked a while during my bike tour and paused the app while doing so, other app just use the direct line from pause start to pause end and include it in the total amount of distance, OpenTrakcs don't.

PERFECT APP!

AND ITS ON F-DROID TOO! WHAT MORE CAN YOU WISH FOR???

PLEASE DON'T CHANGE ALL OF THAT, IT'S A PERFECT APP!!! :)))

And yes, I wanted capitall letters! ;)

Cheers
Markus

**Comment by dennisguse** [comment]
Thanks a lot :)
Cool to have some happy users!
