### ISSUE TITLE
Trailing spaces in file names.

### ISSUE THREAD

**Issue by Colbertson** [OpenTracksApp/OpenTracks#1410]
When naming a finished track and using the autocomplete feature on gboard (and probably other keyboards) it adds a space.
![Screenshot_20221030_191339](https://user-images.githubusercontent.com/81972292/198892082-f141778a-f975-46ff-b791-75166df1bcf5.png)
![Screenshot_20221030_191429](https://user-images.githubusercontent.com/81972292/198892081-d846ddb3-a774-4a09-9bcb-c365648ef641.png)
It would be nice if it was automatically removed before it gets exported.

**Comment by dennisguse** [comment]
Just did some research:
1. ' ' (space) is a valid character for FAT32 (for historic reasons this compatibility was used by Google's MyTracks)
2. There is no option to configure this behavior on the textfield
3. Seems to be a problem of GBoard: https://support.google.com/android/thread/151426405/how-do-i-control-the-added-space-after-selecting-a-suggested-word?hl=en

Not really sure, we should implement a workaround if Google broke/added a feature to their keyboard.
