### ISSUE TITLE
GPS is not aktivated - OpenTracks is recording without GPS signal

### ISSUE THREAD

**Issue by marsch1975** [OpenTracksApp/OpenTracks#1421]
Hi,

every now and then OpenTracks tells me "GPS is not aktiv - OpenTraks is recording without GPS data" but at that moment the line of the journey is fine, in some other cases the line is broken...

I set the battery settings to not interupt OpenTracks which is working fine with other apps...

Samsung Galaxy S21 5G
Android 12
One UI 4.1
OpenTracks 4.1.2

What else can I do?

Cheers
Markus

**Comment by dennisguse** [comment]
Go to someplace with a better GPS reception :)

For real: not that much (if it is not a battery issue).
I would need to check the code: but this message is popping up after 30s(?) if there was no location received in between.
It is just user feedback and has no other impact.

However, two consecutive locations are too far apart (configurable; default 50m) then a new segment is created (aka the line is broken).

**Comment by marsch1975** [comment]
Hi Dennis,

thanks for your reply.

In fakt, I'm under the clear blue sky without high buildings around when it happens..

Most of the times it's just missing for serveral Meters up to some 100Meters i guess and once I was starting at home and after about 10 to 15 minutes it started recording, that was about 4km...

Time in s "smallest"
Recording is 10m (recommended)...
Max distance is 200m (recommended)
GPS 50m (recommended)

So you want me to change the GPS of 50m? Higher or lower?

**Comment by marsch1975** [comment]
How do I make OpenTracks show coordinates? I've been the menu up and down... can't find it...

**Comment by dennisguse** [comment]
Settings -> User Interface -> Customize recording Layout -> (choose one or create a new one) -> add the one with Latitude/Longitude

**Comment by marsch1975** [comment]
Oh, ok, it wasn't easy to find that I can configure the screen myself. When you go on "customize/create your own" it looks like threre is nothing further "like it's empty feature"...

It helped to start the recordings just a few seconds before starting out...

Thanks for all your help!
