### ISSUE TITLE
Marker add w/o track record

### ISSUE THREAD

**Issue by Mental64** [OpenTracksApp/OpenTracks#1432]
I would like the ability to add a marker without first having to record a track.

Sometimes in my work I need to record waypoints but am not recording a track. I do this with other mapping apps.

**Comment by dennisguse** [comment]
Mhhh. That is kind of tricky.
In OpenTracks every marker belongs to a track. 

Another problem is the import and export. 

All of this is doable, but a lot of work to do it properly.

Only alternative at the moment: start a track, create a marker and stop the track. 
You could even use the same track for this.
