### ISSUE TITLE
Expand list of all Tracks with Export-Status

### ISSUE THREAD

**Issue by mega-stoffel** [OpenTracksApp/OpenTracks#1434]
**Is your feature request related to a problem? Please describe.**
It happens more often in the last time, that the app can't export the track after stopping it. I guess it has something to do with a changing or lost network in combination with my nextcloud.

**Describe the solution you'd like**
Therefore I'd like to have a visualization on the list of all tracks, if the export was successful - or if it failed.

**Describe alternatives you've considered**
The best would be, that all exports finish successful - but I'm afraid that's way harder to realize. ;-)

**Additional context**
If I can see failed track exports in the list of all tracks, I can just restart the track and hope, that it will export successful after this restart (which indeed works pretty often).

**Comment by dennisguse** [comment]
We don't store this information and there is no need within OpenTracks to do this.
