### ISSUE TITLE
I CAN'T CONNECT THE MAPS 

### ISSUE THREAD

**Issue by optometria** [OpenTracksApp/OpenTracks#1437]
When I tap on the symbol to see the map it tells me that 
**no application is able to perform this action**

I have installed opentrak v,4,1,2 from F-DROID and OSM Dashboard on line and offline

**Comment by dennisguse** [comment]
Can you check the settings?
Go to Settings -> User Interface -> Select "show on map" behavior.
Should be set to `OpenTracks Dashboard API`.

**Comment by optometria** [comment]
Thank you very much
previously I had set KMZ (with photos)
