### ISSUE TITLE
New design for stickers?

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1444]
Back in 2019, I created a sticker for OpenTracks.
I printed two batches and those are gone now.

Question: is anybody interested creating a new design?

https://github.com/OpenTracksApp/OpenTracks/blob/main/promotion/sticker_inkscape.svg
![image](https://user-images.githubusercontent.com/2820825/211209293-afed4ba4-a5cc-4bc8-b8aa-fe0f193cb966.png)

@pstorch @rgmf @mondlicht-und-sterne

**Comment by mondlicht-und-sterne** [comment]
Ich kann keine Sticker erstellen. Ich bin an neuen Stickern interessiert, für meine Ausstellungen zum ausstellen.

**Comment by pstorch** [comment]
I still like the current design

**Comment by dennisguse** [comment]
#1317

**Comment by yuval-herman** [comment]
I am not a designer but I do know my way around inkscape. If you have any idea about a new sticker I'd more then happy to help you out!

**Comment by dennisguse** [comment]
@yuval-herman not real ideas yet. 
The first sticker was inspired by these NASA mission badges and works okay as a sticker. 

As it is 3 years old already (and it took me 20min to draft the first design), I thought: can we do better?

**Comment by kristicunga** [comment]
Hello 👋 

Below you can find two versions for the sticker. If you help me with some more content, I can try something better.

What do you think? 🤔 

![OpenTracks-Sticker-Preview-Draft-1](https://user-images.githubusercontent.com/40668901/220101862-e3db0dce-aa9d-443b-932c-f0a64b9eb7cc.png)

Draft 1

![OpenTracks-Sticker-Preview-Draft-2](https://user-images.githubusercontent.com/40668901/220101860-0ee1a775-4c41-4d0e-be33-858d4410158e.png)

Draft 2

**Comment by dennisguse** [comment]
I somehow like draft two slightly more: it is better visible ;)

PS I guess, we don't need to mention Apache 2.0 anymore as it is likely not helpful (kind of too much information).

And we have an open issue for replacing privacy-proof by privacy-first (or something similar).

**Comment by kristicunga** [comment]
OK, so what content do you suggest me instead of the current one?

Can we chose something of [these bullet points](https://alternativeto.net/software/opentracks/about/)? 🤔

**Comment by dennisguse** [comment]
@kristicunga sorry for the real long delay.

What about these?
* A sport tracker that values your privacy
* Open-source for Android

And we could make it somehow cheesy: `with fancy features`.

**Comment by MartinH80** [comment]
@kristicunga Not sure if you are still willing to finish this, please let us know.

My design skills are quite bad, but I managed to make something in inkscape that is quite similar:

![opentracks_new2](https://github.com/OpenTracksApp/OpenTracks/assets/132921173/82fb8201-e3a2-421e-b57b-143d75147fb8)

I used larger fonts to make it more readable at small screens/sizes. I also put OpenTracks at the top as I expect that will be read first.

@dennisguse Please provide your feedback, next step would be my first feature branch, commit and pull request?

**Comment by MartinH80** [comment]
@dennisguse Thanks :-)

I have put opentracks at the top, as that is usually where you start reading it made sense to me, but I'm not a designer.

I might need to put some more time in it and try several things like:
- some white, maybe the opentracks text?
- the privacy and open source text in smaller font size?
- rephrase to 'An open source sports tracker for Android that values your privacy'?
- do we actually need to mention that it is open source for android?
- the black circle could be smaller
- .. maybe even more.

In the beginning I thought this was a small quick fix :-)

**Comment by MartinH80** [comment]
![opentracks2](https://github.com/OpenTracksApp/OpenTracks/assets/132921173/1c775f91-7cff-4230-8f4f-85d6af948190)
![opentracks3](https://github.com/OpenTracksApp/OpenTracks/assets/132921173/1f07684f-3579-4641-af15-60d86cda8417)
![opentracks4](https://github.com/OpenTracksApp/OpenTracks/assets/132921173/5310438d-fc89-4a13-ba1a-a59457e90f1a)

**Comment by MartinH80** [comment]
@dennisguse Ok, hereby some alternatives. The longer it takes, the harder it gets :-)

**Comment by dennisguse** [comment]
I think we should go with three items as more than 120° are hard to read and shorter texts (max 6 words). And in the 2nd and 3rd, the ratio between black and yellow seems to be odd. 

PS just typing on a phone in the middle of nowhere

**Comment by dennisguse** [comment]
@ch3thanhs if you have fun doing graphic things: this topic is open since ages :D

**Comment by ch3thanhs** [comment]
@dennisguse Sure, will try to come up with something.

**Comment by ch3thanhs** [comment]
Here's my first draft, I've kept it very simple.

I'll continue to work on other variants over the weekend.

<img src=https://github.com/OpenTracksApp/OpenTracks/assets/76928501/f16571af-d979-4f3e-8b92-8d4d5e08cbd6 width=70%>

**Comment by dennisguse** [comment]
@ch3thanhs you can also go creative - the sticker must no be similar to the previous one (although it may be) :D

**Comment by ch3thanhs** [comment]
Draft 2 - 

<img src="https://github.com/OpenTracksApp/OpenTracks/assets/76928501/8233769e-47df-49d5-b0f4-71cb0cc9798e" width=50%>

**Comment by ch3thanhs** [comment]
Draft 3 - 

<img src="https://github.com/OpenTracksApp/OpenTracks/assets/76928501/6effba3f-23fd-4c99-996c-1b421dce1dd8" width="55%">

**Comment by ch3thanhs** [comment]
Draft 4 - A laptop sticker?

![Chaos](https://github.com/OpenTracksApp/OpenTracks/assets/76928501/02264b10-639e-461e-be3a-81a7ea5bc6e4)

**Comment by dennisguse** [comment]
@ch3thanhs they all look kind of great!
For no real reason, I would prefer Draft nr. 2.
How should we proceed?

@pstorch @rgmf any ideas?

**Comment by pstorch** [comment]
I also like Nr. 2. Although the others are not bad either. @ch3thanhs good work.

**Comment by ch3thanhs** [comment]
@dennisguse, @pstorch, Thank you!

I made some minor changes - 

![One](https://github.com/OpenTracksApp/OpenTracks/assets/76928501/300c3a56-0686-4d05-93a0-77deaf61f3cd)

Let me know if you prefer the initial version.

**Comment by rgmf** [comment]
> @dennisguse, @pstorch, Thank you!
> 
> I made some minor changes -
> 
> ![One](https://private-user-images.githubusercontent.com/76928501/307399258-300c3a56-0686-4d05-93a0-77deaf61f3cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTA1MjQsIm5iZiI6MTcwODcxMDIyNCwicGF0aCI6Ii83NjkyODUwMS8zMDczOTkyNTgtMzAwYzNhNTYtMDY4Ni00ZDA1LTkzYTAtNzdkZWFmNjFmM2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE3NDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZmIyNzFlYTEyZmExOTAxYzQ4MGM3ZTRjYTU1ZmM3YTNhZDE1ZGY3ZmViOTFkN2M0YmE4Mjc1NmRiNmI5NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vaDJ89gwbsQZ-v7WVq_2BnY17VugugNOuOFeX7KMce0)
> 
> Let me know if you prefer the initial version.

I love it :heart:

**Comment by dennisguse** [comment]
@ch3thanhs that looks great!
Can you create a PR for logo nr. 3?
I guess, it goes into the `promotion`-folder (and we need to move the other files around ;)
And we can also replace the feature graphic for F-Droid: `fastlane/metadata/android/en-US/images/featureGraphic.png`
This one actually never looked great in F-Droid....

And I would then try to figure out how to get some stickers printed aka a PDF with the correct information how to cut the stickers...

**Comment by dennisguse** [comment]
Closed by 6657eca54d3aecd3daeb862877cc2dabddfc0e0b

**Comment by dennisguse** [comment]
@ch3thanhs I just got some printed stickers :D 
Great work!

![IMG_20240702_204216](https://github.com/OpenTracksApp/OpenTracks/assets/2820825/991033af-4dff-4398-be94-55f544f624b7)
