### ISSUE TITLE
More wheel circumference options for bluetooth sensors (hometrainer without wheel)

### ISSUE THREAD

**Issue by PolGZ** [OpenTracksApp/OpenTracks#1447]
I have an [elite turno](https://support.elite-it.com/en/categories/5da87279390bf16f7ea20597/5ddfb3179710560dc34625c4/information) "home trainner" with [Misuro B+](https://support.elite-it.com/en/categories/5e8d7943d15ce72da9aada40/5e99cbecd15ce72da9aada43/information) sensor.

On its configuration manual it says: 

_*Using the Misuro B+ sensor with other devices/cycle computers or non-Elite apps requires indicating hometrainer roller diameter data instead of wheel diameter data, as the sensor is applied to the hometrainer._

Also:

_You need to set wheel circumference on the device to calculate speed properly. The circumference to set refers to your bike's wheel, even if you remove it to use the hometrainer.
_This value changes depending on if you're using the My E-Training app or another app / device. With My E-Training you need to set wheel circumference (i.e.: 2095mm)._
_**If you're using a different app or device the value to set is: Value=wheel circumference [mm] / 15.34**_
For instance, with 2095 mm wheel circumference the value to set is 2095 / 15.34 = 136,6 > 137 mm_
_NOTE:_
_An incorrect hometrainer set-up might cause inaccurate power data_

Therefore, I need to indicate to OpenTracks a circumference of 137mm, but it is not possible. It only accepts 4 numbers values (e.j. 1370), resulting in incorrect speed calculations (I wish I were going at 200 km/h!!)

It does not accept 0137mm.

**Comment by dennisguse** [comment]
Done.
The change will be in tomorrows Nightly build.
You can get this via the F-Droid client from this repository: https://fdroid.storchp.de/fdroid/repo/
