### ISSUE TITLE
Bluetooth sensor statistics missing from recorded tracks in v4.2.0

### ISSUE THREAD

**Issue by Salvoxia** [OpenTracksApp/OpenTracks#1448]
Hi, 

I use OpenTracks for recording my cycling sessions with bluetooth speed-, cadence- and power-meters connected.
After updating to v4.2.0 (F-Droid) average/max cadence and average power are now missing when displaying old recorded sessions. The data is still there in the diagrams, but no longer in the stats (first page).
Am I missing something or is this a bug?

Best Regards,
Salvoxia

v4.1.2 vs v4.2.0
![OpenTracks_v4 1 2](https://user-images.githubusercontent.com/6501566/213308439-8b27208e-9888-434e-92cf-038b1c309967.jpg) ![OpenTracks_v4 2 0](https://user-images.githubusercontent.com/6501566/213308443-c5dc271c-f207-4e35-be96-77b87770ad27.jpg)

**Comment by dennisguse** [comment]
Good question. 
I have to check....

**Comment by dennisguse** [comment]
Found it: functionality was removed and needs to be re-implemented due to some technical changes for other UI features.

Here is the issue for this: #1426
