### ISSUE TITLE
Add 2 workouts without GPS, with the ability to edit the distance of the workout.

### ISSUE THREAD

**Issue by MrS1R1US** [OpenTracksApp/OpenTracks#1452]
Since it is winter now, in Ukraine with war there and some difficulties with electricity and street lighting, please add 2 types of training: Elliptical trainer and Treadmill. I'll be very thankful.

Also, if possible, please add the ability to edit the distance to specify it from the bike path or elliptical trainer.

I'm adding large icons, maybe someone can add a person to the Elliptical trainer:
![Слой 2](https://user-images.githubusercontent.com/25895221/214577670-04eea9d2-7011-4231-99d2-feb71ca6ee65.png)
![Слой 1](https://user-images.githubusercontent.com/25895221/214577642-9e49a125-e439-46d4-9be1-6e7c815d4954.png)

**Comment by dennisguse** [comment]
How would you call these two sports (in English)?
I can add those already without the icons.

PS/ entering distance manually; see #937.
This is requires quite some refactoring.

**Comment by MrS1R1US** [comment]
> How would you call these two sports (in English)? I can add those already without the icons.
> 
> PS/ entering distance manually; see #937. This is requires quite some refactoring.

"Elliptical Workout"
and 
"Treadmill workout"

You can temporarily use these icons, one of which will be finalized and replaced. The second icon should suit the style of the application.

Thank you.

**Comment by dennisguse** [comment]
@MrS1R1US Are the icons ready to use?
