### ISSUE TITLE
STATS page bpm field shows sensor name+MAC, not heart rate

### ISSUE THREAD

**Issue by awm0** [OpenTracksApp/OpenTracks#1465]
![Screenshot_20230203_212657](https://user-images.githubusercontent.com/124404838/216721666-d883d32a-c60b-4f0e-b4a2-83052e1d4e51.jpg)
Version 4.2.1 5132, all prevous versions I used since end 2021 worked fine

**Comment by dennisguse** [comment]
Already fixed; see #1455. 
And available in the nightly. 

@rgmf @pstorch Could on of you create a release?
I don't have a computer at hand in the next days.
That would be great 😎

**Comment by pstorch** [comment]
Not done it before, but the documented release process looks familiar. I'll give it a try.

**Comment by dennisguse** [comment]
@pstorch looks great!
Thanks :)

**Comment by pstorch** [comment]
Release [v4.2.4](https://github.com/OpenTracksApp/OpenTracks/releases/tag/v4.2.2) is tagged and on it's way to F-Droid (hopefully).
