### ISSUE TITLE
.gpx only shows heartrate dot in graph when there is simultaneous GPS coordinates after import into GC

### ISSUE THREAD

**Issue by awm0** [OpenTracksApp/OpenTracks#1466]
OpenTracks 4.2.1 5132, Golden Cheetah 3.5 Appimage
Steps for Reproduction:
Record indoor Activity (e.g. rowing) in OpenTracks with GPS activated (don't know how to deactivate for indoor)
using Polar H10 belt
Tab "Plot by time" shows continuous heart rate graph throughout activity
![Screenshot_20230203_232447](https://user-images.githubusercontent.com/124404838/216732029-d70638a1-f52b-4317-adae-5888188b4cac.jpg)
Export to .gpx
Import .gpx to GoldenCheetah
![Screenshot_20230203_231422](https://user-images.githubusercontent.com/124404838/216728513-f596f7df-edfa-41ca-ad83-ddd48cc841d2.png)
The heart rate graph (red) shows wide gaps
Export to .csv
(Import into GC not possible, no valid data error)
[2023-01-07_11_58_59.508_2023-01-07T11_58Z.csv](https://github.com/OpenTracksApp/OpenTracks/files/10583542/2023-01-07_11_58_59.508_2023-01-07T11_58Z.csv)
Spreadsheet in LibreOffice shows that heartrate values are present throughout the recording,
The periods with plotted heartrate graph in GC correllate with the presence of GPS coordinates in .csv (and .gpx?!)

**Comment by dennisguse** [comment]
Sadly, the GPX standard doesn't support data without coordinates.
So, OpenTracks ignores the intermediate data points if no coordinates are present. 

This is support by KML though and OpenTracks exports all data points.

**Comment by dennisguse** [comment]
IIRC GoldenChetah doesn't support KML import, right?
