### ISSUE TITLE
UI: search's close icon might be overlapped

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1493]
**Describe the bug**
In the tracklist, the close button from the search may be overlapped by the record start button. 

**To Reproduce**
1. Go to Track Lidt
2. Click on search icon in action bar 
3. Depending on the screen width the close icon for the search might be overlapped

**Technical information**
 - OpenTracks version: v4.2.2
![Screenshot_20230224-214040.png](https://user-images.githubusercontent.com/2820825/221581563-b5f6e7a2-9831-462d-89f8-1f2541af33e8.png)

**Comment by rgmf** [comment]
Good catch!! It seems it only happens in some phones, so I guess it depends on the resolution... so we have to think a better solution.

**Comment by dennisguse** [comment]
Wasn't me ;)
I got the report via email same days ago....
