### ISSUE TITLE
Rework stats_layout

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#15]
The `stats_layout` (used by `TrackDetailActivity`) has highly nested layout.
This should be simplified to make maintenance easier as well as the layout faster.

Using `GridLayout` would an option.

**Comment by dennisguse** [comment]
Partly done in #229.

**Comment by rgmf** [comment]
> Using `GridLayout` would an option.

What do you think about ConstraintLayout? The highly nested layout would disappear. I could follow #229 trying to convert the nested LinearLayouts to ConstraintLayout.

**Comment by dennisguse** [comment]
@rgmf +1
I just don't like that adds a dependency - but that is a personal opinion.

**Comment by rgmf** [comment]
@dennisguse then a GridLayout will be the best option.

**Comment by dennisguse** [comment]
@rgmf Don't worry, I will get over it.
You can just give it a try if you want.
I mean the ConstraintLayout might also get rid of these empty spaces that under some settings occur.
So, I guess it is worth a shot ;)

**Comment by rgmf** [comment]
Done in #229
