### ISSUE TITLE
Bluetooth sensors broken after updating to Android 13

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [OpenTracksApp/OpenTracks#1512]
**Describe the bug**
I can choose my Bluetooth devices from the OpenTrack settings but no input is recorded or shown.

**To Reproduce**
Android 13, Bluetooth speed sensor DuoTrap S.

If applicable:
* add screenshots
* add logcat output

**Technical information**
 - Device: Note 10 iodeOS
 - OS: 4.1 
 - OpenTracks version: 4.3.0

**Comment by dennisguse** [comment]
Mhhh. 
Hypothesis: There might be a missing/not granted permission. 

1. Can you check that Bluetooth permissions are granted?

2. Can you remove all permissions for OpenTracks (set them to ask everytime)?

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Confirmed issue is not with OpenTracks.

**Comment by dennisguse** [comment]
@ae5960e8-a6fc-491f-b252-898ecf59af95 how did you solve it?

**Comment by dennisguse** [comment]
@ae5960e8-a6fc-491f-b252-898ecf59af95 and can you add the sensor (as it is working) to the DEVICES.md?

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Haven't solved it, the issue is with the new version of the OS my phone is on, so the issue isn't with the app.
