### ISSUE TITLE
GPS jumps

### ISSUE THREAD

**Issue by dizmoduck** [OpenTracksApp/OpenTracks#1519]
yesteday when I track a walk the recording show this. 

I just stated the recording the normal way and saved It right aften I stop the recording 

If applicable:
* add screenshots
* add logcat output

**Technical information**
 - Device: Balckview 8000 pro
 - OS: Android 8
 - OpenTracks version: 4.3.0 version code 5151

![Screenshot_20230411-101033](https://user-images.githubusercontent.com/8668926/231099845-d959fffe-0f12-4b9f-8d47-9878997a2e67.png)
[2023-04-10_14_44_46.911_2023-04-10T14_44+02.zip](https://github.com/OpenTracksApp/OpenTracks/files/11198318/2023-04-10_14_44_46.911_2023-04-10T14_44%2B02.zip)

**Comment by dennisguse** [comment]
Sadly, that is normal. 
I guess, it it the first track point (the outlier). 
What might have happened:
1. You started the recording
2. Your phone started the GPS 
3. ... The first Location reported might be (a) cached or (b) based upon some other technology (like mobile network)
And your phone reported this with a sufficient accuracy, so OpenTracks accepted it. 
Default threshold is 50m IIRC - everything above will be rejected.
