### ISSUE TITLE
UI shows incorrect language

### ISSUE THREAD

**Issue by nthtimes** [OpenTracksApp/OpenTracks#1527]
UI shows incorrect language in some cases.

Language settings:
- zh-TW: It shows the en language
- zh-HK: It shows the zh language

**Technical information**
 - Device: ASUS Zenfone 6 (2019)
 - OS: OmniROM 13
 - OpenTracks version: v4.3.0, v4.3.1

**Comment by dennisguse** [comment]
IIRC that is the default behavior for missing translations in the regional specific locales. 
First check zh-tw, then zh and then fallback to default  (on Android this is en-us).

**Comment by nthtimes** [comment]
I note an untranslatable string named settings_layout_reset_key was translated in values-zh-rTW/strings.xml.
Is this the reason?

**Comment by dennisguse** [comment]
Actually, those should not be translated as they are purely technical. I will remove these translations.

**Comment by dennisguse** [comment]
Since you are on Android 13, how do you set the language?

PS/ `settings_layout_reset_key` is now in the correct file and cannot be translated anymore.

**Comment by nthtimes** [comment]
To set the language as zh-TW:
1. Going into "App info\Language" on OpenTracks.
2. Choose "中文 (台灣)", that is "Chinese (Taiwan)"

**Comment by nthtimes** [comment]
This issue started in v4.3.0.
In the old version 4.2.2, I got the correct language that same the system setting.

**Comment by dennisguse** [comment]
@elastic-rock this seems to be an effect of #1468.
Any ideas?

**Comment by dennisguse** [comment]
@elastic-rock ping

**Comment by elastic-rock** [comment]
I confirm that I am alive and know about it, but I unfortunately had not the time to do it yet. I shall do it in a week max.

**Comment by elastic-rock** [comment]
https://github.com/OpenTracksApp/OpenTracks/pull/1540#issuecomment-1528784034

**Comment by dennisguse** [comment]
@nthtimes could you check that this fixing your issue?
Nightly is already available and F-Droid might take some days as usual.

**Comment by nthtimes** [comment]
It is correctly shows my language now.
But I found that all the regional option are getting the same translation, the Traditional Chinese (Hong Kong) seems to show zh-TW translation.

**Comment by dennisguse** [comment]
So, now it gets dirty.

I did some digging into when things started going wrong.

I compiled the APK for different versions and checked the included locales `resources.asc/strings`
* v4.3.4 does include 44 locales (no country-specific locales)
* v4.3.0 does include 44 locales (no country-specific locales)
* v4.2.2 does include 92 locales (everything is included)

In the repo, we have 54 locales...

So, all the configuration for Android 13's per app language support (included in v4.3.0) some leads to omit locales (especially country-specific locales).
This is not fixed by autogenerating these config files as it is done in v4.3.4 (Android build tools 8.1.0).

**Comment by dennisguse** [comment]
... but all that does not explain why the wrong regional locale is shown now.

**Comment by dennisguse** [comment]
@nthtimes could you check if this is still broken for you using the v4.3.5?

**Comment by dennisguse** [comment]
I just tested this using an Android 13 emulator and replaced zh, zh_HK, and zh_TW with a locale I can distinguish.
When doing this I get three different localizations.

The regions I get shown are these (screenshot below).
I translated the screenshot using Google Translate and all looks good.

Don't really know what else to test :/

![image](https://github.com/OpenTracksApp/OpenTracks/assets/2820825/c70664a4-924a-4d87-8772-fe86de517de0)

**Comment by nthtimes** [comment]
![Screenshot_20230520-045107](https://github.com/OpenTracksApp/OpenTracks/assets/50926809/a21b9403-c9bf-4378-93a6-a6ab51a0c658)
![Screenshot_20230520-045130](https://github.com/OpenTracksApp/OpenTracks/assets/50926809/c1e7616d-7614-4e7c-bcde-c55e5b68baec)
![Screenshot_20230520-050423_1](https://github.com/OpenTracksApp/OpenTracks/assets/50926809/24122c29-5bb8-4e68-b10a-249692c4b17c)

After changing into zh_HK traslication, it seems good, but not.
I think I got the zh_tw translation, because the zh_hk translation has no any the translated strings in About OpenTracks.

**Comment by dennisguse** [comment]
In Weblate, we have three flavors of Chinese:
* https://hosted.weblate.org/projects/opentracks/opentracks-src-main-res-values-strings-xml-main/zh_Hant/#information mapped to `zh`
* https://hosted.weblate.org/projects/opentracks/opentracks-src-main-res-values-strings-xml-main/zh_Hant_HK/#information mapped to `zh-rHK`
* https://hosted.weblate.org/projects/opentracks/opentracks-src-main-res-values-strings-xml-main/zh_Hans/#information mapped to `zh-rTW` (Taiwan)

First, I don't know why Weblate is mapping zh_Hans to zh-rTW.
Second, Android will use `zh` aka zh_Hant as fallback if a translation is `zh-rHK` is missing.
Some more infos here: https://developer.android.com/guide/topics/resources/multilingual-support


I am really at a loss here on how to continue.
