### ISSUE TITLE
Add export to relive (gpx or tcx) 

### ISSUE THREAD

**Issue by Flavien06** [OpenTracksApp/OpenTracks#153]
Hi, actually export is to kmz.
it is possible to change default format to gpx or tcx.
or option to convert and share in gpx for send to relive app?
thank

**Comment by dennisguse** [comment]
What kind of export are you referring to?
I guess the share or the show on map functionality? 

Tcx is not implemented.
I have the feeling it was some time ago and I removed it....

**Comment by Flavien06** [comment]
I need an option to export the course in gpx and share it immediately with other application

**Comment by dennisguse** [comment]
I see. I put it on the roadmap, but with low priority. Pull Request welcome.

**Comment by pirovc** [comment]
If you open the track with OsmAnd you can export the gpx directly

**Comment by dennisguse** [comment]
@Flavien06 Could you describe your desired solution?

**Comment by dennisguse** [comment]
I guess, #225 is a duplicate but provides a nicer description.

**Comment by Flavien06** [comment]
> 
> 
> @Flavien06 Could you describe your desired solution?

Actualy the "share" button share .kmz file.
I want this button "share" (export) in gpx.

A general option for chose the output file.
Or a second button to convert .kmz to .gpx and share it.
