### ISSUE TITLE
Serious privacy concerns caused by misleading information

### ISSUE THREAD

**Issue by HFPasfho** [OpenTracksApp/OpenTracks#1533]
**Describe the bug**
OpenTracks description emphasise how much it values users privacy but after update [v4.3.0](https://github.com/OpenTracksApp/OpenTracks/releases/tag/v4.3.0) I have serious doubts about that. OpenTracks description clearly states that it has [**"No Internet access or extra permissions."**](https://f-droid.org/en/packages/de.dennisguse.opentracks/) yet update [v4.3.0] brings a feature that **"Allow backups (incl. encrypted to the Google)"**. This is pure contradiction since you can't have both **no internet access** and **backups to Google** at the same time. That's why one of this information is a **lie** and lies don't inspire much confidence. I held off on updating and I'm waiting for some explanations

**Comment by dennisguse** [comment]
RTM: https://developer.android.com/guide/topics/data/autobackup

We just allowed the Android OS to make backups (or basically told it that it would be okay to make backups). OpenTracks itself cannot control what the OS is actually doing - it is just a hint.
And as a hint we tell the OS that backups are fine (locally via ADB as well as cloud if they are encrypted).
Usually cloud means Google here (via PlayServices)...

Some more discussion here:
* https://github.com/OpenTracksApp/OpenTracks/issues/346
* https://github.com/OpenTracksApp/OpenTracks/issues/710
* https://github.com/OpenTracksApp/OpenTracks/pull/1495

If you don't like this, it is still an option to compile OpenTracks yourself.

**Comment by HFPasfho** [comment]
@dennisguse Thanks for your reply but this links actually confused me a bit. It's clear that you were die-hard opponent of backing up things to goolge servers yet when @mamoit made a PR implementing this feature you gladly incorporate it into the project. Why? Why such a significant change of opinion?

**Comment by dennisguse** [comment]
When client-side encryption could be enforced, I wasn't an opposed anymore as I don't use these features at all.
I was just not interested to implement it.

My argument is simple: a lot of people want to do local backups via ADB. Google (I guess) decided to only allow ADB backups if Cloud backups are enabled while at least "enforcing" Client-Side encryption.

If an OpenTracks user is using a phone with PlayService installed (the user's decision to use such an Android) and the user enables Cloud Backups to Google servers (again the user's decision), then why should OpenTracks not respect this?
All users without PlayServices will not be affected by this at all.

**Comment by dennisguse** [comment]
When client-side encryption could be enforced, I wasn't an opposed anymore as I don't use these features at all.
I was just not interested to implement it.

My argument is simple: a lot of people want to do local backups via ADB. Google (I guess) decided to only allow ADB backups if Cloud backups are enabled while at least "enforcing" Client-Side encryption.

If an OpenTracks user is using a phone with PlayService installed (the user's decision to use such an Android) and the user enables Cloud Backups to Google servers (again the user's decision), then why should OpenTracks not respect this?
All users without PlayServices will not be affected by this at all.

**Comment by mamoit** [comment]
I don't use play services at all, but still get the benefits of the backups using [seedvault](https://github.com/seedvault-app/seedvault) on LineageOS.

Since a couple of android versions the backup API was open to other backup providers, so you may use whatever you want to perform the backups. You're only stuck with google if you want.

As it is now implemented in OpenTracks backups are only performed if they are client side encrypted.

**Comment by HFPasfho** [comment]
> All users without PlayServices will not be affected by this at all.

@dennisguse But all people with PlayServices struggling to keep last bits of their privacy are screwed. As a developer you live in a bubble and you think everyone is cracking their phones. But that's not true. Even ignoring the requirements of vast technological knowledge and accepting many compromises, in many cases it's actually impossible. And what with people that want to use their bank accounts from their phones? They can't root and flash their devices. And that's the vast majority of people. You should not treat their private data lightly. Especially when this data is health-related. The worst type of data that morally devoid corporations prey on. I'm very disappointed because it's not what this project stood for and how it is STILL advertised to this day.
You should really change your mind. Not because I, some random guy from the Internet, want so. Or that you should bend to my will and change your own project to my liking. No! But you are making a big mistake here and you lead this project in a very wrong direction.
But if you don't want to change anything and you want to keep it like this at least be honest with poor unaware people entrusting you with their data and change the app description and stop mislead people with false claims of privacy and giving us the users a fake sense of privacy.

**Comment by pstorch** [comment]
@HFPasfho to my understanding: do you really see an issue with client side encrypted backups stored on google servers? They cannot do anything with it. What attack vector do you see?

Just a different point of view. Here is someone complaining, that developers disable backups for their apps and asking F-Droid to "break" it open: https://forum.f-droid.org/t/please-f-droid-free-our-data

**Comment by dennisguse** [comment]
@HFPasfho as it really seems to bother: you can also create a build variant that does not allow backups and publish it via Fdroid.

We have a similar approach for the OSM Dashboard (one variant with Internet and one offline only).

**Comment by HFPasfho** [comment]
@dennisguse Then why not created OpenTracks version without this "feature"? As you pointed out OSM Dashboard uses this approach.
>You can also create a build variant that does not allow backups and publish it via Fdroid
Solution to "create a build variant"

This isn't a solution because I'm clearly not a developer.

Also I still stand that current app description is misleading and should be changed to reflect last changes.

@pstorch How can I be sure that Google encryption on google OS is secure? They backup encryption key on their servers for sure. If not because of their malice then because of agencies forcing them.

**Comment by pstorch** [comment]
@HFPasfho so you don't trust Google to proper encrypt the backup on the client side, but you would trust your Google OS to respect the "no backup" option of an app? Your Google OS has full access to everything on your phone. 
Don't get me wrong. I don't want to argue against your request. But I have some difficulties to understand.

**Comment by HFPasfho** [comment]
@pstorch I understand that this is difficult to understand. It's because google makes keeping your privacy so hard that everything you try to do seems pointless. Our situation is so bad and hopeless then even just trying to oppose google's malicious actions seem ridiculous to many.
