### ISSUE TITLE
Record only on gyro activity

### ISSUE THREAD

**Issue by Bernie-KN** [OpenTracksApp/OpenTracks#1541]
Often my hiking tours are interrupted by a few drinks, sandwiches and photos (digicam). Although inactivity and accuracy parameters are set, I get spikes (waypoints) up to 100m around my true location, which unnecessarily lengthen my recorded routes.

Would it be possible to implement an option that only records when gyroscope sensor activity is detected (with adjustable threshold)?

**Comment by dennisguse** [comment]
Like #30?
I never had the time to build this, but it is doable (if somebody) has the time...

**Comment by dennisguse** [comment]
Will not be necessary after implementing idle detection via timeout.
We can make the distance before switching from idle to non-idle configurable.

See #1187
