### ISSUE TITLE
Occasional huge speed tracking bicycle with bluetooth speedometer

### ISSUE THREAD

**Issue by rjo12** [OpenTracksApp/OpenTracks#1557]
On occasion, when stopping riding for a short period (dismounted to safely cross a road with heavy traffic) the recorded speed in that time period is huge.

In one short bicycle ride yesterday my recorded statistics show I reached a maximum speed of 2394.0 km/hr

Uncertain how to reliably reproduce during a ride, and I suspect relatively uncommon edge case(s).

However, I believe I've managed to track down a contributor, so suggest a FIX.

Relevant recorded speeds from KMZ file (two points before and after)

<value>2.9</value>
<value>0.1</value>
<value>665</value>
<value>665</value>
<value>2.5</value>
<value>2.5</value>

The 665 value is consistent with incorrect handling of a 16-bit unsigned underflow (and then dividing that incorrectly underflowed result by about 1000).   That gave me enough information to track down (what I believe is) a contributor in OpenTracks/src/main/java/de/dennisguse/opentracks/sensors/UintUtils.java (which is used in computations in sensors/SensorDataCyclingSpeed.java and for other sensors)

In the function diff() the last line is

      return (UINT_MAX - b) + a;

and should be

      return (UINT_MAX - b + 1) + a;

Rationale:   The function diff() is emulating an unsigned subtraction of a - b, which works modulo UINT_MAX + 1, not UINT_MAX  (so, for example, subtracting 1 from 0 should produce UINT_MAX, not UINT_MAX-1).

**Technical information**
 - Device: [Motorola G9 Play]
 - OS: [Stock.   Build RPXS31.Q2-58-17-7-3   (latest update currently available)
 - OpenTracks version: v4.3.4  (latest currently available through F-Droid)

**Comment by dennisguse** [comment]
Thanks!

Can you create a PR for this incl. a test?
