### ISSUE TITLE
The wording of GPS accuracy

### ISSUE THREAD

**Issue by macias** [OpenTracksApp/OpenTracks#1573]
*Thank you for very interesting app*

**Describe the bug**

The wording of GPS accuracy is odd to me.

**To Reproduce**
1. Go to application settings
2. Select "GPS" section
3. Look at the description of "GPS accuracy"
4. It says "Location is ignored if its accuracy is **less** than X m".

IMHO it should read "more", because let's say you have set limit as 10m. Now you acquire position with 9 m accuracy, it is pretty solid, yet it is rejected because it is too accurate? It should be rejected if position has 11 m accuracy (more than limit).

**Comment by dennisguse** [comment]
Yes, you are right!
Nice finding ;)

Can you create a pull request?

**Comment by macias** [comment]
As for the pull request, only blindly, I didn't proceed further because there is information (no surprise) about checking tests and all. So I would like to help, but in this very moment (I have to pack before my trip) I won't be able to configure all environment necessary.

I am sorry for that.

**Comment by dennisguse** [comment]
@macias don't worry. 
It should just be a change in the strings.xml (without any tests to be changed).
Will take care about this.

Enjoy your vacation!

**Comment by dennisguse** [comment]
Done aka fix en-US and removed all it's translations.
