### ISSUE TITLE
feature request: delayed start

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1578]
For those of us that upload our tracks to fitness sites and other places, it would be nice if i could set a universal delayed start before track recording, so every track does not start at someone's house or other significant location.
For better privacy. 

IE: almost every track i have uploaded here starts at a buddies house as i start the app while i wait for him to get ready.  Same thing with all the tracks i share or upload to fitness sites.
It would be nice if everytime when i started the track it would wait 5 mins before recording. Then the track would start at roughly the same distance from my start location so i can still compare overall performance.

Not sure how many other people would use this feature, but i know i would use it every time.

**Comment by dennisguse** [comment]
Related #240 and #375.
