### ISSUE TITLE
faq: with known working devices.

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1592]
I've got a few heat rate monitors and a couple of cadence devices, to be honest trying to find out if a device is supported by a app is like trying to be a prophet with tea leaves.

A faq with a list of known working devices would be fantastic, maybe a GitHub page where just about anyone can report that their device seems to work out not.  What's apps to use to test connections, how to report info and specs. 

With links to Amazon or other places to buy the exact device would be like sliced bread, just easier.

**Comment by pstorch** [comment]
> How would someone suggest to add a device to this list?

Edit the file and send a PullRequest with your suggestions.
