### ISSUE TITLE
disable gps. track sensors by time

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1593]
A friend loves how simple this app is when i use it however they only use stationary machines like bikes and treadmills, they have no use for the gps to be enabled. They just need the sensors like heart rate, cadence etc to be recorded by time for their workout.

There obviously would need a different file format to save the info since kml and gpx are for gps data. I'll have to look into what other apps like runnerup use (seems Garmin .tcx is pretty popular but I'll keep looking for a open standard)

**Comment by dennisguse** [comment]
That's easy. 

This has been working for quite a while. 
They need a Bluetooth Sensor that provides distance (like for cycling or running). 

Nitpick: GPS permission is required, but the GPS can be turned off by Android. 
If it is turned off, OpenTracks will not use it. 

And for export: KML supports data points without coordinates. Don't know any tools that support to import it though as I never needed that).
