### ISSUE TITLE
Osm dashboard recognised 

### ISSUE THREAD

**Issue by dadudeme** [OpenTracksApp/OpenTracks#1594]
I am on android 13 and can't see the option to select Osm dashboard to display a map. 
Osm dashboard is installed on version 2.19.0 and running in the background. 

**To Reproduce**

If applicable:
* add screenshots
* add logcat output

**Technical information**
 - Device: Motorola g23
 - OS: Android 13
 - OpenTracks version: 4.4.0
![Screenshot_20230610-150308](https://github.com/OpenTracksApp/OpenTracks/assets/79927205/39c1d7d0-a816-4068-a706-4c66d5c451db)

 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

**Comment by dennisguse** [comment]
Go to Settings->User Interface->Select "show on map"-behavior and chose the one you desire.
