### ISSUE TITLE
support for ble devices that don't pair.

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1600]
It seems there are a number of ble devices that will never pair to s smart phone, but they can still be used. 
(https://www.amazon.ca/POSMA-Bluetooth-Cycling-Computer-Monitor/dp/B07VSLL5HQ)

The app looks for and finds the device  connects and it just works.
Eg: 
https://github.com/jonasoreland/runnerup
(Setting-sensors-heart rate-experimental-Bluetooth le then scan)

The devices appear to have standard connection ability, just are designed to send without pairing to devices, likely for a cheaper head unit with less user feedback

(https://play.google.com/store/apps/details?id=com.niruha.blescanner.
 Shows a lot of ble information Scott connectable devices)

(Might be better scanner 
https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp)

**Comment by dennisguse** [comment]
Actually, OpenTracks does not require BLE devices to be paired.
It just stores the address and when a recording is started, it tries to connect.

Or what is the suggestion?

**Comment by nutpantz** [comment]
at the moment, open tracks has no method to look for devices that are not paired that i can see. 
If the device is not paired it never shows up on the list to select.. 
So there would be a scan for all and select to use option for heart rate (and any other devices) needed.

Ie I can be connect and watch  the info with nrf and nothing is listed in open tracks.

**Comment by dennisguse** [comment]
Actually that is what OpenTracks is doing.
It scans for all devices that announce a certain BLE service (e.g., heartrate) and then it will be shown.
If the device doesn't announce the required service in it's announcements packets (like PineTime for heartrate), this filter can even be deactivated.
... but the list may get very long depending on where you are.

The filter can be deactivated in the settings page for BLE; it is the last one.

**Comment by nutpantz** [comment]
Open tracks crashed and dumped a log
![20230611_124149](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/7679d29d-7ff8-44b3-81dc-f311945553d2)

**Comment by nutpantz** [comment]
This one can be closed, since it was an inaccurate issue
