### ISSUE TITLE
moving time is incorrect.

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1611]
[2023-06-17_12_34_21.193_2023-06-17T12_34-07.txt](https://github.com/OpenTracksApp/OpenTracks/files/11782335/2023-06-17_12_34_21.193_2023-06-17T12_34-07.txt)
**Describe the bug**
The moving time vs total time is always incorrect.
95% of my tracks are 100% moving. But there is always a big difference between moving time and total time, sometimes very significant.
Possibly caused by trees ( not sure how it could be this bad since the gps is very very sensitive)

Track included
Rename to kmz

**Comment by dennisguse** [comment]
What where you doing (aka which speed)?
And how was the landscape (aka GPS reception)?

**Comment by nutpantz** [comment]
Speed was about 5-6 kph average 90% of the time. 30% tree coverage that never seems to reduce gps signal when i check it (under 3 meter fix) the rest under open sky (1 meter fix)

**Comment by dennisguse** [comment]
Problem: OT uses (GPS) speed to determine moving/non-moving only.
(GPS) speed is very unreliably - especially when being slow aka walking.

Would be fixed by #1187.
