### ISSUE TITLE
Cannot add existing picture to marker

### ISSUE THREAD

**Issue by khao-soi** [OpenTracksApp/OpenTracks#1620]
**Describe the bug**
When I use the regular android camera app to take a picture of something and try to add that picture to a marker, it says "cancelled, no photo marker added". I also tried to add the picture via the internal photo function and the galery preview of the camera view, but I can only see the picture there but can't apply it as the markers image.

Or am I doing something wrong? What is a photo marker and how does it differ to a regular marker?

**To Reproduce**
1. Take a picture of anything
2. Have a track with a marker
3. Go to that marker
4. Click edit icon (pen)
5. Click add image icon (not take photo icon)
6. See error "cancelled, no photo marker added"

If applicable:
![2023-06-27-132548_002](https://github.com/OpenTracksApp/OpenTracks/assets/2349590/f0e5712f-6bc1-42b7-9c67-62331927c1fa)

**Technical information**
 - Device: OnePlus 8T
 - OS: LineageOS 20.0
 - OpenTracks version: 4.5.0 (F-Droid)

**Comment by dennisguse** [comment]
Do you press the button in the camera that you want the picture that was just taken?
What seems to happen is that the camera app reports that no picture was taken and therefore none will be transferred to OpenTracks.

Can you create a video of what is happening?

**Comment by khao-soi** [comment]
I pressed the preview button in the camera with the picture just taken, yes. But that was just my attempt to workaround the not functioning "add image" button.

Here's a video:

https://github.com/OpenTracksApp/OpenTracks/assets/2349590/3e126554-884e-4a13-a0f6-6dbb0a64e932

**Comment by dennisguse** [comment]
Mhh okay.
Not sure what happens; actually an gallery activity should be opening.
I mean the first case should be working and the 2nd cannot (only allows taking new pictures).

Relevant code is in `MarkerEditActivity`; look for all three cases of `R.string.marker_add_photo_canceled`.

Any chance to get a logcat?

**Comment by dennisguse** [comment]
Or might be related to Android 13s permissions. 
https://github.com/Drjacky/ImagePicker/issues/73

**Comment by khao-soi** [comment]
Here come logcat. One filtered by PID and one unfiltered.

[logcat_opentracks.txt](https://github.com/OpenTracksApp/OpenTracks/files/11885524/logcat_opentracks.txt)
[logcat.txt](https://github.com/OpenTracksApp/OpenTracks/files/11885526/logcat.txt)

**Comment by khao-soi** [comment]
> @khao-soi can you try: #1621

Yeah I could. Give me some time to set up OpenTracks in my local dev env.

**Comment by khao-soi** [comment]
> @khao-soi can you try: #1621

Android Studio doens't want to start it.

`The project is using an incompatible version (AGP 8.1.0-rc01) of the Android Gradle plugin. Latest supported version is AGP 8.0.2`

**Comment by dennisguse** [comment]
@khao-soi We currently use the RC of AndroidStudio (due to a nice feature in AGP 8.1.0).
Hope the stable release comes soon :D
