### ISSUE TITLE
Pure black/OLED theme missing in v4.5.0

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [OpenTracksApp/OpenTracks#1625]
**Describe the bug**
The pure black/OLED theme isn't there anymore in the latest update.

**To Reproduce**
1. Go to User Interface > UI Theme
2. The black theme is missing

**Technical information**
 - OpenTracks version: v4.5.0

**Comment by dennisguse** [comment]
There was no specific OLED theme -it was just the dark theme. 
Is this not working for you?

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
I'm only seeing a dark purple theme as the dark theme, whereas I think there was a pure black toggle before.

**Comment by dennisguse** [comment]
That might be the dynamic color feature of MaterialDesign. 
So, we may need to implement a separate oled friendly theme then.

**Comment by dennisguse** [comment]
That's how it is done in F-Droid:
```
    /**
     * Apply pure black background in dark theme setting. Must be called in every activity's
     * {@link AppCompatActivity#onCreate()}, before super.onCreate().
     *
     * @param activity The activity to apply the setting.
     */
    public void applyPureBlackBackgroundInDarkTheme(AppCompatActivity activity) {
        final boolean isPureBlack = Preferences.get().isPureBlack();
        if (isPureBlack) {
            activity.setTheme(R.style.Theme_App_Black);
        }
    }
```

**Comment by dennisguse** [comment]
@ae5960e8-a6fc-491f-b252-898ecf59af95 If you have time, just do it. 
It is not on my personal agenda (also due to summer).

**Comment by dennisguse** [comment]
@ae5960e8-a6fc-491f-b252-898ecf59af95 If you have time, just do it. 
It is not on my personal agenda (also due to summer).
