### ISSUE TITLE
Current heart rate as speech output

### ISSUE THREAD

**Issue by VolkerGimmler** [OpenTracksApp/OpenTracks#1635]
**Is your feature request related to a problem? Please describe.**
The speech output options only allow selecting average heart rates (for rounds or the whole exercise).

**Describe the solution you'd like**
I would find it very useful to have the option to select the current heart rate (as on the display) for a speech output. 

**Describe alternatives you've considered**
I have tried to work with the average round heart rate, but that doesn't give me a clear idea of recovery times from short sprints. I have tried to just look at the phone (which is fine on the bike), but that works poorly when running.

**Additional context**
When I include sprints in my workout, the heart rate goes up rapidly for a short time. It is close to the peak at the end of the sprint. I would like to be able to hear that peak at the end of the sprint (which I plan according to the length of a round) and then get an idea of the recovery time until it is back to normal.

**Comment by dennisguse** [comment]
@VolkerGimmler Code is in VoiceAnnoucementUtils. 
The current heart rate is already available and only the voice announcement needs to be added. 
And a preference for turning this feature on/off.
