### ISSUE TITLE
Material 3 issue

### ISSUE THREAD

**Issue by neurer** [OpenTracksApp/OpenTracks#1636]
**Describe the bug**
Minor Material 3 issue with text being cut off in two places -- see screenshots:

![2023-07-11-170950_003](https://github.com/OpenTracksApp/OpenTracks/assets/6098965/324e125c-4190-4275-a8fa-6d937389d719)
![2023-07-11-170950_002](https://github.com/OpenTracksApp/OpenTracks/assets/6098965/f7e839bb-e853-4c1f-9174-243d053fbe5a)

**Comment by dennisguse** [comment]
This got fixed.
