### ISSUE TITLE
no values of gain/descent on track statistic screen

### ISSUE THREAD

**Issue by ironspock** [OpenTracksApp/OpenTracks#1642]
Hi,
running track collections/samplings no values of gain and descent are calculated and displayed on the track's statistic screen (buttom part of the track statistic screen). The displayed values of both properties are allways: "-" m

**Technical information**
 - Device: CAT S30
 - OS: Android 5.1
 - OpenTracks version: 4.5.0 (version code: 5262)

**Comment by dennisguse** [comment]
Your device has no barometric sensor and thus no gain/loss is recorded. GPS alone is too noisy.
