### ISSUE TITLE
Höhenberechnung falsch

### ISSUE THREAD

**Issue by Stromnetz** [OpenTracksApp/OpenTracks#1651]
OpenTracks ermittelt die minimale und die maximale Höhe einer Tour richtig. Bei der Berechnung der aufsteigenden und der absteigenden Höhenmeter ergeben sich aber völlig unsinnige Werte, z.B. 40.000 m. Bei allen meinen Touren ergeben sich immer Werte bei ca. 40.000 m.
Nachfolgend ein Auszug aus einem Track:

Maximale Höhe: 1125 m (3692 Fuß)
Minimale Höhe: 695 m (2281 Fuß)
Höhenunterschied: 45033 m (147746 Fuß)
Höhenverlust: 44640 m (146457 ft)

**Technical information**
 - Device: [Google Pixel 6a (2022)]
 - OS: [Android 13]
 - OpenTracks version: [v4.2.0]

**Comment by dennisguse** [comment]
Can you please check that the barometric sensor is working properly?
You can find the procedure here: https://github.com/OpenTracksApp/OpenTracks/blob/main/README_TESTED_SENSORS.md#tested-barometric-sensor-smartphones
