### ISSUE TITLE
nightly not recording any gps data

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1662]
Latest 2 nightly builds are not recording any gps data.
I start the nightly and start recording.
And nothing is recorded. No movement at all.
I am running the latest stable at the same time and another gps tracking app. Both of them record data.

As of today. Tested for over an hour. While driving
Good gps lock
3 meter accuracy
Android 9

I do get a toast that says "open tracks requires location permission" and it has it.

**Comment by dennisguse** [comment]
You need to grant location in background as well now. 
Is this given?

**Comment by nutpantz** [comment]
It's not an option for Android 9. Just location is an option.

**Comment by dennisguse** [comment]
All good; Android 9 was no happy that OpenTracks asked for a permission it didn't know.
Should be working again.
