### ISSUE TITLE
Calories Burnt Estimate

### ISSUE THREAD

**Issue by CoachDom** [OpenTracksApp/OpenTracks#1666]
Would it be possible to include a calories burnt estimate in the individual workouts?

It's always handy/motivational to see how much you spent on a given workout.

**Comment by dennisguse** [comment]
Calories burned is not really a useful metric, but  you are right, we could use something like this.
Some more thoughts: https://github.com/OpenTracksApp/OpenTracks/issues/118#issuecomment-571457531
