### ISSUE TITLE
Start of the week - selectable

### ISSUE THREAD

**Issue by natrius** [OpenTracksApp/OpenTracks#1681]
**Is your feature request related to a problem? Please describe.**
For almost half of the worlds population the start of the week is Monday and not Sunday. https://www.timeanddate.com/calendar/days/first-day-of-the-week.html 
Also https://en.wikipedia.org/wiki/Week

Its incredible annoying when filtering when this setting is missed. 

**Describe the solution you'd like**
Settings - User Interface - "Start of the week"
Let us choose between Saturday, Sunday and Monday

**Describe alternatives you've considered**
None

**EDIT for clarification:**
* Device: Xiaomi Mi 9
* OS: Android 10

Regional Settings: Tried UK, Austria, Germany

Every time it starts with sunday.

**Comment by dennisguse** [comment]
Actually, OpenTracks behaves region specific.
With English (US) it is Sunday.
With German (Germany) as well as  Spanish (Spain) it is Monday.
So, works as expected :D

Android 14 will support configuring certain settings per Language/Region.
https://developer.android.com/about/versions/14/features#regional-preferences

**Comment by natrius** [comment]
I had region UK and it was sunday. Changed the region now to austria and its still sunday. Changed the regional settings to germany, its still sunday. 

Every calendar app has included a setting for this, please open this issue again and it would be greatly appreciated if this would be a setting.

**Comment by pstorch** [comment]
![Screenshot_20230831_131045_Calendar](https://github.com/OpenTracksApp/OpenTracks/assets/5598124/655fa1fa-f231-4025-8ee8-e578e711468c)
![Screenshot_20230831_131106_OpenTracks (Nightly)](https://github.com/OpenTracksApp/OpenTracks/assets/5598124/f0707369-c33c-4f95-8fdb-6e1122040ccf)

**Comment by pstorch** [comment]
Tested again. The system setting which I showed above applies only to the stock calendar app, no other app respect that setting.
But when I change the language from english/us to english/uk, I get the starting date of monday.

**Comment by dennisguse** [comment]
Here is the code that is determining the start of the week: https://github.com/OpenTracksApp/OpenTracks/commit/b4ce99440a364485c5f2e08e238efefe7c9c3e14

It is not Android 14 ready :)

**Comment by dennisguse** [comment]
We may also think about migrating to MaterialDesign's DateRangePicker
