### ISSUE TITLE
Time announcement Speech output

### ISSUE THREAD

**Issue by Dr-Sommer** [OpenTracksApp/OpenTracks#1683]
Hi, it would be great to have an "Time of the day announcement " on every Intervall, so you know the exact Time in place,

For example:
Speech Output: 
"Time: 14:45","Total Route: 22KM". "Pace: 4:49", etc.

Thank You.

**Comment by dennisguse** [comment]
Something with TtsSpan in VoiceAnnouncementUtils.
However, this may be kind of tricky.
Additional aspects to keep in mind: 12 vs 24h.
