### ISSUE TITLE
are nightly s working?

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1703]
The last nightly i have listed is 4.8.2-6
My stable is 4.8.3

Is it building and posting correctly to the nightly server?

Or is it just me?
(I don't see any errors on my end and none of my devices show the nightly as updatable)
(And the nightly web page is sayings it is building 4.7.0 so that is way out of date)
If there is no update i would think the nightly should match the latest stable.

**Comment by pstorch** [comment]
The nightly is currently fixed to this PR: https://github.com/OpenTracksApp/OpenTracks/pull/1652

@dennisguse should we change back to main branch or should we merge in the changes from main to update it and have a new nightly build?

**Comment by dennisguse** [comment]
Rebase done :D

**Comment by pstorch** [comment]
A new nightly is born 🤗

**Comment by dennisguse** [comment]
@pstorch nighlty is still on the now deleted idle branch, right?

**Comment by pstorch** [comment]
No, I switched it back to main.

**Comment by dennisguse** [comment]
The issue seems to have been me. 
I somehow fucked up the merge of the idle PR (merged, but commits not added to main) and this seems to have prevented updates as (guess) the version id was lower than with the idle branch. 

Now I got the nightly from main :)

**Comment by dennisguse** [comment]
PS/ found it :D
This condition occurred as the sensor susbsystem was started twice and then shutdown wasn't done properly.
