### ISSUE TITLE
History list incorrect whilst tracking activity

### ISSUE THREAD

**Issue by IAmTheWebb** [OpenTracksApp/OpenTracks#1709]
**Describe the bug**
The previous activity list looks normal until I start tracking an activity, once tracking has started if I return to the list every item is a repeat of the currently in progress run. Clicking these opens the correct activity.
I don't think this happened on previous versions

**To Reproduce**
1. Start tracking.
2. Navigate back to activity list

If applicable:
![Screenshot_20230927-062501_OpenTracks](https://github.com/OpenTracksApp/OpenTracks/assets/17071553/5d5bd513-4bce-4f3b-ac69-f41a751ae1a9)

**Technical information**
 - Device: Oneplus Nord
 - OS: LineageOS 20
 - OpenTracks 4.8.4

**Comment by dennisguse** [comment]
Thanks for the report. 
I fixed this yesterday. 
Will be in v.4.9.0.

**Comment by dennisguse** [comment]
Here is the commit: https://github.com/OpenTracksApp/OpenTracks/commit/fda9ef9dd7b1d592a2a4a7ba0d74444c3dc5f0ed
