### ISSUE TITLE
Attempt to downgrade from v4.84 to v4.8.3 or lower failed - unknown error

### ISSUE THREAD

**Issue by BosqueRider** [OpenTracksApp/OpenTracks#1714]
Downgrade attempt from v4.8.4 to v4.8.3 failed using F-Droid.

Experienced this after the crashes documented in Issue 1711 and included this discovery in  comments there.   Have not tried to downgrade previously, so it is not known whether this is a new problem or an isolated incident.  Attached photos show error message as well as device and app info.

![Screenshot_2023-09-27-23-02-31](https://github.com/OpenTracksApp/OpenTracks/assets/138072764/758a44ca-2ca7-4e9c-82df-520274e9bdf2)
![Screenshot_2023-09-27-23-02-50](https://github.com/OpenTracksApp/OpenTracks/assets/138072764/6a4eb1f8-13cf-4184-86fa-10a20309d82a)
![Screenshot_2023-09-27-22-56-12_Info_device_version](https://github.com/OpenTracksApp/OpenTracks/assets/138072764/83dddd5d-a773-4f6e-b252-549166f016fc)

**Comment by dennisguse** [comment]
Can you check if downgrading for any app via Fdroid works?
For me, this doesn't work at all.

**Comment by BosqueRider** [comment]
Okay, I tried downgrading Organic Maps a few minutes ago and get the same "unknown error" message, indicating this is an F-Droid issue, or more likely, my phone. Thanks for the reply. If I figure it out, I'll let you know.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by BosqueRider** [comment]
Oddly enough, I upgraded Organic Maps without any issues, but trying again to downgrade resulted in the unknown error.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by dennisguse** [comment]
That's what I expected as Android shouldn't allow this.
More infos here: https://developer.android.com/studio/publish/versioning#versioningsettings

**Comment by pstorch** [comment]
I also tried to downgrade a different app, but failed. I had to uninstall first the current version. Be careful to uninstall OpenTracks: do a backup before 😉
