### ISSUE TITLE
No more distance voice announcements

### ISSUE THREAD

**Issue by sgofferj** [OpenTracksApp/OpenTracks#1739]
**Describe the bug**
Since 2 or 3 builds ago there is no more voice announcement for distance.

**Technical information**
### App information
* ID: de.dennisguse.opentracks.nightly
* Version: 5483 v4.9.2-17-g8f9ba046c

### Device information
* Brand: ulefone
* Device: Armor_3
* Model: Armor_3
* Id: O11019
* Product: Armor_3

### Firmware
* SDK: 27
* Release: 8.1.0
* Incremental: 1535356309

**Comment by dennisguse** [comment]
Can you check that is activated in the settings?
I accidentally removed this setting only, but re-added it.

**Comment by sgofferj** [comment]
Ah, yes, indeed, the setting is back. Apologies.
