### ISSUE TITLE
Ability to directly upload to Fitness Trackers (Specifically, custom FitTrackee)

### ISSUE THREAD

**Issue by Firesphere** [OpenTracksApp/OpenTracks#1761]
**Is your feature request related to a problem? Please describe.**

When I want to put my rides in to [FitTrackee](https://github.com/SamR1/FitTrackee), I need a GPX file from somewhere.

This process is quite cumbersome.

**Describe the solution you'd like**

Either:
- Ability to upload directly from the app to FitTrackee

**Comment by dennisguse** [comment]
Current options to export (to Android device file system):
* Automatic post-recording export
* Share track functionality
* Export via settings (all in one or all individually)

How AAT is doing by providing an Android data source would be interesting. 

Anyhow, the upload functionality must be done by another application like Nextcloud or Syncthing.

**Comment by Firesphere** [comment]
Ahhhh, the automatic post-recording would solve about half of my problem 👍
