### ISSUE TITLE
export route with LineString

### ISSUE THREAD

**Issue by chclxds** [OpenTracksApp/OpenTracks#1778]
Hello

It would be a feature, or an option if possible.
The application is excellent, but I would like it if when exporting in .kml format, the entire route traveled was treated as a line (LineString). If there is such an option, where do I activate it?

Q: Why would this be useful?
R: I work with a provider, and the line option would perfectly portray the route of the fiber, making mapping easier. Along with the points.

**Comment by dennisguse** [comment]
This is not implemented.
It shouldn't be be too difficult to build.
The relevant code is in KMLTrackExporter.

**Comment by chclxds** [comment]
I see.
In that case, there is a possibility that this feature is being developed.

**Comment by dennisguse** [comment]
I was checking the provided documentation (finally got some spare time again).
Bad news: the LineString object only is a list of coordinates (lat, lng, elevation) as a string.
There is no way to add any sensor data or timestamps.
So, this would mean exporting the LineString would have to be done in addition and thus significantly increasing the file size without actually adding new data.
That's just not a good idea.

@chclxds If you really need these LineString objects, I would recommend to create a script that converts the existing `<when><coord>` combination into a LineString object in post-processing step.
