### ISSUE TITLE
Crash on ending recording (with Barometer)

### ISSUE THREAD

**Issue by evanpeterjones** [OpenTracksApp/OpenTracks#1779]
**Describe the bug**
Exception occurs while saving new recording. File still saves, and I can reopen the app to find the track. 

**To Reproduce**
1. Start recording 
2. Stop recording 
3. See error

If applicable:
* add screenshots
![Screenshot_20231207-201642.png](https://github.com/OpenTracksApp/OpenTracks/assets/26383362/8e4c3b3d-7c86-4e34-a235-a0f55dbc5fdf)

**Technical information**
 - Device: Pixel 6
 - OS: Android 13
 - OpenTracks version: v4.9.6

**Comment by dennisguse** [comment]
Always or sometimes?

**Comment by Mats391** [comment]
I can confirm that I get the same crash every time I stop recording. Is there a way to access the logs of older crashes? Yesterday I also got some crashes while recording with bluetooth sensors connected.

**Comment by dennisguse** [comment]
Not like this. 
You can Android studio to access logcat.

**Comment by dennisguse** [comment]
I added a quick fix; can you check the nightly?

**Comment by dennisguse** [comment]
Added quick fix: https://github.com/OpenTracksApp/OpenTracks/commit/24212a226ec07765955b9cfaf925382daad2e413

**Comment by Mats391** [comment]
I tested the nightly and the barometer crash is gone for me. I created a new issue for the other bluetooth related crashes I mentioned earlier: [1780](https://github.com/OpenTracksApp/OpenTracks/issues/1780)
