### ISSUE TITLE
positive ascent does not make sens

### ISSUE THREAD

**Issue by Dambond** [OpenTracksApp/OpenTracks#1785]
The positive ascent result do not make sens.

**To Reproduce**
Ride?

screenshots:
![Screenshot_20231213-122237_OpenTracks](https://github.com/OpenTracksApp/OpenTracks/assets/103888780/2331f502-56c9-4d9b-a84f-d1851be8c43b)
![Screenshot_20231213-122314_OsmAnd~](https://github.com/OpenTracksApp/OpenTracks/assets/103888780/b5b3e06f-a479-4f11-8dd5-2c3a0f4c2dac)

**Technical information**
 - Device: Samsung S10e
 - OS: /e/ 
 - OpenTracks version: V4.9.6/V4.9.6

I can send GPX if necessary

**Comment by dennisguse** [comment]
Sounds like the barometer produces a lot of noise. 
Can you check that the sensor is working?

https://github.com/OpenTracksApp/OpenTracks/blob/main/README_TESTED_SENSORS.md#tested-barometric-sensor-smartphones

Please reopen this issue if the test doesn't show any problem.
