### ISSUE TITLE
Cadence data persistence in the stats screen

### ISSUE THREAD

**Issue by janzen42** [OpenTracksApp/OpenTracks#1790]
**Describe the bug**
The cadence data displayed in the stats screen alternates between showing a dash and showing the rpm number when the rpm is less than 60 rpm.

**To Reproduce**
1. In Settings, Bluetooth Sensors, add a Cadence sensor
2. In Settings, User Interface, Customize your recording Layout, Add the Cadence data field.
3. Start recording. Vary the rpm to observe how the number is displayed continuously when the rpm is higher than 60. When the rpm is lower the rpm number is displayed but is replaced with the dash prior to the next reading being displayed. The lower the rpm, the more often the dash is observed.

If applicable:

https://github.com/OpenTracksApp/OpenTracks/assets/79019480/3b1be498-2f2f-4e76-a37a-f284f351c928

**Technical information**
 - Device: Moto G7 Power
 - OS: [LineageOS 20-20231013-mircoG-ocean]
 - OpenTracks version: [v4.9.7-debug/v4.9.7-3-g64422e2f8]

**Comment by janzen42** [comment]
The cadence sensor used for this test was the Coospo BK467.

**Comment by dennisguse** [comment]
Can you add this sensor to the sensor readme?

Let me think about what might be wrong :)

**Comment by dennisguse** [comment]
I did some mental debugging while walking home.
It could be that the sensor is sending the data repeated and then the value is removed from OpenTracks.
This line would be responsible for this: https://github.com/OpenTracksApp/OpenTracks/blob/bb23bac7ec17345cacb82b86ef03c2443a13f98e/src/main/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorCyclingCadence.java#L28

@janzen42 Can you remove this line and check if this solves the issue?

**Comment by janzen42** [comment]
> I did some mental debugging while walking home. It could be that the sensor is sending the data repeated and then the value is removed from OpenTracks. This line would be responsible for this:
> 
> https://github.com/OpenTracksApp/OpenTracks/blob/bb23bac7ec17345cacb82b86ef03c2443a13f98e/src/main/java/de/dennisguse/opentracks/sensors/sensorData/AggregatorCyclingCadence.java#L28
> 
> @janzen42 Can you remove this line and check if this solves the issue?

I tried it out and it solves the issue however it creates a new issue. When one stops pedaling the last recorded cadence value sticks indefinitely so the value never drops to zero. Cadence is a tricky one isn't it?

**Comment by dennisguse** [comment]
:+1: 
Good that this works!

The sensor data has a TTL of 5s.
So, if OpenTracks doesn't  any further data, it should use getNoneValue().
... or there is another bug in AggregatorCyclingCadence...

**Comment by janzen42** [comment]
Yeah, it doesn't seem to be working. I can pedal for a bit, get it to record 60rpm and then I stop for a minute. The By time screen shows cadence remaining at 60rpm to the end of the recording and this also causes an inaccurate avg cadence value on the Stats screen.

**Comment by OMTDesign** [comment]
> When one stops pedaling the last recorded cadence value sticks indefinitely so the value never drops to zero.

I also have this issue on the latest version 4.12.4 version code 5788. I have CYCPLUS S/C3 sensors, and Opentracks will hold the last received cadence and Speed value instead of dropping to zero. @dennisguse 
![opentracks error](https://github.com/OpenTracksApp/OpenTracks/assets/39666543/f6000f4f-d37f-4db6-85c4-31272249d11d)
![opentracks_error2](https://github.com/OpenTracksApp/OpenTracks/assets/39666543/0785764b-2658-4ada-bb87-55fd1aa16972)

**Comment by OMTDesign** [comment]
![Uploading opentracks_error2.jpg…]()

**Comment by OMTDesign** [comment]
https://github.com/OpenTracksApp/OpenTracks/assets/39666543/39e41b57-7f61-4e61-81d8-33958e322505

**Comment by dennisguse** [comment]
@OMTDesign Can you open a new issue for this?
I am not sure that this is related to this issue.
