### ISSUE TITLE
Ski / snowboard - Distinguish between piste and lift

### ISSUE THREAD

**Issue by khao-soi** [OpenTracksApp/OpenTracks#1791]
When tracking for skiing or snowboarding distinguish between lift and piste for time and distance.  

An easy approach would be: 
- going up is lift
- going down is piste

I know this isn't always the right case, but might be a good start. 

Additional ideas are very welcome.

**Comment by dennisguse** [comment]
I would leave this to some kind of post-processing software.
Such things are hard to get right for all cases.
