### ISSUE TITLE
do not report units in the announcer

### ISSUE THREAD

**Issue by hercek** [OpenTracksApp/OpenTracks#1805]
**Is your feature request related to a problem? Please describe.**
My problem is that the announcer talk can be talking for too long and "hiding" too much of a show I'm listening in the background while training.

**Describe the solution you'd like**
Do not report the units. They are useless. Sometimes they are too long like e.g. "kilometres per second". They are always the same as set in the settings.

Continue to report the name of the quantity being reported, eg. "Average speed" (or only "Speed" for interval speed average) and the number. The name needs to stay so that we do not need to remember the meaning of reported numbers by their ordinal position. It also allows me to increase concentration to catch the following number.

**Describe alternatives you've considered**
Unit reporting can be an option in the settings but I think it is not worth it.

**Comment by dennisguse** [comment]
Sounds like a good idea!
