### ISSUE TITLE
more space for actual chart area by moving x-axis label lower left

### ISSUE THREAD

**Issue by hercek** [OpenTracksApp/OpenTracks#1820]
**Is your feature request related to a problem? Please describe.**
The actual chart area is rather small. It is harder to investigate charts when little screen space is available.

**Describe the solution you'd like**
Move X-axis label (typically "Time" or a distance unit) just below the x-axis and also so that the right side of the text is aligned with the right side of x-axis. Do not draw x-axis markers which would write over the moved label.

I have this solution already implemented. If this is accepted then I can create a PR.

**Describe alternatives you've considered**
An alternative would be to draw it above the x-axis instead of just below it. That way it might hide some chart curves. I think it is better if it hides some x-axis markers since one can easily linearly extrapolate what a hidden marker would be. It can be extrapolated from the markers which are still visible. On the other side a hidden part of a chart curve cannot be extrapolated. It is unpredictable and invisible data.

**Additional context**
**Screenshot of the current behaviour:**
![OpenTracksOld](https://github.com/OpenTracksApp/OpenTracks/assets/5325126/b8e765ec-5e73-4a5b-b7e2-3a1ad6123efe)

**Screenshot of the required behaviour:**
![OpenTracksNew](https://github.com/OpenTracksApp/OpenTracks/assets/5325126/7b703ae4-41d2-445a-8554-767784381a73)

**Comment by dennisguse** [comment]
Sounds good. 

PS you can also just open PRs ;)
