### ISSUE TITLE
make more space for charts by making Y-axis more compact

### ISSUE THREAD

**Issue by hercek** [OpenTracksApp/OpenTracks#1828]
**Is your feature request related to a problem? Please describe.**
The actual chart area is rather small. It is easier to investigate charts when more screen space is available.

**Describe the solution you'd like**
Make Y-axis labels more compact. Currently the labels for one chart tick are in one line. The line can be quite long when more curves are present in the chart. That is mostly fine in landscape mode but in portrait mode it takes too much screen space. Divide the chart labels into two lines (1st line just above the 2nd one) if it still allows at least one line height empty space between the labels corresponding to different ticks. I.e. if the separation between set of labels corresponding to different ticks is big enough. This makes the width of the Y-axis about half what it was before leaving more space for the chart itself.

**Describe alternatives you've considered**
Here are options I think are worse or not worth the additional effort:
1) The labels are not aligned into a nice grid. This is more work but especially this would often take a bit more space. I do not think it is worth it. Labels can be distinguished easily since each series has a different colour. No important reason to organize to a grid except maybe a bit nicer look.
1) Separation into more than two lines. It is more work and we would need to allocate more space at the top and the bottom of the chart so that the Y-axis labels do not over lap with chart title at the top or the X-axis labels at the bottom. This actually may be worth doing but I'm lazy.

**Additional context**
I have a provisional patch implementing this. I'll create a PR if it is accepted as it is. I may modify the patch to based on the requirements to make it merge-able upstream but no promises.

Here are some examples how does it look with my patch and without it (at the end):

**Bigger screen portrait two curves with my patch**
![PortraitTwoCurves](https://github.com/OpenTracksApp/OpenTracks/assets/5325126/34c50028-7016-453b-bab5-69b89851744d)

**Bigger screen portrait three curves with my patch**
![PortraitThreeCurves](https://github.com/OpenTracksApp/OpenTracks/assets/5325126/412ae8bc-03be-4e07-bc32-5590c05d8033)

**Bigger screen portrait four curves with my patch**
![PortraitFourCurves](https://github.com/OpenTracksApp/OpenTracks/assets/5325126/7d519c97-2151-40c5-9877-4f9cb5cea5a1)

**Smaller screen portrait four curves with my patch**
![PortraitSmall](https://github.com/OpenTracksApp/OpenTracks/assets/5325126/2cdb3bea-f08c-4637-919b-5fca70379a02)

**Smaller screen landscape four curves with my patch**
![LandscapeSmall](https://github.com/OpenTracksApp/OpenTracks/assets/5325126/ec710f26-5e26-424b-a3b5-3c06a9dc4a4d)

**Smaller screen landscape the current state (without my patch)**
![OldPortraitSmall](https://github.com/OpenTracksApp/OpenTracks/assets/5325126/ab9c5a08-5ff4-4762-b871-767cd5315782)

**Comment by dennisguse** [comment]
Looks good!
