### ISSUE TITLE
BLE sensor suitable for Atmospheric Pressure Measurement (0x2A6D) using the Environmental Sensing Service (ESS: 0x181A)

### ISSUE THREAD

**Issue by vlszabolcs** [OpenTracksApp/OpenTracks#1832]
#1424  continuation

Summary: BLE atmospheric pressure measurement has been introduced in v4.10.1. It works excellently!! :D
Currently, there is no commercially available fully-fledged BLE sensor device supporting Environmental Sensing Service ([0x181A](https://github.com/oesmith/gatt-xml/blob/master/org.bluetooth.service.environmental_sensing.xml)) and the Pressure characteristic ([0x2A6D](https://github.com/oesmith/gatt-xml/blob/master/org.bluetooth.characteristic.pressure.xml)) on the BLE sensor side.
A potential solution could be the development or modification of a BLE sensor, for which the following devices have been considered so far:

Dev boards: Hardware and software development are required:

- [Arduino Nano 33 BLE Sense](https://store.arduino.cc/products/nano-33-ble-sense-rev2)
- [Nicla Sense ME](https://store.arduino.cc/products/nicla-sense-me)
- [nRF Sensor Tag](https://www.aliexpress.com/item/32859423925.html?spm=a2g0o.detail.0.0.7168WDSNWDSN1O&gps-id=pcDetailTopMoreOtherSeller&scm=1007.40050.362094.0&scm_id=1007.40050.362094.0&scm-url=1007.40050.362094.0&pvid=65c4103d-486d-4559-8ead-f12c1cbb900e&_t=gps-id%3ApcDetailTopMoreOtherSeller%2Cscm-url%3A1007.40050.362094.0%2Cpvid%3A65c4103d-486d-4559-8ead-f12c1cbb900e%2Ctpp_buckets%3A668%232846%238115%232000&pdp_npi=4%40dis%21HUF%217282.40%215970.93%21%21%2120.49%2116.80%21%402103200617045371396292353e90eb%2165326366709%21rec%21HU%21874335205%21)

Ready-made BLE sensors: Mostly requiring software development/modification:

- [RuuviTag](https://ruuvi.com/ruuvitag/)
- [SensorPush HTP.XW](https://www.sensorpush.com/products/p/htp-xw)
- [Bangle js2](https://www.espruino.com/Bangle.js2)

For the first attempt, I see potential in modifying the RuuviTag since it is open source. The challenge is that currently, it only supports broadcasting with Nordic Uart Service. Instead or alongside, Environmental Sensing Service (ESS) could be added.

Any other solutions, ideas? :D

**Comment by dennisguse** [comment]
* implement an Android application that serves ESS - see https://developer.android.com/reference/android/bluetooth/BluetoothGattServer

I have a Nexus 5 and a Samsung S4 that have a barometer and Bluetooth aka fulfill all requirements as an external sensor :)

**Comment by dennisguse** [comment]
Some days ago, I released a working prototype that allows to use the barometer from another phone via BLE: https://github.com/OpenTracksApp/NoTrustIssues

**Comment by dennisguse** [comment]
@vlszabolcs if you have any other ideas, can you add those to the README_TESTED_SENSORS?

**Comment by dennisguse** [comment]
@vlszabolcs I got a sensor that works: https://market.flybeeper.com/device/ps1
