### ISSUE TITLE
incorrect naming "recording time interval" in the settings

### ISSUE THREAD

**Issue by hercek** [OpenTracksApp/OpenTracks#1840]
**Describe the bug**
The setting "GPS" - "Recording time interval" is not correctly named. It should be named "Sampling time interval" or maybe "Reading time interval". Recording into track points happens every "recording distance interval" or about once in 7 seconds when stationary. Well, no clue really. This is how it looks from my experience as a user. I did not check the code.

**Technical information**
 - OpenTracks version: 4.11.0

**Comment by dennisguse** [comment]
See GPSManager; it is the update interval passed to Android's LocationManager for the desired interval of updates.

I like 'Sampling time interval' as it is actually not used for recording (in difference to 'Recording distance interval'.
Can you fix this?

**Comment by hercek** [comment]
Do you want to have it changed in the translation strings only or also in the source code (i.e. renaming of the relevant java identifiers in the sense \*MinRecordingInterval\* -> \*MinSamplingInterval\*)?

I tried to rename it in the source code as well but not sure it is what you want. The diffstat of this full rename is not too bad:
```
 src/androidTest/java/de/dennisguse/opentracks/services/handlers/GpsStatusTest.java |  4 ++--
 src/main/java/de/dennisguse/opentracks/services/handlers/GPSManager.java           |  6 +++---
 src/main/java/de/dennisguse/opentracks/services/handlers/GpsStatusManager.java     |  4 ++--
 src/main/java/de/dennisguse/opentracks/settings/GpsSettingsFragment.java           | 10 +++++-----
 src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java              | 16 ++++++++--------
 src/main/res/values/settings.xml                                                   |  8 ++++----
 src/main/res/values/strings.xml                                                    |  4 +++-
 src/main/res/xml/settings_gps.xml                                                  |  8 ++++----
 8 files changed, 31 insertions(+), 29 deletions(-)
```
The partial rename (only in translations) will change only the ``strings.xml`` and one-line-change in ``GpsSettingsFragment.java``.

**Comment by dennisguse** [comment]
Changing the code as well sounds good
