### ISSUE TITLE
Opentracks not displaying elevation Loss/Gain

### ISSUE THREAD

**Issue by miharashi** [OpenTracksApp/OpenTracks#1848]
Opentracks v4.11.0 no longer displays Loss/Gain on statistics screen. 

To Reproduce
1 Start recording
2 Observe that Loss/Gain remain blank (see screenshot)

Note: lat/lon/elevation are being logged to GPX files

![Screenshot_20240131_173252_OpenTracks](https://github.com/OpenTracksApp/OpenTracks/assets/23371311/0808bfc5-3e91-4864-9535-58e043a4e3c0)

Device: Galaxy S22 (stock)

**Comment by dennisguse** [comment]
Can you check the settings: Bluetooth Sensors -> Barometer and what is set there?
It should be internal, but it likely is not.

**Comment by miharashi** [comment]
That was a quick and accurate diagnosis.
I set "Bluetooth Sensors" to "Internal" and Loss/Gain is being displayed.
Thank you. Donation coming.

**Comment by LeonPyramid** [comment]
It seems that I have the same issue, but it seems I cannot select any barometer in the settings.
![Screenshot_20240826-160007_OpenTracks](https://github.com/user-attachments/assets/ced6e257-aa7b-46c6-aac4-be3f9e3d82b0)
I'm on a Redmi Note 9S with Lineageos for microg.

**Comment by dennisguse** [comment]
@LeonPyramid the Redmo note has no barometer. 
So, the behavior is correct.

**Comment by miharashi** [comment]
I think you sent this to the wrong address. I don't have a Redmo.

(I had a similar issue a while ago and you helped then. Thanks!)
________________________________
