### ISSUE TITLE
App crashes after stopping non-GPS workout via Gadgetbridge-linked fitness tracker

### ISSUE THREAD

**Issue by beansmachine** [OpenTracksApp/OpenTracks#1850]
**Describe the bug**

After stopping a workout recording via fitness tracker, the app immediately crashes. This issue *doesn't* occur when recording a workout that uses GPS, such as walking or cycling. All requested app permissions are enabled, battery use is unrestricted. 

**To Reproduce**
1. Stop any non-GPS workout on tracker
2. See error

**Technical information**
- Devices: Xiaomi Mi A2 lite, Xiaomi Mi Band 4
- OS: LineageOS 21 (unofficial)
- OpenTracks version: v4.11.0

Crash log:
[crashlog.txt](https://github.com/OpenTracksApp/OpenTracks/files/14186028/crashlog.txt)

**Comment by dennisguse** [comment]
Can you upload the logs to Github?

**Comment by dennisguse** [comment]
Can you give detailed instructed how to reproduce this  (incl. in which if the screen is on/off)?

**Comment by beansmachine** [comment]
The crash consistently happens whenever data are sent over from the fitness tracker. Tested this with the app being open, running in background, with the screen on and after unlocking - as soon as the tracker's recording is stopped (including cases when the band says the workout is too short to be recorded), OpenTracks displays the crash log and closes.

**Comment by dennisguse** [comment]
Best guess: introduced in 9a0f9271.
When stopping a the service should not be started as it is already running.

**Comment by dennisguse** [comment]
Fix reverted due to #1853.

And this is actually a duplicate of #1824.
Due to https://github.com/OpenTracksApp/OpenTracks/issues/1824#issuecomment-1941956834
