### ISSUE TITLE
BUG v4.11.1: TrackRecordingService killed in background

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1853]
The fix for #1850, results in the foregroundservice not being started (or rather killed whenever the screen is turned off).

How to reproduce (https://github.com/OpenTracksApp/OpenTracks/commit/8400d45e987da9b77bddc3a446df3cce233fb444):
1. Start a recording (Service starts showing notification)
2. Turn screen off
3. Turn screen on: service gone; no notification

**Comment by mamoit** [comment]
I found out about this issue today after 25km of riding.
F-droid doesn't have the fixed version yet.
The extra slow builds on their side are really annoying.
Has anyone looked into the possibility of setting up a repository?

**Comment by pstorch** [comment]
@mamoit you can you our nightly build repository: https://fdroid.storchp.de/fdroid/repo/

**Comment by mamoit** [comment]
@pstorch that's exactly what I was looking for.
Thanks!
