### ISSUE TITLE
Update README, F-Droid and Play Store screenshots

### ISSUE THREAD

**Issue by ch3thanhs** [OpenTracksApp/OpenTracks#1854]
I would like to update the screenshots to reflect the new design of the app, I have created a sample (attached below) and will create the rest if you can provide me with the appropriate screenshots, Let me know which one you prefer.

## Solid Color -

<img src="https://github.com/OpenTracksApp/OpenTracks/assets/76928501/4a2a7b56-da37-4f59-8288-aef53e1c4f37" width=200>

## With Gradient - 

<img src="https://github.com/OpenTracksApp/OpenTracks/assets/76928501/f18f5f6a-1567-417a-ad04-8218e2f0f1b9" width=200>

**Comment by dennisguse** [comment]
That sounds good!
I personally prefer the 2nd version.
Just create a PR and we can merge this :D

There are some templates for these images in `screenshots-svg` and there is the script `UPDATE_SCREENSHOTS.sh`.
This may be a good starting point for some automation.

**Comment by ch3thanhs** [comment]
Done :)

**Comment by dennisguse** [comment]
@ch3thanhs you are right the images were still the old ones.
Fastlane is only working for F-Droid; the PlayStore happens (once a year) manually by me and it has the tendency to not work aka provide weird error messages.

I just did the upload of the images + feature graphic manually and it now awaits PlayStore review.
Thanks for reminding me :+1:
