### ISSUE TITLE
MarkerList: The "back" arrow doesn't work 

### ISSUE THREAD

**Issue by serrq** [OpenTracksApp/OpenTracks#1861]
OnePlus CPH2399
Android 13
OT 4.11.1 (fdroid)

![1000106088](https://github.com/OpenTracksApp/OpenTracks/assets/113377431/40ac3255-be69-4f77-a254-6bc33294191a)

**Comment by dennisguse** [comment]
You are right; this button is working in some places and in some it isn't.
This issue #1708 describes how it should be done.
Not the most exiting task though...
