### ISSUE TITLE
Recording stops when minimizing OpenTracks or when pressing the power button to shut down the screen

### ISSUE THREAD

**Issue by pitkajuh** [OpenTracksApp/OpenTracks#1863]
**Describe the bug**
Recording stops when minimizing OpenTracks or when pressing the power button to shut down the screen.

**To Reproduce**
1. Start recording
2. Minimize OpenTracks (go to home screen) or press the power button to shut down the screen
3. Recording stops

**Technical information**
 - Device: Google Pixel 6a
 - OS: GrapheneOS, UQ1A.240205.002.2024020500
 - OpenTracks version: 4.11.1, 5679

**Comment by dennisguse** [comment]
Duplicate of #1853.
Please upgrade to v4.11.2 or downgrade to v4.11.0
