### ISSUE TITLE
OpenTracks requires to have doc.kml file in kmz

### ISSUE THREAD

**Issue by cyber-toad** [OpenTracksApp/OpenTracks#1864]
**Describe the bug**
OpenTracks requires to have doc.kml file in kmz

**To Reproduce**
1. Share a single track from OrganicMaps app and try to import in OpenTracks
2. There is an error that doc.kml is not available

**Technical information**
 - OS: Android
 - OpenTracks version: v4.11.1

Based on KMZ spec doc.kml is not a mandatory name for file in kmz:
https://developers.google.com/kml/documentation/kmzarchives

> For clarity, this page refers to the main KML file within a KMZ archive as doc.kml. This main KML file can have any name, as long as it ends in .kml, and as long as there is only one .kml file.

> Put the default KML file (doc.kml, or whatever name you want to give it) 

Discussion in Organic Maps bug tracker: https://github.com/organicmaps/organicmaps/issues/7398

**Comment by dennisguse** [comment]
Works for me; code is in `KMZTrackImporter` + some translations.
@cyber-toad could you create a PR?
