### ISSUE TITLE
PNG not shared

### ISSUE THREAD

**Issue by ramos** [OpenTracksApp/OpenTracks#1866]
**Describe the bug**
When a track is shared, only the .kmz file is shared, and not the PNG picture. This was working a wike back (not sure what happened)

**To Reproduce**
In share settings, choose .kmz with picture. When a track is seen (with the map and osm dashboard installed), share.

Only the kmz file is shared, no picture.

I use lineageos with las version of opentracks (4.11.1) and osm dashboard (4.0.0)

**Comment by dennisguse** [comment]
The kmz-file is just a zip - can you check that the pictures are not included?

Or which pictures do you mean?
