### ISSUE TITLE
 Download .apk from github directly with Obtainium #41 

### ISSUE THREAD

**Issue by HomemadeAdvanced** [OpenTracksApp/OpenTracks#1878]
I would like to pull the latest .apk directly from github using Obtainium. In order to do this, the latest released .apk would have to be listed under Releases. Would this be possible or is there another way to get the latest .apk directly from github?

**Comment by pstorch** [comment]
You can download the latest nightly build apk from our fdroid repo: https://fdroid.storchp.de/fdroid/repo/

3rd party fdroid repos are supported by optanium, when I've read the readme correctly.

**Comment by HomemadeAdvanced** [comment]
Yes I know about that F-Droid links work, but some Apps need a few days to get pushed to F-Droid so it would be nice to get it directly from source.
