### ISSUE TITLE
auto start recording when app starts option

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1884]
**Is your feature request related to a 
There should be an option to automatically start recording when the app starts. 
Maybe with a user settable delay so the user could abort the recording

**Comment by dennisguse** [comment]
I wouldn't do this.
Implementing #1563 might an option or you may use the existing Pubic API.

**Comment by nutpantz** [comment]
How would a regular user use the api to start a track? Without have to buy yet another app?
