### ISSUE TITLE
Battery drain Sensors running background

### ISSUE THREAD

**Issue by pamatika** [OpenTracksApp/OpenTracks#1900]
**Describe the bug**
After last update tracker is keeping location / gps active all the time causing battery drain 16% 9 hours.

**To Reproduce**
1. After updating to latest version battery drain started. Also location notification for tracker popping up from time to time.

**Technical information**
 - Device: Samsung A34
 - OS: latest
 - OpenTracks version: v4.12.2

**Comment by dennisguse** [comment]
How can I reproduce this?

**Comment by pamatika** [comment]
So this happened after updating to the latest version. App kept on trying to get a fix on location. Killing the app didn`t help. But restart of the phone helped. After restart I have not seen same behaviour. So it has to be some clitch in installation...or..

**Comment by dennisguse** [comment]
Thanks for the feedback. 
Let's close this issue for now and if it reappears, please open it again.
