### ISSUE TITLE
Samsung galaxy s10 not tracking in Background

### ISSUE THREAD

**Issue by FirstWithThisName** [OpenTracksApp/OpenTracks#1902]
**Please describe the problem and how to reproduce it:**

...

**Checklist**

- [x] Consulted [https://dontkillmyapp.com/]
- [x ] Power management: battery optimization is disabled for OpenTracks

**Technical information**

- Device: [Samsung Galaxy s10]
- OS: 12
- OpenTracks version: 4.12.0

OT only records if the screen is on.
I only can allow using the location while app usage.
Other app have the option to always allow using the location.

**Comment by dm1cael** [comment]
Could #1653 be related?

**Comment by dennisguse** [comment]
Might be #1653. 

If the screen is off, some Android devices might enforce permission to access the location in the background. 
And OpenTracks is not (yet) requesting this permission.

Can you check if it works, if the screen is on?

**Comment by dennisguse** [comment]
How do you start OpenTracks?

**Comment by FirstWithThisName** [comment]
Oh, yes. Sorry for the delayed answer.
With the screen unlocked it works.
#1653 seams to be the problem

28.04.2024 22:27:22 Dennis Guse ***@***.***>:

**Comment by FirstWithThisName** [comment]
> How do you start OpenTracks?

With the red button at the lower right corner

**Comment by dennisguse** [comment]
That's a different problem than. 

PERMISSION_LOCATION_BACKGROUND is not required if started via the UI. 
In this case: it is usually a misconfiguration with power saving - e.g. something like Android OS optimizing for low power consumption.

**Comment by FirstWithThisName** [comment]
I set it to not optiomize in the app settings but, my phone maybe been in energie saving mode. I will test tomorrow if switching of the energie saving mode fixed the issue.

**Comment by FirstWithThisName** [comment]
Oh, sorry it seams like the e-mail resonse didn't work.

Disableing the engerie save mode fixed it.

Thanks for your help!
