### ISSUE TITLE
Moving time only stops when isn't recording GPS data

### ISSUE THREAD

**Issue by ScriptForAll** [OpenTracksApp/OpenTracks#1911]
**Describe the bug**
I've noticed this bug for a few weeks now.
Despite having set 5 seconds of idle time the app doesn't stop recording moving time in pauses longer than 5 seconds. However, if the app doesn't receive GPS data, moving time stops counting.

My use-case for this app is to track my transportation data so it's quite important to get moving and total averages speed accurate.

**To Reproduce**
1. Track trip (e.g. suburban train)
2. Train stops longer than 5 seconds
3. Moving speed is 0
4. Timer for moving time doesn't stop 

**Technical information**
 - Device: Google Pixel 7
 - OS: GrapheneOS
 - OpenTracks version: 4.12.3

**Comment by dennisguse** [comment]
Sadly, this is broken since I added the idle functionality.
Last weekend I had some time to check this in detail and the problem just got messier.

I have a test case showing how it should look like, but implementation is kind of complicated.
This will take some more days.

More infos here: #1756
