### ISSUE TITLE
App shouldn't prohibit recording tracks without Bluetooth (Nearby devices) permission

### ISSUE THREAD

**Issue by soshial** [OpenTracksApp/OpenTracks#1930]
**Describe the bug**
If I reject Bluetooth permissions (shown as "Nearby devices"), the app prohibits recording tracks at all. That's not very liberal: we should give user a choice.

**To Reproduce**
1. Make clean install
2. Accept location permission, reject "Nearby devices" permission
3. Try to record a new track

**Technical information**
 - Device: Samsung Galaxy S22
 - OS: Android 14
 - OpenTracks version: v4.12.4

**Comment by dennisguse** [comment]
Similar: #1259
