### ISSUE TITLE
Back arrow in all setting menus does not work

### ISSUE THREAD

**Issue by ironspock** [OpenTracksApp/OpenTracks#1932]
The back arrow (yellow marked in screen dump) in all settings menus does not work.
You have to use the cogwheel icon (green marked in scree dump) to get back to the previous/parent menu/screen.

**Technical information**
 - Device: Gigaset GX6
 - OS: Android 13
 - OpenTracks version: v4.12.4 version code 5788 (F-Droid)

![Screenshot_20240621-152534](https://github.com/OpenTracksApp/OpenTracks/assets/68661025/c1701cfa-dce6-4a4c-bb7d-225b033350a6)

**Comment by Random90** [comment]
Yea, I have the same issue on GrapeheOS on Pixel Fold. Navigating with gestures works though.
