### ISSUE TITLE
list not showing track being recorded

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1934]
**Describe the bug**
A track of being recorded but the list of tracks does not show the top one recoding

**To Reproduce**
Start a track. 
Go do something for 3 mins
Look at list of tracks.
None are listed as recording

If applicable:
* add screenshots
* add logcat output

**Technical information**
 Pixel 8 pro android 14
 - Google android 14 March 2024
![Screenshot_20240622-142046](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/4c7a2568-fa2a-4bd8-9815-8fb000621069)

The top track is actively recording

 - 4.2.14
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

**Comment by nutpantz** [comment]
Here are some Screen shots. One is after I stopped recording it still showed recording (you can see the button on the bottom red showing no recording). So there are more issues with displaying "recording"
![Screenshot_20240622-150413](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/e1dd8d98-f4bd-4434-bcb2-e3c930ee3297)
![Screenshot_20240622-150317](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/79f4e554-b82d-4f0c-903e-46ca7dfbed0d)
![Screenshot_20240622-150305](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/6b82010f-671e-46ac-b3fb-cddf008dcf2d)

**Comment by pstorch** [comment]
I cannot reproduce this one as described, but in a different way.
- start a new recording
- stop the recording from the track details page
- the confirmation dialog is shown
- instead of finishing the track, hit the play button to resume
- recording is started again and the track list is show without any visible recording
