### ISSUE TITLE
displaying elevation gain broken?

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1935]
**Describe the bug**
Showing elevation gain is broken.

**To Reproduce**
Start track
Go up and down something 100 meters
Look for elevation gain

If applicable:
* add screenshots
* add logcat output

**Technical informatig
Pixel 8 pro Google android 14 March update
 - v4.2.14 stable
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]
![Screenshot_20240622-111830](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/4612b75b-35ca-4d5a-bf40-73499a9abd70)
![Screenshot_20240622-111837](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/1a55cff5-710a-4f52-a699-67656a7921e3)

You can see elevation has been recorded

**Comment by nutpantz** [comment]
Also elevation gain is not in stats like it used to be after a track is stopped

![Screenshot_20240622-151435](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/d059f26f-2998-40a8-937b-425badd9b98e)

**Comment by nutpantz** [comment]
Just because I should be complete in my testing and reporting .
Also not showing elevation in intervals page
![Screenshot_20240622-151857](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/c597ae52-31ed-4f7e-a880-05cf5f66da84)
![Screenshot_20240622-151904](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/e759cffb-e973-4a0a-8

**Comment by nutpantz** [comment]
Lots of elevation gain and loss
![Screenshot_20240622-151904](https://github.com/OpenTracksApp/OpenTracks/assets/12160507/76b46ecc-1b15-4c88-b729-2e6225a0bee9)

**Comment by paulle** [comment]
I can confirm this. Here te same.
Xperia 5 V, Android 14

**Comment by dennisguse** [comment]
Is the barometer configured in the settings?

**Comment by paulle** [comment]
No, will try it next time.
Thank you

Gesendet von Proton Mail für Android

-------- Ursprüngliche Nachricht --------
Am 11.07.24 06:27 um Dennis Guse schrieb :

**Comment by paulle** [comment]
It works
Gesendet von Proton Mail für Android

-------- Ursprüngliche Nachricht --------
Am 11.07.24 15:10 um Krischan schrieb :

**Comment by nutpantz** [comment]
What is wrong with the gps only altitude?

**Comment by dennisguse** [comment]
@nutpantz GPS altitude: absolute measure (with quite some noise). 
Barometer altitude: relative measure (with drift due to weather changes).

Nothing wrong: just different data sources that can be used for different things.
