### ISSUE TITLE
Activity list titles are being truncated

### ISSUE THREAD

**Issue by furo321** [OpenTracksApp/OpenTracks#1958]
**Describe the bug**
Activity list titles are being truncated, despite there being plenty of space. See screenshots. Happens more commonly with longer titles, sometimes multiple activities or just one. It usually changes which ones are being truncated when going in and out of an activity.

![image](https://github.com/user-attachments/assets/c54c76ae-3d68-4755-ada4-1e79ab2e6de6)

![image](https://github.com/user-attachments/assets/d2ca4221-1d8c-4f55-aea1-7922e7aff442)

**Technical information**
 - Device: OnePlus Nord CE
 - OS: LineageOS 18.1 (Android 11)
 - OpenTracks version: v4.12.4 (F-Droid)

**Comment by Pulau-Komodo** [comment]
The number of characters before truncation seems random for each item, and it seems to re-randomize every time I go into an activity and back to the list.

**Comment by dennisguse** [comment]
I guess it depends on the list. 
The UI framework does not recompute the required size of the names and then it just truncates them.
