### ISSUE TITLE
KML/KMZ export has wrong heartrate data field name

### ISSUE THREAD

**Issue by MorganJamesSmith** [OpenTracksApp/OpenTracks#1961]
In the KML export, the data field name for heart rate data is "heart_rate" when it should be "heartrate".  This causes interoperability issues.  When opening a KML file in GPXsee I am unable to see the heartrate graphs as it expects the data field to be called "heartrate". 

Manually editing the KML file and modifying the SimpleArrayField and SimpleArrayData name allows GPXsee to view the heart rate data.

Reading the file "src/main/java/de/dennisguse/opentracks/io/file/exporter/KMLTrackExporter.java" I found a link to the KML specification "https://docs.opengeospatial.org/is/12-007r2/12-007r2.html".  There is clearly states that the field should be "heartrate".

In the same file the variable "EXTENDED_DATA_TYPE_HEART_RATE" has the value "heart_rate".  I am not familiar with the source code but possibly the fix is simply changing that value?

Thanks,

Morgan

**Comment by dennisguse** [comment]
Yes, you are right.

And the change is also the correct one. 
For the importer, we need support for both names aka heart_rate and heartrate. 

A test for this would be great.
