### ISSUE TITLE
Icons in search bar are not centered

### ISSUE THREAD

**Issue by m-gail** [OpenTracksApp/OpenTracks#1962]
**Describe the bug**
The icons inside the search bar on the track list are not centered and there is additional padding on the bottom.

**To Reproduce**
1. Open the track list
2. The icons in the search bar are not centered and there is a noticable bottom padding

Screenshot:

I have tried out a quick fix for this, if the bottom padding is not intentional I could open a pull request with my fix. The left side is the current look, right side is without the bottom padding.

<div>
<img src="https://github.com/user-attachments/assets/39780372-dbb4-4255-ba65-5bf52a9487cd" width="40%">
<img src="https://github.com/user-attachments/assets/6b26e558-39e6-4ad0-b83a-8c6297325445" width="40%">
</div>

**Technical information**
 - Device: Pixel 7
 - OS: GrapheneOS, Android 14
 - OpenTracks version: v4.12.5

**Comment by dennisguse** [comment]
If you have a fix, please open a PR.
