### ISSUE TITLE
Sensor data not recorded if GPS enabled but speed is zero

### ISSUE THREAD

**Issue by as123rgb** [OpenTracksApp/OpenTracks#1966]
Related to #1088. When I stop moving for a few minutes (with GPS on) I see suspicious linear interpolation for every metric:

<img src="https://github.com/user-attachments/assets/b72544b8-9794-4868-8a70-49fb21c19464" height="450">
<img src="https://github.com/user-attachments/assets/f8e882c6-c68c-4bed-9afd-9ffca5c27e6c" height="450">

_Red is HR, blue is speed, green is elevation._

If the phone is not moving then dropping redundant GPS coords makes sense, but HR data is still useful and it should be recorded. The speed should probably be recorded as being 0 at the start and end of each interval to avoid weird interpolation, then it would correctly show as 0 over the whole interval and if other applications want to interpolate the data it'll be unambiguously 0.

Here is a snippet of exported kml. No data exists for the intervals where I've stopped moving. 
```xml
<when>2024-07-18T15:55:31.136+00:00</when>
<coord>xxx.xxxx23 xx.xxxx27 9.313198332140</coord>

<when>2024-07-18T15:55:32.14+00:00</when>
<coord>xxx.xxxx18 xx.xxxx38 8.9174764139130</coord>

<when>2024-07-18T15:55:33.139+00:00</when>
<coord>xxx.xxxx09 xx.xxxx45 8.2689896704566</coord>

<!-- gap of 29.952 seconds -->

<when>2024-07-18T15:56:03.091+00:00</when>
<coord>xxx.xxxx05 xx.xxxx48 9.444981316744</coord>

<when>2024-07-18T15:56:03.153+00:00</when>
<coord>xxx.xxxx05 xx.xxxx48 9.444981316744</coord>

<!-- gap of 110.974 seconds -->

<when>2024-07-18T15:57:54.127+00:00</when>
<coord>xxx.xxxx19 xx.xxxx42 8.5567704015492</coord>

<when>2024-07-18T15:57:55.122+00:00</when>
<coord>xxx.xxxx21 xx.xxxx51 8.6911931082478</coord>
```

My settings:
| Setting | Value |
|-|-|
| Recording > Recording distance interval | 1 m |
| Recording > Idle threshold | 30 s |
| Recording > Max distance | 200 m |
| Sensors > GPS > Sampling time interval | 0 s |
| Sensors > GPS > GPS accuracy | 20 m |

**Checklist**

- [x] Consulted [https://dontkillmyapp.com/]
- [x] Power management: battery optimization is disabled for OpenTracks

**Technical information**

- Device: Google Pixel 8
- OS: GrapheneOS 2024-07-28
- OpenTracks version: v4.12.5

**Comment by dennisguse** [comment]
Relevant code is in `TrackRecordingManager.onNewTrackPoint()`.
IIRC this functionality was implemented a while ago - however, it might be broken...

**Comment by dennisguse** [comment]
I did some digging: and we have even test coverage for this case - and I presume this should be working.
See `TrackRecordingServiceRecordingTest.testRecording_blesensor_only_no_distance`

Do you have any more insights?

**Comment by dennisguse** [comment]
Functionality should be working.
We have a test case for this.
There some missing functionality though aka we used different clocks at different places.
Now it is the same.
