### ISSUE TITLE
Elevation records strange numbers

### ISSUE THREAD

**Issue by mega-stoffel** [OpenTracksApp/OpenTracks#1967]
**Describe the bug**
In #1898 there was a bug in the recording of the track length. It looks like a similar behavior is not happening with the elevation.

**To Reproduce**
I haven't fully tried to reproduce the issue, but it happens pretty often.
Usually I start a track and then just forget about it. I.e. I ride into the underground parking or walk into buildings where I don't have GPS signal. Then I remember again and stop the recording. Afterwards I continue this track again, and again until the day is over.

If applicable:
Screenshot of today's short trip in Stuttgart. Yes, it's hilly but not as hilly as 14.500 meters of elevation during 6,6km.
![Screenshot_20240807-160031](https://github.com/user-attachments/assets/bde45c69-72d5-4c0b-a9fa-f90d3041a9f2)

**Technical information**
 - Device: Pixel 6
 - OS: latest GrapheneOS
 - OpenTracks version: 4.12.5
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

**Comment by dennisguse** [comment]
Can you check if your sensor is working correctly?
Barometers are quite error prone.
Please follow the procedure described here: https://github.com/OpenTracksApp/OpenTracks/blob/main/README_TESTED_SENSORS.md
