### ISSUE TITLE
Corsican localization is now ready on Weblate

### ISSUE THREAD

**Issue by Patriccollu** [OpenTracksApp/OpenTracks#1974]
Hello,

I just completed the **Corsican localization** of `opentracks-opentracks-src-main-res-values-strings-xml-main` file on [Weblate](https://hosted.weblate.org/projects/opentracks/-/co/).

Please note that two other files - _App store metadata_ and _glossary_ do not contain any string to translate.

Best regards,
Patriccollu.

**Comment by dennisguse** [comment]
Merged localization, but we still need a language switcher as Android's built-in doesn't pick up Corsican.
See: https://github.com/OpenTracksApp/OpenTracks/issues/1970#issuecomment-2295355736

Actually, this might even be considered a bug in Android.

**Comment by Patriccollu** [comment]
Hope that you will be able to circumvent this problem by setting `co` locale programmatically!

**Comment by Patriccollu** [comment]
Hi @dennisguse,

Do yoy have some news on this enhancement?

Best regards,
Patriccollu.

**Comment by dennisguse** [comment]
Sadly no. 
Times are quite busy. 
I should have time at the end of the year. 
My plan was to use the approach taken by K9-mail and just copy their implementation - what could go wrong, right?

**Comment by Patriccollu** [comment]
I can confirm that Corsican language can be selected on K9-Mail app.

**Comment by pstorch** [comment]
Just stumbled upon this: https://apt.izzysoft.de/fdroid/index/apk/io.nightdavisao.multilocale

Would it help to make Corsican locale selectable? Haven't had time to test myself.

**Comment by dennisguse** [comment]
@pstorch this tool needs root access.

**Comment by pstorch** [comment]
@dennisguse there is also an option to grant permission via ADB. I want to try that.

**Comment by pstorch** [comment]
I could give the app permission via adb, but it doesn't offer Corsican locale either.

**Comment by dennisguse** [comment]
@Patriccollu feature is available as of v4.15.0 (will take some days for F-Droid).
However, only for Android 14 (SDK34+) or later - the commit messages says SDK33+, but that is a mistake on my side.
I couldn't figure out a way to get the list of available locales/languauges prior Android versions and I didn't want to manually set those somewhere.
Hope this works for you - if not we can keep digging :D

**Comment by Patriccollu** [comment]
@dennisguse
I need to find an Android 14 device to be able to test as my current phone is only 11 :-(

Thank you for your work on this issue. I will keep you informed.

**Comment by dennisguse** [comment]
@Patriccollu The reason for this is an API that lists the available locales that were bundled with the application.
Sadly, this API is only available on Android 14 or later.
Otherwise, we would manually need to maintain the lists of locales in the source code in addition to the actually translations from Weblate.

I also checked for alternatives (like `LocaleManagerCompat.getApplicationLocales()`), but those don't provide not all locales.

**Comment by Patriccollu** [comment]
@dennisguse And what about the option to use the approach taken by K9-mail?

![1733696173576](https://github.com/user-attachments/assets/1f97721f-988a-4577-b1a9-0deb4b9c0a80)

**Comment by dennisguse** [comment]
Let's see...

**Comment by dennisguse** [comment]
@Patriccollu should work now..
Implementation is brutally ugly, but hey it works and the locales will be updated automatically.
We are not a beauty contest, right? ¯\_(ツ)_/¯

**Comment by Patriccollu** [comment]
Hi @dennisguse ,

It's just... perfect! ;-)

Thanks a lot,
Patriccollu.
![Screenshot_2024-12-12-14-11-29-135_de dennisguse opentracks nightly](https://github.com/user-attachments/assets/3c34ddf2-3f6b-4f93-a554-4f2061ad9a1c)
