### ISSUE TITLE
Support barometer 

### ISSUE THREAD

**Issue by k0styan3** [OpenTracksApp/OpenTracks#1994]
If you could add support for a built-in smartphone barometer, the app would be perfect! Do you have any plans for this?

**Comment by dennisguse** [comment]
Actually this is already supported. See #10.
I built this in 2020 :D

**Comment by k0styan3** [comment]
I can't find in the settings the ability to turn on the internal barometer, but only the external one via Bluetooth... or is this the barometer support? That is, only the external barometer is supported?

**Comment by dennisguse** [comment]
What phone do you have?
Are you sure it has a barometer?

**Comment by k0styan3** [comment]
Definitely there is - the phone model is Moto Edge 2022. You can check it out

**Comment by dennisguse** [comment]
Interesting :)
Can you check with another app like TrailSense that the sensor is actually reported (so OpenTracks should allow it to be selectable)?

**Comment by k0styan3** [comment]
I don’t understand why, but after resetting the settings, in the “sensors” section, an item appeared - Barometer and you can choose - internal!! I did nothing except reset the settings! Now the altimeter with the internal barometer will work?

**Comment by dennisguse** [comment]
Can you check if you can reproduce the broken behavior? 
There is always a chance that new bugs get introduced. 

Besides that you can upload screenshots to issues directly.

**Comment by k0styan3** [comment]
> Можете ли вы проверить, можете ли вы воспроизвести сломанное поведение? Всегда есть вероятность появления новых ошибок.
> 
> Кроме того, вы можете загружать скриншоты непосредственно в выпуски.

![требует блютуз](https://github.com/user-attachments/assets/0ea24022-3135-40f8-86c8-de2a6705929a)
Here is a screenshot attached. When you click on the button to select the source of changes, it requires you to turn on Bluetooth and does not allow you to select the built-in barometer.

**Comment by dennisguse** [comment]
The Bluetooth permissions are required, because external barometers are supported. 
The UI will not be shown without the Bluetooth permission and thus barometer selection won't be available.

**Comment by Cyclopropinon** [comment]
On a sidenote, displaying the current (and maybe min and max) pressure on the recording screen would be really cool

**Comment by dennisguse** [comment]
@Cyclopropinon internal barometer is already supported.
Why would like to see the air pressure?
TrailSense may be more suited for your use case.

**Comment by k0styan3** [comment]
in trailsense you can take photos and link them to a track? we just want your application (thank you for it by the way! to work 100% as intended and stated). do not be angry at our indications of bugs in the application - we do not write them just like that, but to eliminate errors!! and the built-in barometer is much more convenient to use than an external one, in my opinion. I have not seen a better application than yours and I really want its functionality to work as intended. With respect

**Comment by dennisguse** [comment]
@k0styan3 no worries.
We need understand what the problem is that you are trying to solve with a feature.
Then we can figure out how it can be build and how much effort it would be (including maintenance effort).
For example: OpenTracks doesn't not yet store air pressure data directly, but accumulates it.
It might now be quite some effort to show this data to the user.
And then the question arises if there may be better suited tools already available.

If you want to built the feature: just go ahead and try it out.
If the code looks good (aka maintainable), we can include it into OpenTracks.

PS/ I don't know the actual effort required...

**Comment by k0styan3** [comment]
Thank you for your trust - but alas, I am not a programmer! I do not know
how exactly you (as the author of the program) planned to implement the
barometer measurements, I saw them (I would like to see them, rather) as a
tool,  Calculated using GPS. That is, just for clarification. Well, maybe
also in the photo so that it is visible - the height above sea level is
such and such ... That's all. But the most important thing is the ability
to take photos while recording a track and export them along with the track
in one file.
С уважением, Константин С

пн, 21 окт. 2024 г., 20:44 Dennis Guse ***@***.***>:
