### ISSUE TITLE
Can't add a photo to a track

### ISSUE THREAD

**Issue by k0styan3** [OpenTracksApp/OpenTracks#1996]
**Describe the bug**

**To Reproduce**

If applicable:
* add screenshots
* add logcat output

**Technical information**
 - Device: [e.g. Nexus 7 (2013)]
 - OS: [e.g. LineageOS 15.1]
 - OpenTracks version: [e.g. v3.2.4]
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]
It is impossible to add a photo to a track - when trying to add a marker with a photo, there is simply no such option. In the list of options there is no option to add a photo. And there is no other way to add a photo Just no. I apologize in advance for my bad English - I am writing through a translator. My phone is android 13, stock firmware, no root. The program is installed from f-droid.

**Comment by iiipt** [comment]
I have the same problem
Device: Nokia 3.1 +   (2018)
system: android one (android 10)

There just isn't the button to add image to marker

**Comment by iiipt** [comment]
The osm dashboard works fine, when I click on marker it show the marker in the main app.

**Comment by k0styan3** [comment]
> The osm dashboard works fine, when I click on marker it show the marker in the main app.

I don't understand where this is...can you attach a couple of screenshots?

**Comment by iiipt** [comment]
![Screenshot_20241012-131535.png](https://github.com/user-attachments/assets/90905441-9800-4514-aee5-5ef33b5e33a5)

You click on the red marker in the map and it will open the marker in the main app (this is my last marker where I was able to upload image, its from august)

![Screenshot_20241012-131708.png](https://github.com/user-attachments/assets/e5a6787d-3020-4128-a595-2327860f9f23)

**Comment by k0styan3** [comment]
How do you even get from the tracker to the Axis Dashboard? When I click on
a track and then on the map icon at the top, I get a suggestion to open one
of two other applications, but it's  There is no OSM dashboard there!
С уважением, Константин С

сб, 12 окт. 2024 г., 14:37 iiipt ***@***.***>:

**Comment by iiipt** [comment]
You need to install it
here link: https://f-droid.org/packages/de.storchp.opentracks.osmplugin/
