### ISSUE TITLE
total time vs. moving time

### ISSUE THREAD

**Issue by ironspock** [OpenTracksApp/OpenTracks#2000]
moving time looks not correctly calculated compared to total time even consindering pauses and/or "slow moving activities" as geocaching, OSM mapping.
examples: 
total time        moving time             track distance in "lower mountains"
5:06:51		3:32:18			19,44 km
6:38:09		2:43:03			15,53 km
5:00:34		2:14:34			13,64 km

maybe issue is related to my settings
Settings
	recording intervall: 10 m 
	max. distance new segment: 200m
	downtime threshold: 10s

Sensors
	GPS 
		Sample Intervall: 0s
		GPS accuracy: 50 m
	Generisch
		Barometer: Internal Sensor

**Technical information**
 - Device: Gigaset GX6
 - OS: Android 13
 - OpenTracks version: v.14.0 5889 F-Droid

**Comment by dennisguse** [comment]
The pauses are visualized in OSMDashboard - this might be helpful for understanding the situation.
Slow moving activities (like hiking) should use higher thresholds.
Profiles for different activities+settings would be helpful see #1954.

**Comment by ironspock** [comment]
Hi Dennis,

thanks for your feedback. I have to tune my settings... ;-)

Regards ironspock
