### ISSUE TITLE
Pixel 8 pro Layout issue latest Version 

### ISSUE THREAD

**Issue by BoBBer446** [OpenTracksApp/OpenTracks#2013]
Today i installed the latest Version from f-droid. 
But the top Bar ist Not useabile
![Screenshot_20241101-212247](https://github.com/user-attachments/assets/6b14d3c0-1f68-4b82-a22d-fe9161cd06f2)

I cant Touch settings 

Looks Like the Layout ist to big 

Im using Pixel 8 pro with Android 15

**Comment by dennisguse** [comment]
Duplicate of #2008.

The setting icon is still functional (tested on Pixel 8), but harder to reach.
