### ISSUE TITLE
Feature Request: Recording interface without recording

### ISSUE THREAD

**Issue by haarp** [OpenTracksApp/OpenTracks#2019]
Hello!

**Is your feature request related to a problem? Please describe.**
I'd like to use OpenTracks as a bike computer. It features a nice interface with stats like speed, distance, averages, etc. For this purpose, recording is unnecessary.

**Describe the solution you'd like**
It would be cool if there was a button that brings up the recording interface (featuring your cool custom layouts) without actually doing a recording. i.e. activate GPS, show stats, but don't track or store it.

**Describe alternatives you've considered**
I could discard the recording after I'm finished with a ride. But this would become annoying quickly and store data until then unnecessarily. I might also forget to do so.

**Additional context**

Thanks! :)

**Comment by dennisguse** [comment]
Would be doable but with significant effort. 
Is the "discard track after recording feature not enough'?

If no data is stored, then the following stops working (at least): 
* the diagrams,
* the Dashboard API,
* pause and resume feature 

If you want to build this, go ahead.

**Comment by haarp** [comment]
Thanks for the reply!

> Is the "discard track after recording feature not enough'?

It's the convenience factor. You have to remember to stop the recording and press the small button to discard, sometimes in the cold, with gloves. Something that can quickly bring up and end the "speedometer" would be super convenient.

> If no data is stored, then the following stops working (at least)

Mhh, so we'd ideally actually store the data temporarily. You're right, I can see how this would require some new plumbing to be installed. The effort would likely not justify the small use case.

Please feel free to close this!

**Comment by dennisguse** [comment]
May I ask why you not use any other speedometer app for this use case?

**Comment by haarp** [comment]
OpenTracks has a nice and customizable dashboard with statistics :)

**Comment by dennisguse** [comment]
That's a very valid argument :D

What about an API that allows you trigger the deletion of a track?
We could add this even to the Public API as a parameter?
Basically: please stop recording and delete the data.
Wouldn't be too complicated.

**Comment by dennisguse** [comment]
@haarp ?
