### ISSUE TITLE
Accrescent app store

### ISSUE THREAD

**Issue by ellie3-36** [OpenTracksApp/OpenTracks#2028]
**Is your feature request related to a problem? Please describe.**
[Accrescent](https://accrescent.app/) addresses certain security issues that F-Droid has.

Security:  
[Signed repository metadata](https://accrescent.app/features#signed-metadata)  
[App signing key pinning](https://accrescent.app/features#key-pinning)  
[Name verification](https://accrescent.app/features#name-icon-verification)

Privacy:  
[No remote APK signing](https://accrescent.app/features#no-remote-signing)  
[No accounts](https://accrescent.app/features#no-accounts)

**Describe the solution you'd like**
Accrescent is an Android app store focused on security, privacy, and usability. Would love to see OpenTracks available in Accrescent.

Some relevant links:

Official website: https://accrescent.app/

Docs: https://accrescent.app/docs/index.html

App submission: https://accrescent.app/faq#app-submission

Contact: [contact@accrescent.app](mailto:contact@accrescent.app)

**Describe alternatives you've considered**

**Additional context**

**Comment by dennisguse** [comment]
We are working on reproducible builds.
You can publish it to Accrescent if you want to.
