### ISSUE TITLE
Share track: allow to configure file format

### ISSUE THREAD

**Issue by gdt** [OpenTracksApp/OpenTracks#225]
In the description, it says that tracks can be exported as GPX or KML/KMZ.   After recording a track, I see a share button, but that only does KMZ.  There was no apparent way to send GPX.

Later, I found "export all tracks" and could export my (all 1) track to GPX.  But that will drop many files, and there's no easy way to just send/save a single GPX.

One approach is to configure a preferred share method in preferences.

Another is to  have a choice menu on pushing share, before going to the android share destination menu.

Another approach is to have multiple share menu items.

Overall, I lean to configuring the preferred share method, as I suspect most users have a preference for interchange formats.

**Comment by dennisguse** [comment]
Released in v3.7.4
