### ISSUE TITLE
Theming support day/night

### ISSUE THREAD

**Issue by PrzemoF** [OpenTracksApp/OpenTracks#231]
**Describe the bug**
Dark theme is only partially supported

**To Reproduce**
1. Switch to "night mode" on android system (9.0)
2. Open OpenTracks
3. Go to "By time" or "by distance"
4. Graphs use bright background

If applicable:
![Screenshot_20200516-155740_OpenTracks](https://user-images.githubusercontent.com/2077043/82192660-2e9d8380-98ec-11ea-8592-f6b8913c6b0f.jpg)
![Screenshot_20200516-155743_OpenTracks](https://user-images.githubusercontent.com/2077043/82192662-2fceb080-98ec-11ea-983c-6bd496cbecd4.jpg)

**Technical information**
 - Device: Samsung Galaxy S10
 - OS: default stock android
 - Version 9.0

**Comment by dennisguse** [comment]
Valid request as OpenTracks only has one theme (and the white background is not the best).
