### ISSUE TITLE
Links in Help not clickable

### ISSUE THREAD

**Issue by PrzemoF** [OpenTracksApp/OpenTracks#232]
**Describe the bug**
Links in Help not clickable

**To Reproduce**
1. Go to Help
2. Try to click on any yellow link (see screenshot)
3. Nothing happens

If applicable:
OpenTracks downloaded from f-droid
![Screenshot_20200516-155727_OpenTracks](https://user-images.githubusercontent.com/2077043/82193005-acfa2580-98ec-11ea-9422-016ed2a6678b.jpg)

**Technical information**
 - Device: samsung galaxy S10
 - OS: default stock android
 - Version 9

**Comment by rgmf** [comment]
@PrzemoF thank you ;)

I've created a PR fixing it https://github.com/OpenTracksApp/OpenTracks/pull/234
