### ISSUE TITLE
Can't connect LIVALL Bluetooth Cadence sensor.

### ISSUE THREAD

**Issue by programmin1** [OpenTracksApp/OpenTracks#233]
**Describe the bug**
I cannot connect a LIVALL Cadence sensor.

**To Reproduce**
1. Go to Settings
2. Click on Cadence
3. Only "None" available.

I have unpaired and tapped it again, uninstalled and reinstalled app.

**Technical information**
 - Device: LGMP260
 - OS: 7.0
 - Version latest on FDroid.

**Comment by programmin1** [comment]
What's worse, the instructions here give "Connection refused" https://elinux.org/RPi_Bluetooth_LE

**Comment by dennisguse** [comment]
Could it be that this sensor does not support the Bluetooth Profile "Cadence and Speed"?
At least, I saw several complaints about not working with Strava.

So, the actual question from my side is: what does this sensor send?
Can you check with BLE Explorer to figure out what it can do?

**Comment by dennisguse** [comment]
@programmin1 any more insights?
