### ISSUE TITLE
Cumulative statistics

### ISSUE THREAD

**Issue by slecache** [OpenTracksApp/OpenTracks#244]
**Is your feature request related to a problem? Please describe.**
There was "Cumulative statistics" in MyTracks menu that it seems be missing in OpenTracks.

**Describe the solution you'd like**
Display the same screen than one track "Statistics" but by cumulating the data of all the tracks.

**Comment by dennisguse** [comment]
This was removed in one of my code cleanups.
The feature did not seem to be really useful (e.g., lack of filtering etc, no visualization of time) and made the code base slightly more complex (nowadays it would probably ok).
If you have time to work on this, it would be great.
#112 keeps track of a general statistics feature.

**Comment by slecache** [comment]
You're right: it's not really useful without filtering.

BTW, sorry for duplicate. I didn't find https://github.com/OpenTracksApp/OpenTracks/issues/112.
