### ISSUE TITLE
Setup Translation management systems (TMS)

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#27]
Option would be to use [translate5](https://translate5.net/)?

**Comment by dennisguse** [comment]
Just setup Transifex - might be sufficient.

**Comment by dennisguse** [comment]
We are now migrating to crowdin: https://crowdin.com/project/opentracks

Todo:
[ ] setup git integration (files are not correctly imported)
[ ] add link to everywhere needed (README.md / app?)

**Comment by pstorch** [comment]
Regarding the folder pattern, which are wrong in the PR. When you download it manually it seems to be right:

![image](https://user-images.githubusercontent.com/5598124/79685598-365d0000-823a-11ea-8ef9-5d0867fe134b.png)

**Comment by pstorch** [comment]
I got a new PR with still a wrong file Pattern with `de-rDE`, I solved it now via Export / Language Mapping:

![image](https://user-images.githubusercontent.com/5598124/79688987-539dc880-8252-11ea-9300-3164967269aa.png)

**Comment by dennisguse** [comment]
I guess you are using android-codes, right? For OpenTracks I tried yesterday two-letter-codes.
However, somehow no automatic import is taking place....

**Comment by pstorch** [comment]
Yes, I also tried the two-letter-codes, but then I got a Exclamation Mark at the syncing, because I have a language with a variant (Portuguese Brazilian) which is not compatible with two-letter-codes.

**Comment by dennisguse** [comment]
OK, but syncing worked? Because in the OpenTracks project syncing is not kicking in...
OpenTracks has French, Chinese and Portuguese that are the only android-codes.
I was thinking about using a custom language mapping.
Also we have support for Spanish South America and English (not yet figured out how to do this in Crowd in).

**Comment by pstorch** [comment]
I also had some issues with the syncing. Suddenly it was working again. After doing some more translations and forcing the build.
English is the default language for OpenTracks, right? So there is no translation necessary. You need to tick it off.

**Comment by pstorch** [comment]
I would also set "Skip untranslated strings" otherwise each language file contains all the english source strings as duplicates. Also "Skip untranslated files" should be set, I guess.

![image](https://user-images.githubusercontent.com/5598124/79690193-6b2c7f80-8259-11ea-8a72-426b148f28be.png)

Can you also try to approve all translations so far, because anyway they are in the App right now. Maybe that helps triggering the build and syncing.

**Comment by dennisguse** [comment]
Thanks, will try this.
English US is default.
English UK is the other.

**Comment by dennisguse** [comment]
Re-enabled transifex - hope that works better.
Removed crowdin commits from master.

**Comment by dennisguse** [comment]
Here is the transifex url: https://www.transifex.com/opentracks

For Transifex, the Github integration is activated - this _should_ automatically pull changes from the repo.
Push from Transifex to Github happens if 100% are translated (opens a PR).

For crowdin, I failed to setup the sync from Github - somehow the files would need to be uploaded manually(?) and changes in the repo are not reflected.
If somebody has an idea/experience, please let me know.

**Comment by dennisguse** [comment]
Transifex is up and running.

Workflow requires that all changes need to be reviewed and by default only languages are added via PR if 100% is translated.
Otherwise, we can trigger the process manually under settings/integration.
