### ISSUE TITLE
Speed/Moving time difference while exporting gpx

### ISSUE THREAD

**Issue by fdawans** [OpenTracksApp/OpenTracks#275]
I am using Osmand 3.6.3 on Android 10 with OpenTracks 3.7.3. 
It seems that there is an discrepancy when I import a Gpx track from OpenTracks to Osmand.
The moving time (also speed) is calculated differently in Osmand. I think that OpenTracks does not specify when there is speed or not in its gpx files and this might be the issue.

**Comment by dennisguse** [comment]
I just saw that the speed that OpenTracks stores is not exported into KML/GPX.
So, Osmand is computing their own speed based upon the GPS points.

#213 is related.
