### ISSUE TITLE
Take a look at viewbinding and check if it saves some effort

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#281]
We have some viewbinding code that is not very complicated, but also not fun to take care of.
Automatic viewbinding would probably nice to make the UI changes slightly more fun.

https://developer.android.com/topic/libraries/view-binding

**Comment by dennisguse** [comment]
@rgmf About the interval refactoring.
We can also try to refactor the TrackDataHub to a ViewModel (or even multiple ones).
We might be able to remove the internal interfaces.
Would this make sense?

**Comment by rgmf** [comment]
> @rgmf About the interval refactoring.
> We can also try to refactor the TrackDataHub to a ViewModel (or even multiple ones).
> We might be able to remove the internal interfaces.
> Would this make sense?

Good question! I think it makes sense and the refactor can be worth it.

**Comment by dennisguse** [comment]
https://github.com/OpenTracksApp/OpenTracks/issues/54
Is related - I guess.

**Comment by dennisguse** [comment]
Done for fragments in #485.

Final step: activities.

**Comment by dennisguse** [comment]
Already implemented.
