### ISSUE TITLE
Aggregated Statistics: add to PlantUML and message when empty list.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#295]
**Is your feature request related to a problem? Please describe.**
If there aren't tracks recorded then AggregatedStatisticsActivity layout shows an empty screen. It should show at least a message like this: "Record your first track to see aggregated statistics".

Also, in PlantUML doesn't appear AggregatedStatisticsActivity.

**Comment by dennisguse** [comment]
Why not disable the menu item if there is nothing to be shown?

**Comment by rgmf** [comment]
I've just done it and I think the result is good.

Disable the menu item means touch TrackListActivity instead of AggregatedStatisticsActivity.

Let me add a PR and then you take a decision ;)

**Comment by dennisguse** [comment]
@rgmf If you like it, just do it ;)
