### ISSUE TITLE
Shutdown on Huawei P10

### ISSUE THREAD

**Issue by geyr** [OpenTracksApp/OpenTracks#308]
**The App finishes every track after max 9 minutes**
App ends up tracking after short time without any notification. (Short-)Track is saved. ???
**To Reproduce**

If applicable:
* add screenshots
* logcat output not available. ..?!!

**Technical information**
 - Device: Huawei P 10 VTR-L29
 - OS: EMUI 
 - Version 9.1.0

**Comment by dennisguse** [comment]
Sounds like powersaving.
Can you check that the powersaving is disabled for OpenTracks on your device?
Otherwise, the powersaving mode will kill the TrackRecordingService (the notification will vanish) and the recording stops.

**Comment by geyr** [comment]
Hi Dennis, thanks for your helpful hint: I looked under powermanagement and there was a restriction for OpenTracks. Unchecking the "background-running not allowed" did it!Thanks for the App, with regardsDierk--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 03.07.20, 08:08 schrieb Dennis Guse <notifications@github.com>:

   
  Sounds like powersaving. Can you check that the powersaving is disabled for OpenTracks on your device? Otherwise, the powersaving mode will kill the TrackRecordingService (the notification will vanish) and the recording stops.
