### ISSUE TITLE
Long distances randomly divided in smaller parts and big part of the total path lost

### ISSUE THREAD

**Issue by vinceecniv87** [OpenTracksApp/OpenTracks#318]
First of all, thanks a lot for developing and mantaining OpenTracks. I like the idea of opensource apps, and data ownership given to the final user :)

**Describe the bug**
Everytime I use the app while riding my bike, "random" start and stop events split the recording of a long path into very short distances (few hundreds meters) and somehow a big part of the total path is lost. This weekend I did a test comparing the app with other ones (DirtTracks, MyTracks, very similar but less complete than OpenTracks) while travelling by bus (in order to check in realtime what was happening in the 3 apps).  I could actually verify that while the other apps did work fine and register the whole path of 34Km, OpenTracks did only register 3 paths of 5.52 Km, 0.61Km and 0.52Km. Therefore, a part of the path was been lost and the remaining was split in 3 separate segments.

**To Reproduce**
Try to record a long path while keeping the screen of your phone locked. I didn't check what happens by keeping the screen on (as I am normally riding a bike when I use the app). Therfore I don't know if the problem is related to when the app runs in the background.

If applicable:
I add screenshots of the paths registered in OpenTracks and in the other apps. 
![DirtTracks](https://user-images.githubusercontent.com/23019460/87323029-804e3d00-c52e-11ea-958d-9217b17eb5f8.jpg)
![MyTracks](https://user-images.githubusercontent.com/23019460/87323035-80e6d380-c52e-11ea-9419-77e0fb29f70a.jpg)
![OT_path1](https://user-images.githubusercontent.com/23019460/87323036-817f6a00-c52e-11ea-9cdc-26fff5c0b497.jpg)
![OT_path2](https://user-images.githubusercontent.com/23019460/87323038-82180080-c52e-11ea-87d8-24c0f05ea5c5.jpg)
![OT_path3](https://user-images.githubusercontent.com/23019460/87323039-82180080-c52e-11ea-8346-01e9296fb413.jpg)
![OT_summary](https://user-images.githubusercontent.com/23019460/87323040-82b09700-c52e-11ea-8609-0a1386565036.jpg)

**Technical information**
 - Device: Redmi Note 5
 - OS: Android 
 - Version: 9 (Xiaomi MIUI Global 11.03 Stable

**Comment by dennisguse** [comment]
Thanks!

Some questions:
* Why did you create three tracks?
  Was OpenTracks stopping the recording?
* How good was your GPS accuracy (shown in the notification)?
  Was it above the GPS accuracy threshold (see settings?)?
  Basically, OpenTracks ignores all GPS locations then...
* What is the settings of "Max distance"?
  If a new GPS location is farther away from the previous location a new segment is started.
* How do these Tracks look on a map (e.g., use OSMDashboard)?

**Comment by vinceecniv87** [comment]
- I didn't do it on purpose. I started the recording process once and when I discovered openTracks had stopped, I started the recording again. However, I remember sometimes not doing anything, recording just once, and getting one or multiple very short tracks as a result, at the end of the ride.
- the accuracy floats below 10m in general, goes up to 22m sometimes and rarely above 50m. I have set the recommended value of 50m.
- max distance is set to 200m.
- I attach the screenshots of the maps
![track1_googleearth](https://user-images.githubusercontent.com/23019460/87328850-6ca6d480-c536-11ea-8c1e-0e085dc070fa.jpg)
![track1_OSMDashboard](https://user-images.githubusercontent.com/23019460/87328856-6dd80180-c536-11ea-9825-e78ba41cf8a7.jpg)
![track2_googleearth](https://user-images.githubusercontent.com/23019460/87328857-6e709800-c536-11ea-8af1-ccc94e5530e7.jpg)
![track2_OSMDashboard](https://user-images.githubusercontent.com/23019460/87328859-6f092e80-c536-11ea-992d-d8e971cefcf5.jpg)
![track3_googleearth](https://user-images.githubusercontent.com/23019460/87328860-6f092e80-c536-11ea-82e9-60fd4a6081b4.jpg)
![track3_OSMDashboard](https://user-images.githubusercontent.com/23019460/87328863-6fa1c500-c536-11ea-9508-52d2679eaa60.jpg)

**Comment by rgmf** [comment]
@vinceecniv87 maybe you have to set battery optimisation off for OpenTracks. If battery optimisation for OpenTracks is on then when OpenTracks goes to background then Android kill the service. Maybe this is the reason because you have these results with OpenTracks.

**Comment by vinceecniv87** [comment]
Dear @rgmf,

what you suggested did work perfectly! I am a bit ashamed because I thought I had done it already (if I am not wrong a pop-up appears when using the app for the frist time). But still I am glad that we could solve the mistery very rapidly.

**Comment by dennisguse** [comment]
@vinceecniv87 Thanks for the detailed report ;)
