### ISSUE TITLE
Preferred rate ignored for aggregated stats

### ISSUE THREAD

**Issue by ChristophWurst** [OpenTracksApp/OpenTracks#321]
**Describe the bug**
Preferred rate, if set, should be used for aggregated stats as well, not just the detail view.

**To Reproduce**

0. Set preferred rate to km/h
1. Track something
2. Save as *Other* type (I use this to distinguish between different types of biking)
3. Open aggregated stats
4. See min/km for some activies

![opentracks](https://user-images.githubusercontent.com/1374172/87580570-fe017c80-c6d7-11ea-8331-22108c4513c4.png)

**Technical information**
 - Device: Google Pixel 3a
 - OS: Android 10, stock
 - Version 3.7.5

**Comment by rgmf** [comment]
Thank you @ChristophWurst, I overlooked this :(

PR on the way :D
