### ISSUE TITLE
EditMarker: photo disappears when rotating device

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OpenTracks#330]
1. Edit a marker. 
2. Select a photo (by camera or by gallery doesn't matter).
3. Before saving, rotate the device
4. Photo is not displayed anymore (but is still there when you click on save)

This is only a display issue, not a crash.

**Comment by dennisguse** [comment]
Damn - would I have known that orientation changes are that much effort, I would not naively enabled it (hoping nothing would break) ><

**Comment by dennisguse** [comment]
And I can reproduce it :)
 The old photoURL is restored and not the new one.
