### ISSUE TITLE
GPX files exported by Opentracks are not valid

### ISSUE THREAD

**Issue by jensMF** [OpenTracksApp/OpenTracks#335]
In GPX 1.1 speed is only allowed as extension.
Be aware that extensions have to have a different name-space than the default one.

Here is the documentation of for GPX 1.1:
[https://www.topografix.com/GPX/1/1/](url)

**Comment by dennisguse** [comment]
@ronajon @jensMF Thanks for your help!
v3.8.0 contains your changes to the GPX importer/exporter :+1:
