### ISSUE TITLE
Opentracks under contacts

### ISSUE THREAD

**Issue by gotros** [OpenTracksApp/OpenTracks#340]
Hi,

under contacts some of my contact's mobilenumbers are falsely recognized as Opentrack coordinate (?). Thus I got the normal number to call and text and beneath I got the same number with the opentracks symbol next to it. When I try to open the phone number with Opentracks I get the following error.

![Screenshot_20200729-214759_OpenTracks](https://user-images.githubusercontent.com/66696861/88846298-bd305a00-d1e5-11ea-8ace-4d03e6d268e8.png)

I am using official LineageOS on my old S5 klte.

Thx in advance,
gotros

**Comment by dennisguse** [comment]
@gotros 
Thanks!
I guess, I did not implement the intent-filter correctly to react to kml/kmz/gpx suffixes.

For devs: more info here: https://developer.android.com/guide/topics/manifest/data-element

**Comment by dennisguse** [comment]
@gotros I guess the itnent-filters where far too optimistic (might have been matching everything).
Could you give it a try?

The following ZIP contains the fix (it is the PlayStore build; different package name than FDroid version).
[OpenTracksUpstream-releasePlayStore.zip](https://github.com/OpenTracksApp/OpenTracks/files/4997476/OpenTracksUpstream-releasePlayStore.zip)

**Comment by gotros** [comment]
@dennisguse

Yes that fixed it. Thank you.
