### ISSUE TITLE
Allow backup

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OpenTracks#346]
**Is your feature request related to a problem? Please describe.**
I cannot perform an ADB backup of OpenTracks by myself, because the Manifest doesn't allow it.

**Describe the solution you'd like**
Allow backup, set 
`android:allowBackup="true"` in the manifest.

**Comment by dennisguse** [comment]
This flag disables backup to Google Cloud (on Google-enabled phones).
I am not eager to send backups there.

https://developer.android.com/guide/topics/data/autobackup

**Comment by dennisguse** [comment]
And we should add tools:replace="android:allowBackup" to enforce this for potential libraries that provide a AndroidManifest.xml

**Comment by pstorch** [comment]
Ok, I understand. 
Can the cloud backup and the ADB backup be separated somehow? Because this flag also hinders me as a user to do a local backup on my own.

**Comment by dennisguse** [comment]
I guess not - either you allow backups (incl. adb and Google Cloud) or not.
adb and Google Cloud Backup seem to use the same stuff on the device.

@pstorch Why would you like to backup the data via adb?
Is something missing in the KMZ export/import?
Or do we miss something else?

**Comment by pstorch** [comment]
I tried https://codeberg.org/izzy/Adebar to do a complete Backup of my phone. But it gave me a list of apps which doesn't allow backups. So I came to open this ticket.
Yes, export via kmz works, but would be an extra manual step.

There are settings in the manifest to require client encryption of the backup or only allow device to device backup https://developer.android.com/guide/topics/data/autobackup#define-device-conditions . Would that be an option?

**Comment by dennisguse** [comment]
It is API29 - but we can give it a try.
Should we create an issue for this?

**Comment by pstorch** [comment]
> It is API29 - but we can give it a try.

API 28, but still very recent. When I read it correctly that means that there won't be any backup for older devices because they don't know about the `clientSideEncryption` requirement. I hope older devices really disallow backups if they can't fulfill this requirment.

> Should we create an issue for this?

If you don't want to tacke it here, I'm fine with a separate issue.

**Comment by dennisguse** [comment]
We can also tackle it here ;)

**Comment by dennisguse** [comment]
@pstorch Did you try `clientSideEncryption`?

**Comment by pstorch** [comment]
No, haven't looked into it yet.

**Comment by pstorch** [comment]
I learned in the past days how important trust is and now I think we should close the android backup way and concentrate on https://github.com/OpenTracksApp/OpenTracks/pull/383

**Comment by hockeymikey** [comment]
> This flag disables backup to Google Cloud (on Google-enabled phones).
> I am not eager to send backups there.
> 
> https://developer.android.com/guide/topics/data/autobackup

Why?

**Comment by dennisguse** [comment]
@hockeymikey There are people out there that are using phones with the original ROM (incl. Google Play Services) for different reasons.
Just from the top of my head: 
* phone does not support a custom ROM
* custom ROMs did not reach most recent Android version (e.g., Android 11)
* stability of the original ROM
* lack of practical knowledge
....

Therefore, we cannot deploy this functionality.
If you need this, we need create a separate build (which can be published also to F-Droid).

**Comment by hockeymikey** [comment]
@dennisguse None of those matter at all. Let's go over the facts, you can disable syncing and google backups if you want to, if you're a pleb and running stock with gapps. What are you really preventing google from knowing if they had this app backed up? Your location? Nope, they are already getting all of that by your location requests to their servers using wifi and cell tower data. They are tracking your every step with the new covid tracker that is built into google services. If you have locations disabled, someone doesn't out there and they'll know and I'm sure it's "anonymous". They have complete control over the phone yet you're worried about backups for some reason? Give me a break and wake up. They scan your phone all the time with the play store, safety net is an obfuscated mess that no one knows what it really does or looks for. This is not a privacy feature at all, it's just a burden to the user.

**Comment by mamoit** [comment]
@pstorch @hockeymikey
FYI: backups are now a thing :slightly_smiling_face:
