### ISSUE TITLE
Sharing tracks as an image (with track statistics)

### ISSUE THREAD

**Issue by slecache** [OpenTracksApp/OpenTracks#363]
**Describe the solution you'd like**
I would like to share my activities in a photo containing some statistics. Could it be done with a custom dashboard like [OSMDashboard](https://github.com/OpenTracksApp/OSMDashboard)?

**Additional context**
Like this [one](https://support.strava.com/hc/article_attachments/360008726071/socialShare_run.jpg) see [here](https://support.strava.com/hc/en-us/articles/221089587-Sharing-your-Strava-Activities) for more details.

**Comment by dennisguse** [comment]
Interesting idea!
If I got it right, you just want to extend the currently available sharing function that is implemented, right?

Just to clarify it:
1. you want to share just the image OR the image and the gpx/kml/kmz?
2. the image was taken by you while recording a track (or do we need some generic image)?

If we don't need Internet access to generate the image, we can do this within OpenTracks.

**Comment by pstorch** [comment]
For the 1st example (other running apps do it similar), you would need to have some Track statistics (provided in the Dashboard interface), but you would also need to access the photo of a waypoint. We discussed this when adding the waypoints to the Dashboard interface. And there is no need for the Trackpoints. At the moment this sounds like a separate interface or a Feature withing OpenTracks (Share a Wapoint image and with added Track statistics).

**Comment by slecache** [comment]
> If I got it right, you just want to extend the currently available sharing function that is implemented, right?

I though about a new CustomDashboard but extending the currently available sharing function sounds good to me.

> 1. you want to share just the image OR the image and the gpx/kml/kmz?
> 2. the image was taken by you while recording a track (or do we need some generic image)?

I would like to share a image generated from:
1. A photo of a waypoint
2. Some Track statistics : total duration, distance and speed average

> If we don't need Internet access to generate the image, we can do this within OpenTracks.

You're right!

**Comment by hchr** [comment]
Would something like this be possible to?:
![test](https://user-images.githubusercontent.com/6417330/89916538-3fa61a00-dbe7-11ea-8a4d-5197f8e6b230.jpg)

**Comment by pstorch** [comment]
@hchr this would be something for the OSMDashboard as the map is involved.

**Comment by dennisguse** [comment]
I was thinking about rendering a Android layout on top of an image.
This way the resulting overlay would be easily configurable.
