### ISSUE TITLE
Avg. Pace: 4:60 instead of 5:00.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#370]
**Describe the bug**
I have a couple of tracks with an average pace of 4:60 but it should show "5:00". But it's really weird because I have tracks with an average pace of 5:00 and it shows "5:00". Sometimes good and sometimes bad ¿?
Seem that there is a bug inside `getSpeedParts` in `StringUtils`.

**To Reproduce**
It's very difficult because you need to create a track with an average pace of exactly 5 minutes.

If applicable:
![screenshot](https://user-images.githubusercontent.com/4819612/90051865-a48d6d00-dcd8-11ea-8722-e2639bba8099.png)

**Comment by dennisguse** [comment]
Bug is in StringUtils.getSpeedParts() and this line:
```
return new Pair<>(String.format(Locale.US, "%d:%02d", minutes, seconds), unitString);
```

And it is a rounding issue - so, if you have 04:599 you get 04:60.

**Comment by dennisguse** [comment]
I also added some test coverage for this function ;)

@rgmf nicely spotted!
