### ISSUE TITLE
Mountain bike icon not showed.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#371]
**Describe the bug**
When I change the activity type to "mountain bike" selecting the icon then the activity type is "mountain bike" but the icon is "bike".

**To Reproduce**
1. Click on any track in the list.
2. Menu / Edit.
3. Select in the spinner the mountain bike icon. Change the icon and the activity type.
4. Save.
5. You'll see bike icon but not mountain bike icon.

**Comment by pstorch** [comment]
@rgmf thanks for spotting. "mountain bike" was still in the bike list.
