### ISSUE TITLE
Shorter start recording toast

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OpenTracks#372]
Maybe it's only me, but when I test the Dashboard with a started recording, I have to wait a long time until the toast of the notification disappears to open the Dashboard. It is also not possible to swipe it away.
Is there a reason why the toast stays in the way so long? Can we make it shorter?

**Comment by dennisguse** [comment]
I guess, you mean the service notification, right?
Let me check if we can make this one shorter (but I am not sure as it might be an Android security feature).

**Comment by dennisguse** [comment]
I did not find anything to reduce the duration of the notification. I guess, it is just as it is as we long need a foreground service.
