### ISSUE TITLE
elevation and gps coordinates not shown

### ISSUE THREAD

**Issue by bkmystim** [OpenTracksApp/OpenTracks#382]
Hi, on my samsung xcover4 there is currently no way to get the elevation and coordinates feature to work. In recorded tracks neither of them is shown, even when set in the settings menue.

Any idea? Thx BK

**Comment by bkmystim** [comment]
App version 3.8.1 via fdroid

**Comment by dennisguse** [comment]
@bkmystim These infos are only shown while recording.
They basically show the lat/long/elevation at your current position.
For this reason, these are not shown after a track was recorded.
Why would you need them (and which actually)?

**Comment by bkmystim** [comment]
Would be great to know afterwards the meters you walked uphill and downhill, and to know lowest and highest altitude of the recorded track. Lat and long is actually not so important - afterwards.

**Comment by dennisguse** [comment]
We are working on elevation gain/loss since some time and might have this ready soonish.
See #243.
