### ISSUE TITLE
Implement Espresso UI tests

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#387]
Follow-up to #385.

It would be a great idea to have some basic espresso UI tests - we literally have no test coverages on the UI code.
But it would be great for maintenance.

Some ideas for tests cases:
* start, pause, stop a track recording
* add, delete waypoints, add from picture/camera
* change waypoint/track description
* search waypoints, tracks
* open settings
* start/stop gps
* export all/import all 

https://developer.android.com/studio/test/espresso-test-recorder

**Comment by dennisguse** [comment]
@pstorch Somehow the EspressoUI recorder cannot figure out how the record/pause/stop buttons work.
If I migrate to long-press (gives us 400ms delay) it works, but I guess the delay is too short.
Do you have suggestions?

**Comment by pstorch** [comment]
The delay is configured as https://github.com/OpenTracksApp/OpenTracks/blob/48c3695b5df54861dba544ec36ac576c7abf388b/src/main/res/values/settings.xml#L227 1500ms

**Comment by dennisguse** [comment]
The delay I saw.
However, I could not figure out why the Espresso UI recorder does not realize that it is an UI element that I am interacting with.
Somehow it ignores our custom touch events.
I will do some digging ;)

**Comment by pstorch** [comment]
Hmm, the Button reacts onTouch with MotionEvent.ACTION_DOWN and MotionEvent.ACTION_UP, I don't know if you can simulate that with Espresso UI.

**Comment by dennisguse** [comment]
The activity type chooser is also not working.
OnTouch seems to be the trouble - I will do some more digging ><
