### ISSUE TITLE
Renaming: change marker to waypoint

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#389]
In the database layer, we call it waypoint while on the UI layer it is called marker.
Just rename everything to waypoint.

**Comment by dennisguse** [comment]
@pstorch @rgmf I slept some days over this and now I am not sure anymore.
So, we have the functionality to _mark_ something while recording a track.
Is this
a) a waypoint, 
b) a marker?

At the moment, I am now more in favor of marker as a waypoint is something on a route that I am following.

**Comment by rgmf** [comment]
I think it's not worth the change from marker to waypoint. Anyway, every time you add a Marker you are really adding a Waypoint, right? I doesn't matter the terminology, I think it's clear that it's the important thing.

**b)** for me.

**Comment by pstorch** [comment]
It's a marker-waypoint :wink: 
I can live with either term.

**Comment by dennisguse** [comment]
That makes my life complicated ><
Then let's go for marker.
I can take care of the refactoring after merging the open PRs, as this will be a lot of changes.

And thanks for the input!

**Comment by pstorch** [comment]
Is it really worth the work?

**Comment by dennisguse** [comment]
It is actually not too much effort (just refactoring for 2-3 hours using AndroidStudio).
Afterwards, we don't have to explain the difference between a marker and a waypoint (and also we don't need to document that it is the same).
Personally, I find it also kind of confusing.

This time the DB-update is just an ALTER-table statement (as sqlite support this).

But yes - it is not the most important work!
I will just do it, when we have no open PRs and I have a free afternoon.
