### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Aquarh** [OpenTracksApp/OpenTracks#392]
It is impossible to download opentracks from F-droid

**To Reproduce**
1. Go to F-droid
2. Click on opentracks
3. Scroll down to install

"Download Failed"
"The requested file has not be found"

*Fdroid is up to date

**Comment by rgmf** [comment]
Can you see 3.9.1 OpenTracks version? From the web page the link works well: https://f-droid.org/en/packages/de.dennisguse.opentracks/

**Comment by Aquarh** [comment]
Thank you, it works ! I use your link and open with fdroid... I don't understand fdroid said that my repo was up to date ...
