### ISSUE TITLE
cumulative positive elevation in summary statistiques

### ISSUE THREAD

**Issue by tclavier** [OpenTracksApp/OpenTracks#394]
Given a track in mountains, I want to know the cumulative positive elevation in order to compare tracks. 

Could you compute and add this indicator in summary screen of track ?

**Comment by rgmf** [comment]
This feature is on the way :D

Look at this https://github.com/OpenTracksApp/OpenTracks/pull/243

**Comment by tclavier** [comment]
Ho great, I close this issue.
