### ISSUE TITLE
Unable to stop!

### ISSUE THREAD

**Issue by mbnoimi** [OpenTracksApp/OpenTracks#396]
**Describe the bug**
As show in the following gif OpenTrack unable to stop at all!
I tried to reinstall it but it still reproduce the same bug.

![recording_20200830_202940](https://user-images.githubusercontent.com/284547/91666172-5b745000-eb03-11ea-8a75-ca2a341ea55f.gif)

![photo_2020-08-30_20-58-01](https://user-images.githubusercontent.com/284547/91666193-82328680-eb03-11ea-99a4-aa61c16f2f3e.jpg)

**Technical information**
 - Device: ASUS Zenfone 6
 - OS: Android 5.0
- Version: 3.9.1

**Comment by rgmf** [comment]
This bug is fixed... Soon there will be a new release. Thank you for open this Issue ;)

Here more info: https://github.com/OpenTracksApp/OpenTracks/issues/390

**Comment by mbnoimi** [comment]
@rgmf Oops I didn't look in the closed issues

**Comment by dennisguse** [comment]
There is another issue related that we are going to resolve (soonish): #388.
Once the TrackRecordingService dies while recording, the UI never gets this info and it requires resetting the preferences (which is not possible while the UI thinks a recording is ongoing).
So, the only option to recover from this state is to delete all app data.

**Comment by dennisguse** [comment]
Fixes (and a workaround) are in v3.9.2 (also for the behavior in my previous comment: https://github.com/OpenTracksApp/OpenTracks/issues/396#issuecomment-683451712)

Let's leave this issue open until this release reaches F-Droid (will take up to 7 days...).

@mbnoimi It would be great if you could test the fixes.
Here is the build that I just pushed to the PlayStore:
[OpenTracksUpstream-releasePlayStore.zip](https://github.com/OpenTracksApp/OpenTracks/files/5147475/OpenTracksUpstream-releasePlayStore.zip)

**Comment by mbnoimi** [comment]
@dennisguse I installed it and imported the old tracks it works fine but tomorrow I'll test it practically (I've 8 km to walk)

**Comment by mbnoimi** [comment]
@dennisguse I can see you've released a new version https://github.com/OpenTracksApp/OpenTracks/releases/tag/v3.9.3 may you please upload the upstream?

**Comment by dennisguse** [comment]
What do you mean?
I can only update the PlayStore as Fdroid uses its own key for signing.

**Comment by mbnoimi** [comment]
> What do you mean?

I only want an apk because waiting 7 days is too much,

**Comment by dennisguse** [comment]
1. The APKs are not the same (the application the is different)
2. I cannot build Fdroid (and I guess never will)
3. Creating a build takes me about 10min - and I rather waste my spare time differently
4. We are using the PlayStore build to finance our expenses

@mbnoimi If you have time and want to take a look on how to create nightly builds - feel free.
I guess some people might be interested in getting a nightly F-Droid repo.
One advantage: as app version, we use the #commits (main branch) - so this can be directly used for nightly builds.

**Comment by dennisguse** [comment]
@mbnoimi I totally forgot: promo codes for the play store are available here: https://github.com/OpenTracksApp/OpenTracks/issues/97

**Comment by FHenry** [comment]
Same bug here l, hope New apk on f-droid soon

**Comment by rgmf** [comment]
> Same bug here l, hope New apk on f-droid soon
> 
> Edit: Finnaly pay from store, you deserve it for this opensource software

Version 3.9.2 is already in f-droid and this version should fix this bug ;)

**Comment by dennisguse** [comment]
Saldy, export is not yet working (needs v3.9.3).
