### ISSUE TITLE
gps is kept on when not recording

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#403]
Galaxy s4 LineageOS 712

After stopping a track the device keeps the icon for gps use in status bar and only disappears if i go into recents and swipe it away or if i force stop open tracks. The open tracks icon in the status bar works fine. 
If the gps keeps running out will kill the battery quickly.
For me it kept running for over two minutes before i force stopped it.
It appears to work fine on my s7 with Android 8

Start the app start a track, end the track and watch the gps active icon (usually a upside down teardrop poi marker icon). 
After a check the icon stays on for over an hour at least.. no point checking for longer

**Comment by rgmf** [comment]
I can reproduce it... :+1:

**Comment by rgmf** [comment]
Catched and fixed. What an error!!!! :see_no_evil:

This becomes in my favourite screw up :sweat_smile:

**Comment by dennisguse** [comment]
@rgmf Sounds like we need another release.
What do you want 3.9.4 or 3.10.0 (because the interval view is included).

**Comment by rgmf** [comment]
@dennisguse I'm with this: https://github.com/OpenTracksApp/OpenTracks/issues/406

Do you have those issues. I'm fixing them now.
