### ISSUE TITLE
Intervals: issue in recorded and in recording.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#406]
**Describe the bug**
There are troubles with intervals. In recorded you only can see intervals if you change the interval (spinner). In recording you cannot see intervals.

**To Reproduce in recorded**
1. Go to any track you recorded.
2. Move to intervals tab.
3. You won't see intervals.
4. Change spinner interval value and then you'll see intervals.

**To Reproduce in recording**
1. Record a new track.
2. Move to intervals tab.
3. Intervals don't show.

**Comment by dennisguse** [comment]
That is my fault. It is the initialization of the interval.
