### ISSUE TITLE
Opening gpx file from OT in OsmAnd~ crashes OsmAnd~ since last update to 3.9.3

### ISSUE THREAD

**Issue by Jakethethird** [OpenTracksApp/OpenTracks#411]
**Describe the bug**
I have always opened the gpx files from the OT interface in OsmAnd and never had a problem. But after the last update to 3.9.3, it now starts OSMand which then crashes and closes after showing the initial OSMand start up screen. If I select an alternative mapping program (MMTracker), it works OK.

**To Reproduce**
1. Go to OT page showing all recorded routes
2. Click on button to open gpx file in another program
3. select OsmAnd~ from the programs suggested.
4. OsmAnd start page appears, then program is "stopped" and closes. Rebooting phone makes no difference.

**Technical information**
 - Device: motoG (2014)
 - OS: [e.g. LineageOS 14.1 with microG, no GApps]
 - Version [e.g. v3.9.3]

**Comment by dennisguse** [comment]
Found the bug and it really hurt - we were sending data as intent extra and the data could not be unparceled.
But the actual fun fact: it was not even used...

PS: Cool that somebody is using this functionality!
I was recently wondering if we should keep it or not.
Why are not using OSM Dashboard?

**Comment by Jakethethird** [comment]
Thanks for fixing this so quickly. I always use this as the easiest way to get the .gpx file into osmand. When I first discovered this, I thought "wow, that is so cool"
Once moved across, I can access it via the osmand dashboard as it is in the list. But I only do this for new or interesting routes - most of my training is on just a few local loops (biking).
