### ISSUE TITLE
Crash after exporting train into map

### ISSUE THREAD

**Issue by petrhejna** [OpenTracksApp/OpenTracks#413]
**Describe the bug**
Exporting track via "map" button in top left causes craah.

**To Reproduce**
1. Go to Track Detail
2. Click on Map Button
3. Doesnt matter which format 
4. Error appears (but sometimes, no error but nothing happens).

![Screenshot_20200905-121050_Android_system](https://user-images.githubusercontent.com/383295/92303051-bf6a9e80-ef71-11ea-9f5b-e0fce97c41a5.png)
![Screenshot_20200905-121045_OpenTracks](https://user-images.githubusercontent.com/383295/92303052-c09bcb80-ef71-11ea-94f8-faa517e754b9.png)

![Screenshot_20200905-121809_OpenTracks](https://user-images.githubusercontent.com/383295/92303069-e7f29880-ef71-11ea-8be9-9e4f73a9cfbd.png)

**Technical information**
 - Device: [One Plus 7 Pro]
 - OS: [e.g. LineageOS 16]
 - Version [v3.9.3]

**Comment by dennisguse** [comment]
Hopefully fixed in https://github.com/OpenTracksApp/OpenTracks/issues/411 aka last night.
Released with v3.9.4 (already on PlayStore, but not yet on F-Droid).

Can you give it a try?

**Comment by petrhejna** [comment]
Ah, good to hear that. Thanks. I use F-Droid only. So I'll try it once it there. 

:)

**Comment by dennisguse** [comment]
Spoiler alert: I know - otherwise I would have gotten a notification from the PlayStore as they collect the stacktraces of all app crashes.
Privacy at it's best.

**Comment by dennisguse** [comment]
Update just reached fdroid. @petrhejna can you check if this works for you?

**Comment by petrhejna** [comment]
Works like a charm. Thank you:! :)

**Comment by dennisguse** [comment]
Thanks for testing and sorry for the inconvenience...
