### ISSUE TITLE
F-Droid has trouble installing in Android 11 with Target SDK

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#420]
More information is available here: https://gitlab.com/fdroid/fdroidserver/-/issues/827

We have the option to downgrade to 29 as we do not use any 30 feature except that Android enforces more limitations like querying for other installed apps.
From a privacy perspective this is nice, but not that important for OpenTracks.

**Comment by rgmf** [comment]
Downgrade to 29 is a good solution for now. When we add 30 features we'll see.

**Comment by dennisguse** [comment]
Seemingly people have trouble #421.

**Comment by duggalsu** [comment]
Downgrade is a good solution if it works on fdroid for now.

**Comment by dennisguse** [comment]
We downgraded for v3.10.0 and wait until Fdroid fixes the issue.

**Comment by ctennenhouse** [comment]
What is version 29? I only see 3.9.5, 3.9.4, 3.9.3 on F-droid.

**Comment by dennisguse** [comment]
That is the targetSDKversion that OpenTracks is compiled for incl 3.9.5 it was 30 and due to the Fdroid issue 3.10.0 is 29.
But this version is not available via Fdroid - probably tomorrow. You can use the PlayStore version until then.

**Comment by aaronaxvig** [comment]
3.10 is still not available on F-Droid.

**Comment by dennisguse** [comment]
I know, but OpenTracks was built yesterday. So we are waiting for the signing. Can't do anything about this.

**Comment by aaronaxvig** [comment]
Oh well, I ended up buying it on the Play Store so I guess you get a coffee out of it!
________________________________

**Comment by dennisguse** [comment]
@aaronaxvig FYI: the package name is different, so you can install both versions in parallel.

**Comment by pstorch** [comment]
The fdroid buildserver was fixed to properly sign the APK with targetsdk 30. The OSMDashboard is in the current buildcycle with targetsdk30. If this is published, maybe someone can test it with Android 11. If that works we can upgrade the main application to targetsdk30 again also.

**Comment by aaronaxvig** [comment]
I would be happy to test out new builds of either program if someone can point out when the new builds are available.  It is unfortunate that the builds take days/weeks to churn.

**Comment by pstorch** [comment]
OSMDashboard is available on F-Droid in Version 2.4.1 (15) which is targeting sdk30.
@aaronaxvig would be nice if you could give it a try.

**Comment by aaronaxvig** [comment]
Version 2.4.1 of OSMDashboard installs and works via F-Droid.

Also version 3.10 was available in F-Droid and installs and runs fine.

**Comment by pstorch** [comment]
@aaronaxvig thanks for the feedback. Have you had to uninstall the previous version of OSMDashboard?

**Comment by aaronaxvig** [comment]
> 
> 
> @aaronaxvig thanks for the feedback. Have you had to uninstall the previous version of OSMDashboard?

I'm pretty sure that I didn't uninstall it; in fact I was not able to find any way to interact with my previously installed versions of OpenTracker or OSMDashboard after my phone updated to Android 11.  They did not appear in the app list nor show as installed in F-Droid.

Once I installed the new version of each app via F-Droid, they had their old settings/data still in place (OpenTracker did not show the data from the Play Store version of OpenTracker, which I understand is expected because they are different namespaces).  For instance OpenTracker had some tracks from before the Android 11 update, and OSMDashboard has some configurations of offline maps still in there.

**Comment by dennisguse** [comment]
Cool - so we survived this nasty thing then!
@aaronaxvig Thanks for testing!
