### ISSUE TITLE
Walk and Run

### ISSUE THREAD

**Issue by PhantomO2** [OpenTracksApp/OpenTracks#428]
(Feature request) So I usually walk as well as run during my workout. My workout starts with 3-4 min of walking and then 1-2 min of running and then again 3-4 min of walk and then again 1-2 min of run. I do this for about an hour. I don't stop for a minute during that time. It's just walking and running combined. So is it possible to calculate the distance I ran and the distance I walked? Right now it shows " the total distance travelled", "the moving time", "the total time", "Max speed", "average speed" and so on. Is it possible to add " total running distance" and "total walking distance" too. And if the problem is the "speed", as different people have different walking and running speed. Then is it possible to provide the "Speed interval" for both running and walking. Like "5-6" km/hr walking and "9-13" km/hr jogging. It can register our walking, jogging and running distance based on the speed interval that a user provide. Thank you.

**Comment by dennisguse** [comment]
I guess that is out of scope within OpenTracks, but it could be integrated into a separate dashboard.
