### ISSUE TITLE
doesn't record with screen of

### ISSUE THREAD

**Issue by fmmaresca** [OpenTracksApp/OpenTracks#430]
Android 9 on xiaomi redmi note 7.
Distance does not increment while screen is off.

**Comment by rgmf** [comment]
Maybe related with this: https://github.com/OpenTracksApp/OpenTracks/issues/177

**Comment by fmmaresca** [comment]
Probably, thank you. Setting the battery optimization off, however doesn't seems to solve the issue here.

Sorry about reporting Android 9 version, the correct device info is:
Android 10 QKQ1.190910.002
MIUI Global 11.0.1. 
Best regards.

**Comment by dennisguse** [comment]
Any news on this?

**Comment by fmmaresca** [comment]
No. I'm locked for now, not going out cycling. Last time I've tried the issue was there. Sorry.
