### ISSUE TITLE
Edit activity doesn't change until you exit and enter again.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#435]
**Describe the bug**
When you edit an activity (name or activity type, for instance) the changes don't take place until you exit to TrackList and enter to the activity edited again.

**To Reproduce: scenario 1**
1. Click on any track on the list.
2. Click on menu and select edit.
3. Change the name of the activity and click on Save.
4. You come back to activity details but name is not changed.

**To Reproduce: scenario 2**
1. Click on any track on the list.
2. Click on menu and select edit.
3. Change the type of the activity and click on Save.
4. You come back to activity details but icon has not changed and rate has not changed neither.

**Technical information**
 - Version 3.9.5

**Comment by dennisguse** [comment]
@rgmf :+1:
