### ISSUE TITLE
F-Droid Badge

### ISSUE THREAD

**Issue by forrestguice** [OpenTracksApp/OpenTracks#440]
Greetings. I arrived here from your post on the F-Droid forum.

I thought you might be interested, a badge that shows the recent F-Droid release is already available. I'm not sure its actually documented anywhere - I saw it mentioned in another forum post a few months back and added it to my own repos.

Anyhow, try adding the following markdown to your readme:

`[![F-Droid](https://img.shields.io/f-droid/v/de.dennisguse.opentracks.svg)](https://f-droid.org/en/packages/de.dennisguse.opentracks/)`

[![F-Droid](https://img.shields.io/f-droid/v/de.dennisguse.opentracks.svg)](https://f-droid.org/en/packages/de.dennisguse.opentracks/)

**Comment by dennisguse** [comment]
Thanks - I just added this!
Sadly, this is not available for Google Play :(
