### ISSUE TITLE
Export/Import GPX without heart rate data end up with heart rate data.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#446]
**Describe the bug**
I've exported and imported all my OpenTracks tracks and some of them have ended up with heart rate datas that I can see in graphs tabs.

I've never used heart rate sensor and in GPS files there are not any heart rate data.

I have some gpx files I know they result in this weird situation, so I'm going to try to catch what happening

An image where you can see heart rate data but I don't know what they come from:
![image](https://user-images.githubusercontent.com/4819612/95215584-69e41480-07f1-11eb-922e-3cd185805bfe.png)

**Technical information**
 - Device: Pixel 2XL
 - OS: LineageOS 17.1
 - Version: 3.11.0

**Comment by dennisguse** [comment]
Quick guess: the shown heartrate is the speed (or rather the inverse of speed aka pace).
Could that be the case?

**Comment by rgmf** [comment]
> Quick guess: the shown heartrate is the speed (or rather the inverse of speed aka pace).
> Could that be the case?

Yes, I was thinking the same that you because values are really small, just like speed values in the gpx file.

**Comment by rgmf** [comment]
@dennisguse very easy... a couple of breaks in a switch/case statement was missing. Fixed and merge onto main.
