### ISSUE TITLE
Export all silently overwrites destination files

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OpenTracks#451]
At the moment the "Export all" function exports all tracks over and over again. 
I would like to have a check if the file already exists at the destination directory and being asked what conflict resolution should be performed:

Message: "This track already exists at the destination directory!"
Options:
- overwrite
- skip
- [ ] checkbox "do it for all conflicts"

As the track list in OT gets longer and longer a skip possibility for already exported tracks could significantly speed up the "Export all" process.
And if you have a cloud destination directory you don't cause unnecessary traffic.

**Comment by rgmf** [comment]
@pstorch @dennisguse someone working on this? I have some time this week and I could take over this.

@dennisguse Should I wait until https://github.com/OpenTracksApp/OpenTracks/pull/454 merge?

**Comment by dennisguse** [comment]
I guess, this would not conflict with #454.
Anyhow, it is ready, so if you could give it a spin, we can just finally merge #454 :)
