### ISSUE TITLE
Accept donation in bitcoin :)

### ISSUE THREAD

**Issue by petrhejna** [OpenTracksApp/OpenTracks#455]
Hi, great app I would love to donate some sats :)

**Comment by dennisguse** [comment]
Nice!
@rgmf @pstorch 
Does anybody of you want to take about this or should I?

**Comment by pstorch** [comment]
I'm not familiar with Bitcoin.

**Comment by rgmf** [comment]
I'm not familiar with Bitcoin neither but I think is nice to add this possibility for people who prefers bitcoins.

**Comment by petrhejna** [comment]
All around the world governments go brrrrrrrrr (printing money like crazy). It's good time to get into Bitcoin and Austrian economics. ;)

Bitcoin is the unconfiscable unprintable magic internet money. ;)

**Comment by dennisguse** [comment]
Here we go: 
```
bitcoin:BC1QCKPLS3LPJLCPYXZM66HCY65HNESAS9ZGACY6YC
```

**Comment by petrhejna** [comment]
Will you please make it PR and merge it to Readme (for other to be able to contribute as well).

Also QR code would be nice to have. :)
