### ISSUE TITLE
KmzTrackImporter: Unable to parse kml in kmz

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OpenTracks#470]
While testing #466 I stumbled upon the error that an exported kmz file from OT fails at import (or share from file manager) with "D/KmzTrackImporter: Unable to parse kml in kmz".
When I extract the doc.kml file from it, I can import it into OT without error.

**Comment by rgmf** [comment]
I was trying to reproduce your error and I cannot to import all my OT exported tracks. This is the error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ClipData.getItemCount()' on a null object reference
```

Something was broken in PR #466 


@dennisguse don't prepare new release.

**Comment by pstorch** [comment]
I'll check

**Comment by pstorch** [comment]
I found the Nullpointer, yes was introduced by me.

@dennisguse can I remove the toString() hack? I get trouble in the debugger:

![image](https://user-images.githubusercontent.com/5598124/96906310-e89bab80-1499-11eb-8919-63b5684ba309.png)

**Comment by dennisguse** [comment]
@pstorch sure, it was only necessary for the refactoring.

**Comment by pstorch** [comment]
Simple fix, I pushed it directly. Hope is it ok. @rgmf please give it a try.

**Comment by rgmf** [comment]
@pstorch it works!!!
