### ISSUE TITLE
Weekly, Monthly, Yearly - Aggregated stats

### ISSUE THREAD

**Issue by duggalsu** [OpenTracksApp/OpenTracks#475]
Add option to view weekly / monthly / yearly aggregate stats to track performance

**Comment by dennisguse** [comment]
@rgmf This is somehow implemented, right?
I mean the new filter option allows to do this...

**Comment by rgmf** [comment]
@dennisguse you are right, I overlooked it. I've just closed it.

Closing issues makes me happy :rofl: :rofl:

**Comment by dennisguse** [comment]
@rgmf me too :)
