### ISSUE TITLE
de.dennisguse.opentracks.databinding package isn't in main branch

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#490]
**Describe the bug**
After pull main I don't see databinding package. Am I doing something wrong? That package is not in the main branch, right?

**Comment by dennisguse** [comment]
Yes, you are right.
The databinding package is autogenerated (i guess using Android gradle plugin somehow).
I guess, AndroidStudio needs to sync with gradle again.

**Comment by rgmf** [comment]
It was my AndroidStudio (not being aware of dynamically generated files).

BTW I've fixed a bug in ExportActivity (setContentView was missing).

**Comment by dennisguse** [comment]
Thanks!
