### ISSUE TITLE
Migrate to ViewPager2

### ISSUE THREAD

**Issue by TacoTheDank** [OpenTracksApp/OpenTracks#522]
https://developer.android.com/training/animation/vp2-migration

Why? https://medium.com/google-developer-experts/exploring-the-view-pager-2-86dbce06ff71

**Comment by dennisguse** [comment]
@TacoTheDank PR welcome.

One thing: we have gesture detection on the the charts (zoom, pan) and those gesture interactions with the viewpager (swiping from chart to statistics etc.).
The underlying issue is that the gesture detection on the charts captures the events.
See #105.

**Comment by TacoTheDank** [comment]
@dennisguse Ah yeah, I experience that issue.

**Comment by TacoTheDank** [comment]
Thanks!
