### ISSUE TITLE
OpenTracks crashes immediately after start recording

### ISSUE THREAD

**Issue by Saboe** [OpenTracksApp/OpenTracks#535]
When I start OpenTracks and want to record a track, OpenTracks crashes immediately. It seems to be a new bug with version 3.13.0. With prior versions there wasn't this issue.

I get only the following crash report/screen from Adnroid:
OpenTracks keeps stopping
(i) App info
X Close app

**Technical information**
 - Device: Fairphone 3
 - OS: Android
 - Version 10, Build 8901.3.A.0054.20200929

**Comment by dennisguse** [comment]
Sorry for the inconvenience.
You can just upgrade to v3.13.2 that contains fixes for this.
Fixed in #513.

**Comment by Saboe** [comment]
Thanks for the hint. Yesterday I've checked F-Droid for the latest version and it shows version 3.13.0 but now it's 3.13.2. Now I've upgraded OT.
