### ISSUE TITLE
Option to write UUID to Imported Tracks

### ISSUE THREAD

**Issue by jdohm** [OpenTracksApp/OpenTracks#539]
**Is your feature request related to a problem? Please describe.**
When syncing tracks via NextCloud/OwnCloud older Tracks and Tracks from other tracking applications get re imported everytime "import all" is used. 

**Describe the solution you'd like**
While importing tracks that don't own a UUID, I would like the option to add a UUID to the imported file. 
A Solution could be a pop up, stating: 

  Write UUID to imported file?
  In order to prevent the imported track from getting imported again OwnTracks would like to write a unique ID to the file.
  Yes / No 

**Describe alternatives you've considered**
a) Writing the UUID to imported file according to an advanced import setting.
b) Prevent imports of data which match already existing tracks (matching on time, place ...) 

**Additional context**
This issue arises when all data is synced in one folder and the user uses other trackers as well.
For example I track my phone using PhoneTracker and in case I forgot to start OpenTracks or it crashes etc. I export the gpx track out of PhoneTracker to the synced folder. 
This feature was first discussed here: #90

**known workaround**

> @jdohm we generate the a unique identifier per track (UUID) and on import check if this is already in the database. If there is none, we generate a new one. 
> Just import the track once and export it (manually replacing the file).

_Originally posted by @dennisguse in https://github.com/OpenTracksApp/OpenTracks/issues/90#issuecomment-735354027_

This works, but is a bit cumbersome since the exported track doesn't necessary matches the filename of the imported file.

**Comment by dennisguse** [comment]
I still don't that this one would happen.
The uuid can also be generated outside of OpenTracks or users have to import+export the tracks.

It is just too much effort.
