### ISSUE TITLE
Use ThumbnailUtils for marker's photos

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#545]
**Is your feature request related to a problem? Please describe.**
Marker's list has trouble when there are several large photos (slow loading).

**Describe the solution you'd like**
Use ThumbnailUtils (see https://github.com/OpenTracksApp/OpenTracks/pull/519#issuecomment-729231165)
https://developer.android.com/reference/android/media/ThumbnailUtils

**Comment by rgmf** [comment]
Seem that using ThumbnailUtils.extractThumbnail can be problematic because you are actually loading in memory a copy of the large bitmap, so this is not a good way of managing big images.

In this official doc explain how to do it:
https://developer.android.com/topic/performance/graphics/load-bitmap?hl=es

**Comment by rgmf** [comment]
Seem that the problem comes from the moment where image is loaded (from storage). The size of the image is not the problem (altought it doesn't help).

Cache strategy could be the solution: https://developer.android.com/topic/performance/graphics/cache-bitmap

**Comment by dennisguse** [comment]
We could also create thumbnails and store those beside the actual pictures.

**Comment by rgmf** [comment]
> We could also create thumbnails and store those beside the actual pictures.

Yes, I thought on that possibility but the actual issue is that we have to load photo's file on a separate thread. Doesn't matter if photo is large or small in size: the marker's list is really slow if images are not loaded in a separate thread.

So, I think the best approach if what I've proposed in #546
