### ISSUE TITLE
Elevation Gain is 0?

### ISSUE THREAD

**Issue by pdhixenbaugh** [OpenTracksApp/OpenTracks#555]
**Describe the bug**
Circuit track has elevation graph, but shows zero elevation Gain overall and in intervals

**To Reproduce**
Import GPX

If applicable:
* add screenshots
![Screenshot_20201225-235019](https://user-images.githubusercontent.com/16969821/103145689-42278d00-470c-11eb-9628-3036d09fa668.png)
![Screenshot_20201225-235011](https://user-images.githubusercontent.com/16969821/103145690-42c02380-470c-11eb-8dd9-a62d5af61469.png)
![Screenshot_20201225-235002](https://user-images.githubusercontent.com/16969821/103145691-42c02380-470c-11eb-8454-6c492aa8c2d8.png)

**Technical information**
 - Device: Pixel 3
 - OS: Android 11
 - Version 3761

**Comment by dennisguse** [comment]
Can you export a recorded track (w/ gain) as KML and import it again?
It might be that we did not implement the export of the gain (got via barometric sensor) for GPX.

**Comment by dennisguse** [comment]
Just checked the code and, yes, we do not export/import the gain data with GPX.
https://github.com/OpenTracksApp/OpenTracks/blob/main/src/main/java/de/dennisguse/opentracks/io/file/exporter/GpxTrackWriter.java

**Comment by rgmf** [comment]
> Just checked the code and, yes, we do not export/import the gain data with GPX.
> https://github.com/OpenTracksApp/OpenTracks/blob/main/src/main/java/de/dennisguse/opentracks/io/file/exporter/GpxTrackWriter.java

@dennisguse I noticed that when I was working on "elevation loss" but I thought that there was a reason. I cannot remember why we didn't add this feature for GPX files.

@pdhixenbaugh Was GPX file you are importing exported using OpenTracks?

@dennisguse Could we build "elevation_gain" and "elevation_loss" for "trackpoints" from elevation in GPX/KML files when these files come from another software?

**Comment by dennisguse** [comment]
No real reason (I guess); we always exported less to GPX and that was it.
About importing from another software: I guess not, but I also don't expect KML to work. We are exporting data into a custom extension. I am not really sure if we even could import speed (exported in a similar way). Usually, gain/speed are derived from the GPS data alone (the actual coordinates).
