### ISSUE TITLE
import multiple GPX files via intent at once

### ISSUE THREAD

**Issue by vanous** [OpenTracksApp/OpenTracks#559]
Importing multiple GPX files at once would eventually be a nice addition. So far i have only researched and tested the manifest changes, as per snippet below. `ImportActivity` would need to receive multiple files most probably via `getParcelableArrayListExtra`, but i didn't manage to research this further.

```xml
<intent-filter>
    <action android:name="android.intent.action.SEND_MULTIPLE" />
    <category android:name="android.intent.category.DEFAULT" />
    <data android:mimeType="application/gpx+xml" />
</intent-filter>
<intent-filter>
  <action android:name="android.intent.action.SEND_MULTIPLE" />
  <category android:name="android.intent.category.DEFAULT" />
  <data android:mimeType="application/gpx" />
</intent-filter>
```

**Comment by dennisguse** [comment]
@vanous do you still need this?

**Comment by vanous** [comment]
Hi @dennisguse :)

personally, due to the lockdown and limited allowed movement range (affecting my possible explorations), i had been focusing my activity related development in Gb on a GPS-less activity detection, but once hiking in hills is allowed again, GPS usage will go up for me. From some feedback i see in our chatroom, people do use the GPS, so my request was coming from me as a user but also from the larger vision of allowing more free data flow between apps.

Feel free to close with "looking for help" :)
