### ISSUE TITLE
New screenshots for F-Droid/PlayStore

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#562]
We had quite some UI changes (interval etc), so updating screenshots might be a good idea.

@pstorch I was thinking about including two screenshots with OSMDashboard (one OSMDashboard in fullscreen and one as free floating overlay), so that potential user get aware of it.
And we would need to show it's name somehow.
What do you think?

**Comment by pstorch** [comment]
Good idea

**Comment by rgmf** [comment]
@pstorch @dennisguse What do you think of doing something like this? With this kind of images we can introduce some text explaining the differents parts of the app (a mini how-to) also:

![imagen](https://user-images.githubusercontent.com/4819612/105638856-65fa0200-5e75-11eb-901a-db9fedb8b15b.png)

**Comment by tarah20202** [comment]
Hello sir tank you for the massage sir. I don't know wat is this?? This is
app?? Sir I want clipclaps modded.
