### ISSUE TITLE
Long activity's name and sensor data on StatisticsRecorded

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#566]
**Is your feature request related to a problem? Please describe.**
When user set a long name for his/her activities then s-he cannot read it on any of the views anymore, either ListActivity nor StatisticsRecorded.

Also, OT records sensor data that user cannot see anymore.

**Issue's screenshot**
![imagen](https://user-images.githubusercontent.com/4819612/104807195-4c095100-57dd-11eb-9838-b1169634bbd0.png)

**Describe the solution you'd like**
I think we should redesign, at least, the StatisticsRecorded layout. I've been playing with this layout and I show you one option that I don't like anything, but you could understand more or less what I'd do:

![imagen](https://user-images.githubusercontent.com/4819612/104807242-d487f180-57dd-11eb-94d1-b81224244083.png)

**Describe alternatives you've considered for issue name**
I think after recording, in the recorded statistics, we should show to the user meta-information like the complete name, description (if any), start and end datetime... all this information is useful.

**Describe alternatives you've cosidered for issue sensor**
By the way we should add sensor data on StatisticsRecorded to complete it. At least:
- Heart rate: max and avg (https://github.com/OpenTracksApp/OpenTracks/issues/525).
- Power: avg power (useful regarding some comments in here https://github.com/OpenTracksApp/OpenTracks/issues/502)

All we need to do is query trackpoints database table to get all this information and load them on StatisticsRecorded.

**Comment by dennisguse** [comment]
Sounds good!

PS: Regarding to changes TrackStaticstics; I need to merge #553 first.
Too many changes there... I am hopefully done by tomorrow.

**Comment by rgmf** [comment]
> PS: Regarding to changes TrackStaticstics; I need to merge #553 first.

Yes, yes, I don't want to touch anything before #553... but no hurry :grinning:
