### ISSUE TITLE
Basque translations

### ISSUE THREAD

**Issue by avtkal** [OpenTracksApp/OpenTracks#572]
Someone translated OpenTracks to Basque some time ago, but there still are some strings untranslated. Is the project on any platform? I read it was on Transifex and then on Crowdin. But on the last one just German translations can be made. How can I contribute to the Basque translation?

**Comment by pstorch** [comment]
The translation service is now on https://weblate.bubu1.eu/engage/OpenTracks/

**Comment by avtkal** [comment]
Thank you!
