### ISSUE TITLE
Use opentracks:trackid as export file name 

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#573]
Currently, we use the trackId (in terms of long) + fileSuffix.
However, the trackId is an internal identifier and only valid for the current OpenTracks installation.
Instead, we can use the UUID.

**Comment by dennisguse** [comment]
Quick hack to convert extract KML from KMZ with UUID as filename.
```
#!/bin/bash

DATA=$(unzip -p $1 doc.kml)

TRACKID=$(echo $DATA | xmlstarlet sel -t -m //opentracks:trackid -v .)
ID=$(echo $DATA | xmlstarlet sel -t -m //opentracks:trackid -v .)
echo "$1 > $ID"

echo $DATA > $ID.kml
```

**Comment by pstorch** [comment]
Related to #512

**Comment by dennisguse** [comment]
Valid points; let's move the discussion there!
