### ISSUE TITLE
Increase contrast between buttons and background during tracking 

### ISSUE THREAD

**Issue by dapgo** [OpenTracksApp/OpenTracks#575]
During outdoor sport I've found problems identifying buttons "record, pause, stop" and their current status.

As background color in the buttons area is black, the red color or grey have little contrast and specially if the screen is using tones of grey (used by the "ultra saving mode" of phones as Samsung) but also for sunglasses.  

See below the aspect and colors in ultra saving mode enabled.
![opentrack_ultrasavemode_list](https://user-images.githubusercontent.com/4981669/105641012-0a824100-5e82-11eb-94a3-50f6cbfe5769.jpg)
![opentrack_tracking_ultrasavemode](https://user-images.githubusercontent.com/4981669/105641014-0eae5e80-5e82-11eb-87fa-3b967159da2c.jpg)

**Comment by dennisguse** [comment]
Any suggestions how to adapt for this?
PS: In LineageOS, one can activate monochrome mode in the developer options.

**Comment by rgmf** [comment]
Doing the circle, square and two lines from record, stop and pause buttons a little bit greater the contrast will become greater too. I don't know if it would be enough to distingush between record, stop and pause but I think so.

**Comment by paulle** [comment]
I would supprt this to have the buttons with higher contras (dark theme). Replacing the dark red with brighter one and the grey with green or yellow. As it is it's hard to see when one is outdoor.

**Comment by paulle** [comment]
![opentracks](https://user-images.githubusercontent.com/4852079/110146425-d849f480-7dda-11eb-868a-6bcafa50e8b4.jpg)

**Comment by dennisguse** [comment]
@paulle You can also use the light theme during the day (it is in the settings).
We need something more holistic than just changing the border of the buttons.
