### ISSUE TITLE
Make `app_name` untranslateable 

### ISSUE THREAD

**Issue by fossdd** [OpenTracksApp/OpenTracks#581]
**Is your feature request related to a problem? Please describe.**
On [Weblate](https://weblate.bubu1.eu/translate/OpenTracks/opentracks/de/?offset=1&q=app_name&sort_by=-priority%2Cposition&checksum=) are translations asked for the app's name, but why translate the App name.?

**Describe the solution you'd like**
Make the `app_name` string untranslateable

https://github.com/OpenTracksApp/OpenTracks/blob/63e3c7a4e79821a05e90ac34fa499529f9580312/src/main/res/values/strings.xml#L353

**Comment by dennisguse** [comment]
Good question - never thought about it.
Thanks for bringing it up :+1:
