### ISSUE TITLE
sharing cardio data 

### ISSUE THREAD

**Issue by silvPet** [OpenTracksApp/OpenTracks#585]
It's known that gpx format does not contain cardio data. Too bad I can't convert kml / kmz in garmin_fit format because gpsbabel tell that " format does not support writing". ( Never been able to convert in that proprietary format). How can I do to share my cardio data in Garmin connect? Thank you

**Comment by dennisguse** [comment]
Actually, we support heart rate in GPX (Garmin provided an extension for GPX; i.e., TrackPointExtension) See https://github.com/OpenTracksApp/OpenTracks/issues/181

Dont know if Garmin connect supports this.
