### ISSUE TITLE
Doesn't run in background

### ISSUE THREAD

**Issue by mbnoimi** [OpenTracksApp/OpenTracks#596]
**Describe the bug**
After upgrading my phone to Android 10. OT no longer able to run in background (while other apps work fine ex. OsmAnd)

**My Android Configs**
![_20210210_143939](https://user-images.githubusercontent.com/284547/107506288-ee371180-6bae-11eb-8e12-471b9eb750f5.png)

![_20210210_144155](https://user-images.githubusercontent.com/284547/107506304-f3945c00-6bae-11eb-836e-922a57c7384a.png)

![_20210210_144701](https://user-images.githubusercontent.com/284547/107506328-fe4ef100-6bae-11eb-97df-24e5b804638b.png)
OsmAnd works fine. Both OsmAnd & OT have the same configs while the only difference OsmAnd has **Allow all the time** location permission.

**Technical information**
 - Device: Google Pixel 3
 - OS: Android 10 (Q)
 - Version 3.14.3

**Comment by mbnoimi** [comment]
BTW, I tried to modify **Battery optimization**, but it didn't affect on the result (as soon as I turn off my screen OT no longer run in background)
![_20210210_145529](https://user-images.githubusercontent.com/284547/107507294-69e58e00-6bb0-11eb-91c3-62f07b4a71fc.png)
![_20210210_145550](https://user-images.githubusercontent.com/284547/107507305-6ce07e80-6bb0-11eb-8665-8045ea153fe3.png)

**Comment by dennisguse** [comment]
We had some similar reports, but there is no real fix as there is not too much what we can do.
On my LineageOS phone, the battery saver, for example, prevents usage of GPS.
And there is no error message :shrug: 

I just know that the location permissions should be okay (OSMAnd is not too privacy friendly here).
Some more details can be found here: https://github.com/OpenTracksApp/OpenTracks/issues/282#issuecomment-646692317

**Comment by dennisguse** [comment]
Please reopen, if we can be of more assistance.
