### ISSUE TITLE
track heart rate variability

### ISSUE THREAD

**Issue by khimaros** [OpenTracksApp/OpenTracks#600]
**Is your feature request related to a problem? Please describe.**
heart rate variability (HRV) is a helpful long term indicator of fitness. tracking this over the course of many months can be a very helpful, encouraging signal for people who are training for health purposes.

https://www.health.harvard.edu/heart-health/what-is-heart-rate-variability
https://www.health.harvard.edu/blog/heart-rate-variability-new-way-track-well-2017112212789
https://www.whoop.com/thelocker/heart-rate-variability-hrv/

**Describe the solution you'd like**
add a new menu item to measure HRV. when the user selects this option, provide instructions to the user they they should take this measurement at rest at the same time every day, generally when first waking up. after acknowledgment, measure heart rate for ~1m and then calculate the [RMSSD](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5624990/) from that session and store it. after the measurement is complete, show the user their long term HRV trend.

**Describe alternatives you've considered**
one option would be to build this as a separate app. there's a possibility that this feature doesn't fit well into OpenTracks or for the development team's plans.

a simpler alternative would be to track heart rate variability trends during any workout session (or with a checkbox to toggle). the user would then need to start a workout session in the morning when they are resting and keep track of their HRV from those sessions only in order to have meaningful trends.

**Comment by dennisguse** [comment]
I guess HRV is up to the sensor. The typical sport HR sensors do not provide this. They only offer heart beats per minute. Do you have an example for a sensor that supports this? 

But is is very likely out of scope. It might fit more to Gadgetbridge (i.e., wearables).
