### ISSUE TITLE
Recording stops after one hour of screen off

### ISSUE THREAD

**Issue by ioctl-user** [OpenTracksApp/OpenTracks#623]
Subj.

After device unlock recording starts again.

Disable battery optimization in settings doesn't help.
I have LineageOS 17.1 (Android 10) firmware.

It looks like [this](https://github.com/OpenTracksApp/OpenTracks/issues/430) and [this](https://github.com/OpenTracksApp/OpenTracks/issues/177) problems.

**Comment by dennisguse** [comment]
Which device?

**Comment by ioctl-user** [comment]
Device Oneplus 8.

**Comment by dennisguse** [comment]
Then, I guess, I cannot be very helpful.
We had some trouble with other devices, but not ones running LineageOS.
And there is not too much OpenTracks can do about - we do all the things you can do, to prevent this (basically starting a foreground service).
I would suggest to get in contact with the LineageOS team for this device.

Sorry, for not providing any other suggestions :(

**Comment by ioctl-user** [comment]
Ok. Thank you for the response.

**Comment by dennisguse** [comment]
Actually, there is one workaround (requiring a portable power supply): you could enable the "keep display on while recording"-option.
Not really efficient, but it should "do" the job.

**Comment by ioctl-user** [comment]
It's too hardcore method. The first I will try calendar notifications each 45 minutes to wake up device while recording.
