### ISSUE TITLE
Speed and elevation correctly shown while recording

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#628]
**Describe the bug**
When I start a new track current speed is always 0 and elevation is "-". Anyway, all stats are computed correctly. I've not realized until today so I don't know when this problem begin (usually I start a record and save the smartphone in my pocket).

Is it reproducible for someone? It's an strange error so I don't know if it's an OT issue or a fault of my smartphone.

PS/ I cannot reproduce it in a virtual device :(

Here there is a screenshots:
![imagen](https://user-images.githubusercontent.com/4819612/110009259-0d900d00-7d1d-11eb-96c3-df9229957d52.png)

**More info**
I'm not using any sensor.

**Technical information**
 - Device: Pixel XL 2
 - OS: LineageOS 17.1
 - Version: current F-Droid version (3.15.0)

**Comment by dennisguse** [comment]
Now that you mention it - I have seen this behavior as well.

**Comment by rgmf** [comment]
I get it but I need to check it in real scenarios (only tested on AVD)

**Comment by rgmf** [comment]
`TrackDataHub` send a null TrackPoint every once in a while through `onNewTrackPointsDone`. That's why statistics recording  fragment shows 0 for speed and you sometimes feel a blink on current speed.

**Comment by dennisguse** [comment]
@rgmf then I introduced the issue...
Let me fix it :)
