### ISSUE TITLE
little error in german translation

### ISSUE THREAD

**Issue by paulle** [OpenTracksApp/OpenTracks#631]
It's remaining the english word loss Instead of the german word Abstieg. I looked in the german string file, but couldn't find it there.
It seems to be stored in another place.
![image_2021_03_05_16_04_51](https://user-images.githubusercontent.com/4852079/110136969-9c119680-7dd0-11eb-8c88-20eb6b13d5c4.jpg)

**Comment by dennisguse** [comment]
That's default behavior - if no translation is present in the used language, then the default is used and that is English.

Just check it on Weblate: https://weblate.bubu1.eu/engage/OpenTracks/
We (manually) pull the translation from there before each release (sometimes even more often).

**Comment by paulle** [comment]
done
