### ISSUE TITLE
Speed / distance: rendering

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#648]
We have two different ways to render the speed and the distance.
See `StringUtils.getSpeedParts()` and `StringUtils.formatSpeed()` as well as `StringUtils.getDistanceParts()` and `StringUtils.formatDistance()`

And both format the speed/distance differently, especially regarding the number of decimal digits.

**Comment by rgmf** [comment]
I see that `getDistanceParts` is appropriated for UI where you have two separated fields for the value and the unit, isn't it?

**Comment by dennisguse** [comment]
Exactly, and the fun question is how to unify it.
