### ISSUE TITLE
GPX export TrackStatistics using TrackStatsExtension

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#652]
For GPX, there is an extension to export statistics about a track.
We can include those without a problem:
```
<xsd:element name="Distance" type="Meters_t" minOccurs="0"/>
<xsd:element name="TimerTime" type="Seconds_t" minOccurs="0"/>
<xsd:element name="TotalElapsedTime" type="Seconds_t" minOccurs="0"/>
<xsd:element name="MovingTime" type="Seconds_t" minOccurs="0"/>
<xsd:element name="StoppedTime" type="Seconds_t" minOccurs="0"/>
<xsd:element name="MovingSpeed" type="MetersPerSec_t" minOccurs="0"/>
<xsd:element name="MaxSpeed" type="MetersPerSec_t" minOccurs="0"/>
<xsd:element name="MaxElevation" type="Meters_t" minOccurs="0"/>
<xsd:element name="MinElevation" type="Meters_t" minOccurs="0"/>
<xsd:element name="Ascent" type="Meters_t" minOccurs="0"/>
<xsd:element name="Descent" type="Meters_t" minOccurs="0"/>
```

https://www8.garmin.com/xmlschemas/TrackStatsExtension.xsd

**Comment by dennisguse** [comment]
And we could export the activity/category via TripExtension's `TransportationMode`.
https://github.com/cpesch/RouteConverter/blob/796cbc79b08f2edb1694891a6b61417b9cc104fa/gpx/src/main/doc/TripExtensionsv1.xsd#L19

**Comment by akanakis** [comment]
I would like to try to fix this issue, if no one else hasn't yet.

**Comment by akanakis** [comment]
I'm really sorry, but for some personal reasons I can't get involve with the project right now. So I will unassign myself from this issue and let anyone else to fix it.

**Comment by dennisguse** [comment]
@akanakis Don't worry!

**Comment by rgmf** [comment]
@akanakis if you can get involve in the future it would be great... we'd help you on everything you need ;)

Great to know people interesting on OpenTracks :D

**Comment by akanakis** [comment]
OK thank you very much!
