### ISSUE TITLE
No Up/downslope Data Calc

### ISSUE THREAD

**Issue by mike-wi** [OpenTracksApp/OpenTracks#656]
neither in the Statistic Screen, nor in Interval screen. Graph Shows Elevation Data.

**Technical information**
 - Nokia 2.4
 - Android 10
-  V 3.15.4

**Comment by dennisguse** [comment]
@mike-wi Can you share a screenshot?
Is it while recording or afterwards or is it something imported?

**Comment by mike-wi** [comment]
It's while recording a track. 

thx -mike

![Screenshot_20210316-210343](https://user-images.githubusercontent.com/41682663/111372717-4c1db400-869b-11eb-98cc-ddca54eae4f9.png)

![Screenshot_20210316-210357](https://user-images.githubusercontent.com/41682663/111372811-6b1c4600-869b-11eb-962b-5afa62ff8536.png)

![Screenshot_20210316-210438](https://user-images.githubusercontent.com/41682663/111372871-7ec7ac80-869b-11eb-8184-27d3d30b373e.png)

**Comment by dennisguse** [comment]
Actually, OpenTracks uses the barometric sensor (if present) to gather the gain/loss.
And if no sensor is present, we don't collect it resulting in the "-" for both fields.
And the Nokia 2.4 does not provide this sensor.
The GPS signal is very imprecise and would require some fancy processing.

See #619.

@mike-wi Thanks for the screenshots that was very helpful.

**Comment by mike-wi** [comment]
Thx
-mike
