### ISSUE TITLE
Make shown data configurable

### ISSUE THREAD

**Issue by sebastianha** [OpenTracksApp/OpenTracks#659]
I would really like to see that I can configure the data shown on the screens.

**Example 1 -  Main screen:** Currently time and km is shown. I would be handy to also show average speed or heart rate information here. There should be enough space in the second row.

**Example 2 - Interval screen:** Currently on the right there is elevation. It would be handy to change this to e.g. heart rate information (avg/max) or other data.

**Example 3 - Graph screens:** It could be handy to hide shown graphs, e.g. if you are not interested in elevation.

**Comment by rgmf** [comment]
Interesting idea. I like it.

We could apply something similar than we are doing now for sensor data (dynamically loaded).

I don't like icon on recording either... it's not that important there.
