### ISSUE TITLE
Small screen layout

### ISSUE THREAD

**Issue by sebastianha** [OpenTracksApp/OpenTracks#660]
I sometimes use split screen to show OsmAnd and OpenTracks both on my screen. Unfortunately the layout is not optimal for this, see screenshots

![Screenshot_20210317-073755_OpenTracks](https://user-images.githubusercontent.com/420807/111428320-a0568180-86f7-11eb-81e4-197248a7c0bb.png) ![Screenshot_20210317-073811_OpenTracks](https://user-images.githubusercontent.com/420807/111428370-b106f780-86f7-11eb-86a8-e40fdc83beec.png) ![Screenshot_20210317-073819_OpenTracks](https://user-images.githubusercontent.com/420807/111428372-b2382480-86f7-11eb-9169-96e9626d1405.png)

Perhaps it would be possible to detect the very small app layout and hide some elements of make them smaller. This would be really handy.

**Comment by dennisguse** [comment]
@sebastianha Does the 4.0.0 release (i.e., the UI update) solve this problem for you?

**Comment by sebastianha** [comment]
As soon, as it hits f-droid, I will check.

**Comment by dennisguse** [comment]
In addition, we might be able to hide some UI elements when in multi-window mode.
This method allows to get events: https://developer.android.com/reference/android/app/Activity#onMultiWindowModeChanged(boolean,%20android.content.res.Configuration)

**Comment by sebastianha** [comment]
> @sebastianha Does the 4.0.0 release (i.e., the UI update) solve this problem for you?

Hi,

no, unfortunately not completely. When not running it looks much better now:

![signal-2022-05-30-121952](https://user-images.githubusercontent.com/420807/170972283-36063d06-6187-4566-b40b-aa995244c4ec.png)

But as soon as you are on the recording screen not even one row of data is visible.

![signal-2022-05-30-121949](https://user-images.githubusercontent.com/420807/170972480-1046b044-ed87-431d-b2f8-596a8d8e9fba.png)

It would be nice to have one row visible, this should be do-able with hiding the top bar when the screen is below a certain height.

**Comment by dennisguse** [comment]
Can you check how it looks like in Fullscreen mode? (It is in the Open tracks preferences)

**Comment by sebastianha** [comment]
It looks the same. I think the is no "fullscreen" when in "split screen" mode.

**Comment by rgmf** [comment]
> @rgmf In one of the screenshots, the fabButton overlaps the actual content. Any idea why this is happening?

Yes, FAB button overlap the content. In AntennaPod, for  example, they added a big padding below, so when user scroll down s-he can see the last row completely. Other solution would be to hide FAB button when scroll is on the bottom.

**Comment by dennisguse** [comment]
Actually the Material3 refactoring improved this a lot. Closing for now.
