### ISSUE TITLE
Enhance voice announcement functionality

### ISSUE THREAD

**Issue by sebastianha** [OpenTracksApp/OpenTracks#662]
It would be really nice if the voice announcements could be configured.

a) Make interval of announcements freely configurable, down to seconds / meters. Sometime I want to keep a specific pace or heart rate and it would be nice to hear this every 30 seconds.

b) Add an option to configure what will be announced. Some ideas:
- heart rate
- average speed of current interval
- time since start
-  m or km since start
- ...

**Comment by dennisguse** [comment]
Implemented in #1132.

**Comment by spacecowboy** [comment]
Half of it anyway. I have implemented some of **b** in a different branch.

![Screenshot from 2022-02-20 14-21-25](https://user-images.githubusercontent.com/223655/156381914-5aa6b88d-6dbc-4cb0-8d5c-a5c80878b046.png)
