### ISSUE TITLE
When recording interval list jumps to top too quickly after scrolling down

### ISSUE THREAD

**Issue by sebastianha** [OpenTracksApp/OpenTracks#669]
**Describe the bug**
When recording a track and visiting the interval page it is always at top position showing the latest information which is a good default.

But when scrolling down the list it jumps quickly back up to the top, I assume as soon as there is any new data recorded. This is annoying when I want to take a look at older intervals of the current session.

It would be handy if the list only scrolls up when there is not interaction of the user for e.g. 5 seconds or so. This should not be triggered by new data.

**To Reproduce**
1. Record a track
2. Switch to interval list
3. Run, run, run, so the list is scrollable
4. Try to take a look at old data so you have to scroll down
5. The list will jump to the top very quickly

**Technical information**
- Device: Moto G7 Power
- OS: LineageOS 17.1
- Version: 3.15.4 but also has been before

**Comment by rgmf** [comment]
Yes, you are right @sebastianha 

That should be improved. I'll look into it.
