### ISSUE TITLE
Spoken elapsed time incorrect format

### ISSUE THREAD

**Issue by delboy711** [OpenTracksApp/OpenTracks#674]
Any activity whose duration is more than one hour is spoken incorrectly.
For example "in one hour and one hundred and twenty two minutes and twenty seconds"

I have tried with two different voice engines, e-speak, and Ivona with the same result.

**To Reproduce**
1. Set a voice frequency in settings
2. Engage in any activity for more than one hour.

**Technical information**
 - Device: Xiaomi Mi5
 - OS:  /e/ 0.15
 - Version: 3.15.4

**Comment by dennisguse** [comment]
Yes, that is the case and it shouldn't.
Lack of test coverage before refactoring.
Introduced in e990b413cd7a216554d246663cff439cb6b91ca9
```
        int hours = (int) (duration.getSeconds() / (60 * 60));
        int minutes = (int) (duration.getSeconds() / 60);
        int seconds = (int) (duration.getSeconds() % 60);
```
