### ISSUE TITLE
Export and import GPS accuracy data

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#683]
We store the GPS accuracy data, but we don't export/import it.

**Comment by sebastianha** [comment]
Funny, I yesterday thought the same, that it would be interesting to graph this data. I like the idea!

**Comment by brianjmurrell** [comment]
I do have a patch for this.  I'll push a PR soon.

**Comment by dennisguse** [comment]
@brianjmurrell for testing this, accuracy verification needs to be enabled here: https://github.com/OpenTracksApp/OpenTracks/blob/28944eff07282453fa631a5301fc9246ff33f921/src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java#L210

Technically: `TrackPointAssert.noAccuracy()` can then be deleted.
