### ISSUE TITLE
Typo in xmlns:gpxtpx url in GPXTrackExporter.java

### ISSUE THREAD

**Issue by ChrisD70** [OpenTracksApp/OpenTracks#684]
**Describe the bug**
When exporting a track to gpx there is a typo in the url for xmlns:gpxtpx, instead of

http://www.garmin.com/xmlschemes/TrackPointExtension/v2

it should be

http://www.garmin.com/xmlschemas/TrackPointExtension/v2

**To Reproduce**
1. Export track
2. Open with text editor and check path

**Comment by dennisguse** [comment]
@ChrisD70 Thanks for finding this one!
