### ISSUE TITLE
Unable to uninstall the app

### ISSUE THREAD

**Issue by deepakshilkar** [OpenTracksApp/OpenTracks#685]
**Describe the bug**
I am unable to uninstall the app through both F-Droid as well as the pop-up pill menu. On clicking uninstall, the package installer crashes.

**To Reproduce**
1. Just long press on the app icon and uninstall. 
2. Or go to F-Droid and click uninstall. 

If applicable:

![image](https://user-images.githubusercontent.com/37940886/112947361-512b3a80-9154-11eb-8075-b5b4dbbc3091.png)

**Technical information**
 - Device: Redmi Note 5 Pro whyred
 - OS: LineageOS 17.1
 - Version v3.15.4

**Comment by dennisguse** [comment]
Can you share a logcat? 

We had something very similar: https://github.com/OpenTracksApp/OpenTracks/issues/129
Solution there was to use `adb` to install as the package installer has a bug in some Android versions.

**Comment by dennisguse** [comment]
I guess, we cannot do anything about this.
