### ISSUE TITLE
Introduce quick links between pages

### ISSUE THREAD

**Issue by sebastianha** [OpenTracksApp/OpenTracks#686]
**Is your feature request related to a problem? Please describe.**
There are lists on some screen which represent data. Currently a tap action is recognized (list entry gets darker) but there is no action triggered.

**Describe the solution you'd like**
I have two examples where a tap on a list entry could lead to another page and show data linked to the list entry.

1. Aggregated Stats -> Filtered List
When clicking on an activity on the aggregated stats page this could lead back to the list with the activities but filter by the clicked activity
![link1](https://user-images.githubusercontent.com/420807/112972338-7322be00-9150-11eb-8444-ba2bd4b48dc2.jpg)

2. Interval List -> Chart
When clicking on an entry of the interval list this could open the chart page and change the range of the chart fitting to the selected interval
![link2](https://user-images.githubusercontent.com/420807/112972466-9483aa00-9150-11eb-891e-0d871d18f765.jpg)

**Comment by dennisguse** [comment]
How should the back button behave in this case?

**Comment by sebastianha** [comment]
I would suggest to go back to the screen  on the left.
