### ISSUE TITLE
sort tracks in folders

### ISSUE THREAD

**Issue by qwerty287** [OpenTracksApp/OpenTracks#687]
Hello,
it would be very nice if you could sort your tracks in folders, so you could find tracks easier.

**Comment by dennisguse** [comment]
For what purpose? Do you keep the tracks all on the device?

**Comment by qwerty287** [comment]
Yes, I do (but I would be able to copy them to my computer, maybe I should do this).

**Comment by abthediablo** [comment]
I would like this feature because maybe you want to separate tracks you recorded e.g. during your holiday from other tracks.
