### ISSUE TITLE
Activity icon

### ISSUE THREAD

**Issue by midros** [OpenTracksApp/OpenTracks#698]
Is there any way to add a new icon when you add a new activity?

I have added a new kayaking activity and I would really like a new icon for this type of activity

**Comment by pstorch** [comment]
@midros do you have an icon already or do you know an existing icon which we can use or derive from?

**Comment by midros** [comment]
@pstorch 
I don't have one but I can look for one if you like.
What about the existing icons? Is there a certain icon pack used or somebody created them from scratch?

**Comment by pstorch** [comment]
Some were already there from the previous project Google MyTracks, right @dennisguse?
Some newer ones were derived from them.

@midros if you have a good icon, we can use as a template, it would be nice. I can try to fit it into OpenTracks.
For me it is a bit difficult to distinguish icons for kayaking and similar looking ones like canoeing.

**Comment by midros** [comment]
@pstorch 
Nobody needs different icons for canoeing and kayaking (I hope)

I 'll try to find one similar to the ones already used and keep you informed

thanks a lot

**Comment by midros** [comment]
@pstorch 
maybe [this ](https://thenounproject.com/term/kayak/17483/) or [this ](https://thenounproject.com/term/kayak/552/) will do the trick?
they are public, with several sizes and fit nicely to the rest of the icons

**Comment by pstorch** [comment]
Thanks, I'll have a look

**Comment by pstorch** [comment]
1.)

![Screenshot_20210406-191918_OpenTracks (Debug)](https://user-images.githubusercontent.com/5598124/113752836-b6130180-970d-11eb-9fdc-bf8567f1c02b.jpg)

2.)

![Screenshot_20210406-192156_OpenTracks (Debug)](https://user-images.githubusercontent.com/5598124/113752916-ccb95880-970d-11eb-865b-7967843d3d24.jpg)

Which do you prefer? I think I like the second a little bit more.

**Comment by dennisguse** [comment]
Nr. 2 as it is also "flat" aka 2D aka non-3D :)

**Comment by pstorch** [comment]
Only thing with No2: it has a helmet or a haircut. I can try to make a version with only a circle head, so it looks like the others.

**Comment by dennisguse** [comment]
@pstorch I did not even notice this ;)

**Comment by pstorch** [comment]
> @pstorch I did not even notice this ;)

Yes, on a small screen it's barely visible.

Now without helmet:

![Screenshot_20210406-200247_OpenTracks (Debug)](https://user-images.githubusercontent.com/5598124/113757732-3ee06c00-9713-11eb-9eba-f8afb6d67fad.jpg)

**Comment by midros** [comment]
I am impressed!

great

**Comment by rgmf** [comment]
@pstorch it's great!!!
