### ISSUE TITLE
Intervals distance don't match with stats

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#703]
**Describe the bug**
The addition of all intervals don't match with total distance in stats.

I realized of this while I was testing #701 but it's not related with it. I guess this issue is because intervals are not considering the new types of track points (TrackPoint.Type).

I think the addition of all intervals were nearly the same that total distance in stats, weren't they?

I'm going to check it out.

**To Reproduce**
1. Record a new track.
2. Look at stats distance and intervals distance: they not match.

**Comment by dennisguse** [comment]
Don't know ;)

Why not use the TrackStastistics via TrackStatisticsUpdater (similar to the charts)?
Then all computation/presentation is done this combination and we are consistently correct/wrong :)

**Comment by rgmf** [comment]
> Don't know ;)
> 
> Why not use the TrackStastistics via TrackStatisticsUpdater (similar to the charts)?
> Then all computation/presentation is done this combination and we are consistently correct/wrong :)

Yes, I was thinking on it.

It has should been done like this... I'm going to try to do it like this.

**Comment by dennisguse** [comment]
Is this related with the IntervalStatistics vs TrackStatistics?
If yes, then this "imprecision" also affects the voice announcements, right?

**Comment by rgmf** [comment]
> Is this related with the IntervalStatistics vs TrackStatistics?
> If yes, then this "imprecision" also affects the voice announcements, right?

Yes, I think so. We are using IntervalStatistics for getting the current interval data to announce them.

**Comment by rgmf** [comment]
It's strange because the distance should be exactly the same and I'm fairly sure that one day it was :thinking: 

Anyway, it's a good moment to use TrackStatistics via TrackStatisticsUpdater :smile:

**Comment by rgmf** [comment]
@dennisguse  I've fixed this... but:

I don't understand very well an important detail. I have a very little track:
- 0.95 km
- 46 seconds

![image](https://user-images.githubusercontent.com/4819612/114205416-915f9980-995a-11eb-8c85-01d8cb30c1ba.png)

But those 46 seconds should be 49 seconds:
- First trackPoint (from database) has a time of: 1617571177713
- Last trackPoint (from database) has a time of: 1617571227232

So `1617571227232 - 1617571177713 = 49519 millis`

Is there an explanation on this? Could this be a potencial bug?

PS/ All trackPoints type are 0 (unless the first one, -2, and the last one, 1).

**Comment by dennisguse** [comment]
@rgmf That was fast!

This issue sounds like a bug.
Can you check what happens if you export and re-import the track?
It might be that the duration computation is slightly (still) slightly different while recording.

**Comment by rgmf** [comment]
> @rgmf That was fast!
> 
> This issue sounds like a bug.
> Can you check what happens if you export and re-import the track?
> It might be that the duration computation is slightly (still) slightly different while recording.

After export/import the track has:
- Total moving time: 46 seconds.
- Total time: 49 seconds.

![image](https://user-images.githubusercontent.com/4819612/114213074-d5569c80-9962-11eb-8d0b-1aa86716ca59.png)

So intervals computation through TrackStatisticsUpdater seem okay.

Intervals distance match with track stats imported/exported. There are always slightly differences between time and distance for tracks when they are exported/imported with the original recorded ones.

For example: ("una imagen vale más que mil palabras" :P ):

![image](https://user-images.githubusercontent.com/4819612/114214244-5e220800-9964-11eb-91fd-3e0f48ddd712.png)

**Comment by dennisguse** [comment]
So, we have same trouble in the TrackRecordingService, as there shouldn't be a difference (at least not larger than rounding issues)...

@rgmf Lo mismo motivo funciona en Aleman :)

**Comment by dennisguse** [comment]
@rgmf This is fixed, right?

**Comment by rgmf** [comment]
@dennisguse no, it's not. The potential bug looks like is in TrackRecordingService: https://github.com/OpenTracksApp/OpenTracks/issues/703#issuecomment-816833733
