### ISSUE TITLE
Intervals speed unit wrong

### ISSUE THREAD

**Issue by Crashillo** [OpenTracksApp/OpenTracks#725]
**Describe the bug**
The speed unit displays **kp/h** which is wrong, at least in non english-speakers countries. The common abbreviation is **km/h**. The unit appears to be ok elsewhere in the app, but the interval segments screen.

**To Reproduce**
1. Go to any track
2. Click on _intervals_ tab
3. See error

![photo_2021-04-22 09 29 32](https://user-images.githubusercontent.com/817526/115674013-85f27200-a34d-11eb-91c4-6e75e51f85d0.jpeg)

**Technical information**
 - Device: Honor 9
 - OS: Emui 9 (Android 9)
 - Version: 3.17.1

**Comment by rgmf** [comment]
@Crashillo thank you ;)
