### ISSUE TITLE
Back arrow on about screen is not working

### ISSUE THREAD

**Issue by malteger** [OpenTracksApp/OpenTracks#727]
**Describe the bug**
Back arrow on about screen is not working, but going back via system back button is working fine

**To Reproduce**
1. Go to settings
2. Open 'About OpenTracks'
3. Click on back arrow on top left
4. Nothing happens

**Technical information**
 - Device: Pixel 4a
 - OS: LineageOS18.1
 - Version v3.17.1

**Comment by dennisguse** [comment]
Nice finding!
Thanks :)
