### ISSUE TITLE
Starting gps takes longer in 3.17.1 than 3.16.0

### ISSUE THREAD

**Issue by xxxxme** [OpenTracksApp/OpenTracks#733]
With version 3.17.1 (F-Droid) on LineageOS 16.0 on an LG H932, starting GPS and waiting for a better signal takes a fair bit longer than on 3.16.0. I'm in the same physical location.

**Comment by dennisguse** [comment]
Can you try this again?
Naively, there were no changes that might cause this.

**Comment by dennisguse** [comment]
Please re-open if this is still an issue.
