### ISSUE TITLE
Implement deletion track according to Android lifecycle

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#735]
**Is your feature request related to a problem? Please describe.**
Follow-up #734.

Read comment: https://github.com/OpenTracksApp/OpenTracks/pull/734#issuecomment-826386091

Basically we are using a Thread that will update UI if Activity is started/resumed. We currently have a collateral issue: when user tap back button while track is deleting then the ActivityList show the track already delete in background by the thread. Usually this is difficult because deletion is fast but it can be occur.

Sum up: we need another approach for this.

**Describe the solution you'd like**
Using an approach that match properly with Android Lifecycle.

**Comment by rgmf** [comment]
I think the best solution should be a service so the TrackListActivity can bind to it and receive delete result by the service. But I have some doubts:

TrackListActivity will has to try to bind to the service. Can this be a problem? I mean, every time TrackListActivity is resumed or started it'll has to check if delete service is running to bind to it.

@dennisguse do you think that can be a problem? Am I missing something?

In that case some classes have to be edited:
- TrackListActivity.
- TrackRecordedActivity.
- AbstractListActivity.
- TrackDeleteActivity.

**Comment by dennisguse** [comment]
Don't know - but I guess that won't be a (big) problem.
One data point from TrackDataHub: it was always trying to bind the service until recently.

Can we somehow get rid of TrackDeleteActivity by moving this to a separate service?
And I guess only TrackListActivity would need to check the progress - assuming that TrackRecordedActivity triggers deletion and then finishes. If TrackListActiivty then prevents opening Tracks that are in deletion, we could avoid this.

**Comment by rgmf** [comment]
> Can we somehow get rid of TrackDeleteActivity by moving this to a separate service?

Yes, that's the idea.

**Comment by dennisguse** [comment]
@rgmf Forgot: i am working on #736 (memoryLeak/liveData - hopefully done until the weekend) and this might create some conflicts with this issue.

**Comment by rgmf** [comment]
@dennisguse okay, then I guess it'll be better to wait.
