### ISSUE TITLE
Search is not working from TrackListActivity

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#757]
Since July 2020....

Search from TrackListActivity is not working as the search action is only triggered if the menu item is shown as an action.
However, only two actions can be present and aggregated stats + GPS are more important.
This would fix the issue, but then search is shown instead of GPS status.
```
    <item
        android:id="@+id/track_list_search"
        android:title="@string/menu_search"
        app:actionViewClass="androidx.appcompat.widget.SearchView"
        app:showAsAction="always" />
```

**Comment by dennisguse** [comment]
I am not really sure.
I really like that the aggregated stats are shown directly (by the way nice work!) as well as the GPS status.
It seems as if the search is not used that often or otherwise people would have informed us.

I see two options:
* replace the Toolbar with something that looks similar but allows for more icons
  (probably kind of complicated, but we waste a lot of space there)
* implement a 2nd activity that handles the search and is started in search mode
  (basically TrackRecordingActivity without ControllerFragment + menu)

For now, I was thinking about hiding the search functionality (as a quick fix).

**Comment by sebastianha** [comment]
> I didn't realise search didn't work. Also nobody have opened an issue. Maybe it's not the more used feature. Anyway I wouldn't remove it.
> 
> I think hidding it and think what to do later is a good idea.
> 
> About the solutiona, the second option looks easy and a good solution.

I just stumbled upon this problem so here is a search user!

**Comment by dennisguse** [comment]
@sebastianha Cool!
If you have the time, you may test: https://github.com/OpenTracksApp/OpenTracks/pull/772

**Comment by sebastianha** [comment]
Hi, I have currently no build environment available, sorry. But I will test as soon as the next release is ready. Or is there any auto dev build available?
