### ISSUE TITLE
Disable voice announcement preference on phones without TTS

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#763]
If there is no TTS installed, the voice announcement preference should be disabled.

**Comment by vsevjednom-cz** [comment]
My `Voice frequency` is in gray colour. Tap isn't possible. So is possible to enable some clink announcement in this case?

**Comment by dennisguse** [comment]
@vsevjednom-cz Yes, it will the settings are deactivated, if not TTS is available.
What do you mean by "clink announcement"?

PS: moving this to a new issue might be a good idea.
