### ISSUE TITLE
Allow rounding elevation scale domain

### ISSUE THREAD

**Issue by Crashillo** [OpenTracksApp/OpenTracks#795]
**Is your feature request related to a problem? Please describe.**
In the image below, the elevation chart is barely meaningful, due to the scale begins at 0m, but the elevation mean was 750m-high roughly.
![photo_2021-05-25_21-55-35-2](https://user-images.githubusercontent.com/817526/119560857-c0b05580-bda4-11eb-926b-d394a7644732.jpg)

**Describe the solution you'd like**
Depicts a better range for the scales, based on the data boundaries, i.e. a slightly upper/lower to the maximum/minimum values.
Add a settings option in order to switch the scale behaviour

**Comment by Crashillo** [comment]
Looking at my old tracklogs I noticed this feature was available back in late feb. Was it removed for any reason or just a bug?

**Comment by dennisguse** [comment]
That was not implemented.
It was mentioned in #235, but you description is way nicer.
