### ISSUE TITLE
Intervals doesn't work properly with TrackDataHub

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#808]
I'm improving Intervals using TrackStatisticsUpdater to compute the intervals and I found that Intervals are re-created every time the IntervalsFragment is resumed. It doesn't make sense because we're using ViewModel with LiveData that retain the intervals. That's because TrackDataHub is resumed every time IntervalsFragment is resumed and then TrackDataHub sends all track points again and again.

It's potentially inefficient because if you change ten times from stats tab to intervals tab then intervals are re-computed ten times, for instance.

I'm working on it (https://github.com/OpenTracksApp/OpenTracks/tree/intervalsWithStatsUpdater%23703)

**Comment by dennisguse** [comment]
Sounds good! 
Does this only affect the IntervalFragment?
I am pretty sure that the ChartFragment is doing it something very similar...

**Comment by rgmf** [comment]
> I am pretty sure that the ChartFragment is doing it something very similar...

Yes, I think so too.

I'll check it out too.
