### ISSUE TITLE
The icon of OpenTracks is way too small on my Android 5

### ISSUE THREAD

**Issue by Altonss** [OpenTracksApp/OpenTracks#814]
**Describe the bug**
The icon of OpenTracks is way too small on my Android 5 phone.

**To Reproduce**
1. Probably you first need a similar phone
2. Look an the app icon on the launcher

If applicable:
![image](https://user-images.githubusercontent.com/66519591/121557523-19265a80-ca15-11eb-89aa-592b4f8a0008.png)

**Technical information**
 - Device: [Samsung Galaxy Core Prime]
 - OS: [Android 5.0.2]
 - Version [e.g. v3.18.3 from F-Droid]

**Comment by dennisguse** [comment]
Yes, I removed the downward compatible PNGs and we now use the a vector graphic (hope to avoid problems for reproducible builds). Introduced in v3.18.3.

@Altonss Can you compile to test it on your device?

**Comment by Altonss** [comment]
Thanks for your quick reply!
Ok you mean that there might be an issue with the vector graphic scaling on older devices?
What should I compile? A version with a bugfix? Sorry that I didn't fully understand your answer :)

**Comment by dennisguse** [comment]
:)

Yes, it is a scaling issue that might affect devices pre-Android 8.0; afterwards we have an adaptive icon.
So, far included pre-rendered PNGs and I wanted to get closer to create reproducible builds.
And PNGs might be randomly modified while building the APK: https://f-droid.org/en/docs/Reproducible_Builds/
(and we save some APK size)

Commit: https://github.com/OpenTracksApp/OpenTracks/commit/b0575c0f5b961b3c9f3b2cf4ab1c69938ed53e57

Relevant file: https://github.com/OpenTracksApp/OpenTracks/blob/f5ec91f0eb8bfce892e9e5df93ddaf4842bae91a/src/main/res/drawable/ic_launcher.xml

But I cannot reproduce the issue in the emulator, so you may need to test it yourself.
We had a similar issue ages ago on Xioami, where the icon was too small.

**Comment by dennisguse** [comment]
Link to old issue, but for adaptive icons on Xioami: https://github.com/OpenTracksApp/OpenTracks/issues/121

**Comment by dennisguse** [comment]
I can also reproduce it on a LineageOS 17.1: the icon in the share menu is too small (within a large white circle).

**Comment by dennisguse** [comment]
@Altonss Please re-open, if this does not solve the issue.

**Comment by Altonss** [comment]
Thanks a lot, I will wait for the next release to be available on F-Droid and give you my feedback :)

**Comment by dennisguse** [comment]
@Altonss if you have a sec you can also try it directly ;)

[OpenTracksUpstream-releasePlayStore.zip](https://github.com/OpenTracksApp/OpenTracks/files/6710836/OpenTracksUpstream-releasePlayStore.zip)

**Comment by Altonss** [comment]
On the left the icon before the bugfix and on the right with the bugfix, I think it's better now :)
![image](https://user-images.githubusercontent.com/66519591/123302553-1b141180-d51d-11eb-84ce-7674aabf138f.png)

But I noticed this bug also on both versions, that should be addressed in another issue. Thats the screen when opening the app:
![image](https://user-images.githubusercontent.com/66519591/123302698-43037500-d51d-11eb-8251-a7870c4942ee.png)

**Comment by dennisguse** [comment]
Thanks for testing and great that it works.
Always cool to fix something that one cannot test :)

PS: The splashscreen will stay that way.
Android (<6.0; <API23) renders the image to small and then upscales.
It is not nice, but not that bad.
Adding a version differentiation adds (IMHO) too much complexity.

**Comment by Altonss** [comment]
Thanks for the info ;)
