### ISSUE TITLE
Make F-Droid store listings translatable (via Weblate)

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#816]
aka `fastlane/metadata/android/SOMETHING-SOMETHING/`
* full_description.txt
* title.txt
* short_description.txt

Out of scope: changelogs.

**Comment by dennisguse** [comment]
Done: https://weblate.bubu1.eu/projects/OpenTracks/app-store-metadata-files/

**Comment by dennisguse** [comment]
@mondlicht-und-sterne As head of translations, does this work?

**Comment by pstorch** [comment]
If it works, I want to set it up for the OSMDashboard as well.

**Comment by dennisguse** [comment]
Works like charm.

I just disabled the translations for the changelogs by setting them read-only.
I guess it is not worth the effort to translate those.

And almost not configuration needed: https://docs.weblate.org/_/downloads/en/weblate-3.11/pdf/
![image](https://user-images.githubusercontent.com/2820825/122545047-b264fa80-d02d-11eb-9245-78c75ce25698.png)

**Comment by mondlicht-und-sterne** [comment]
I'll take care of it from 28.6 after my holiday.

**Comment by pstorch** [comment]
> I just disabled the translations for the changelogs by setting them read-only.

@dennisguse how did you do that?

**Comment by dennisguse** [comment]
Like this; but I am not sure if this also applies to new files :man_shrugging: 

https://docs.weblate.org/en/latest/admin/addons.html

![image](https://user-images.githubusercontent.com/2820825/122587739-7dbd6700-d05e-11eb-93ce-2c21c6d40889.png)

**Comment by pstorch** [comment]
@dennisguse thanks. Maybe I'll keep them for now, because I realized I have translated changelogs in the OSMDashboard :laughing:

**Comment by dennisguse** [comment]
I just wanted to avoid that people start translating them as the value is rather limited, but hey if somebody wants to why not ><

**Comment by mondlicht-und-sterne** [comment]
> @mondlicht-und-sterne As head of translations, does this work?

i am on holiday now and i can translate it after 28.6.2021

**Comment by dennisguse** [comment]
@mondlicht-und-sterne enjoy it ;)
