### ISSUE TITLE
Failing test: espressoDeleteTrackTest

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#817]
i get:
```
androidx.test.espresso.IdlingResourceTimeoutException: Wait for [de.dennisguse.opentracks.EspressoDeleteTrackTest$MyIdlingResource] to become idle timed out
```

![image](https://user-images.githubusercontent.com/2820825/122121559-128c4e80-ce2c-11eb-956a-e807dd1a1fbb.png)

PS: Please ignore EspressoCategoryUnitTest as this is a problem with localization setting.

**Comment by rgmf** [comment]
I can reproduce the error in AVD API 22 but not in AVD API 28 and 29 :neutral_face:

In other way, in API 28 and API 29 EspressoDeleteTrackTest doesn't work because when it clicks on record button it doesn't move to TrackRecordingActivity and it continues in TrackListActivity.

**Comment by dennisguse** [comment]
I did not check this yet. I will try to take a look at the weekend ;)
