### ISSUE TITLE
OpenTracks not working

### ISSUE THREAD

**Issue by JahidFariz** [OpenTracksApp/OpenTracks#823]
I'm using Oppo F1 plus. OpenTracks v3.18.3* + was unable to install on Android version 5.1 anymore.

I tried to install the app from the F-Droid app and F-Droid weblink but it won't work.

**Comment by dennisguse** [comment]
I guess, the APK is then not yet uploaded to F-Droid.
That happens every now and then that the catalogue is already uploaded, but the APKs not.
I guess, you just need to wait some hours.
Usually, the F-Droid people resolve this rather quickly.

**Comment by dennisguse** [comment]
Just checked F-Droid and I could download the APK.
@JahidFariz If there is something else broken, please re-open this issue.
