### ISSUE TITLE
Inaccuracy in Czech translation

### ISSUE THREAD

**Issue by vsevjednom-cz** [OpenTracksApp/OpenTracks#841]
**Describe the bug**
`Obnovit skladbu` in czech translation means something like "restore song". The Czech language is one of the most difficult languages in the world 😋.
Look at the Google translator: https://translate.google.cz/?sl=cs&tl=en&text=Obnovit%20skladbu

**To Reproduce**
Tap to menu 📱.

**Technical information**
`<string name="menu_resume_track">Obnovit skladbu</string>` in `cs/strings.xml`

**Comment by rgmf** [comment]
@vsevjednom-cz thank you for open it.

If you want you can fix it and open a PR. Although the best for translations is enter here and write/change the strings: https://weblate.bubu1.eu/engage/OpenTracks/

It would be great ;)

**Comment by vsevjednom-cz** [comment]
I tried to edit translation of `Resume track`. I hope you see it. I'll fix other inaccuracies of translations in future 🙃.

**Comment by dennisguse** [comment]
@vsevjednom-cz I just checked and I saw the translation - not yet in OpenTracks as Weblate has a grace period for translations (to not commit every single change).
Before every release (at least) I pull the localization updates.
