### ISSUE TITLE
Altitude gain and loss not available

### ISSUE THREAD

**Issue by smu55** [OpenTracksApp/OpenTracks#844]
Hi
As you can see in the screenshots the gain and loss of altitude/elevation are not shown, neither live nor in the stats, although the actual altitude is measured. So it must be simply a calculation issue. I use a Samsung Galaxy a51 with German translation.
Thanks for looking into it.

![Screenshot_20210625-124900_OpenTracks](https://user-images.githubusercontent.com/26635954/123414772-996fc280-d5b4-11eb-959c-ecff05fae255.jpg)
![Screenshot_20210625-124838_OpenTracks](https://user-images.githubusercontent.com/26635954/123414852-b0161980-d5b4-11eb-99d1-328057f150ae.jpg)
![Screenshot_20210625-124827_OpenTracks](https://user-images.githubusercontent.com/26635954/123414866-b5736400-d5b4-11eb-9852-9de6c1b9ea47.jpg)

**Comment by rgmf** [comment]
I suppose your smartphone doesn't have barometric sensor, right? Maybe this can help you: https://github.com/OpenTracksApp/OpenTracks/issues/756

**Comment by dennisguse** [comment]
@rgmf I checked: the a50 does not have a barometric sensor and thus no data is shown.
Deriving gain/loss from GPS (kind of noisy elevation data) is not easy as summing a noisy signal is a bad idea.

* Workaround aka hide the missing data: https://github.com/OpenTracksApp/OpenTracks/issues/791
* Actual fix (do some magic math): https://github.com/OpenTracksApp/OpenTracks/issues/619


PS: The German translations are kind of hard on the layout.
I guess, I should use OpenTracks in German for some weeks :|

**Comment by rgmf** [comment]
> @rgmf I checked: the a50 does not have a barometric sensor and thus no data is shown.
> Deriving gain/loss from GPS (kind of noisy elevation data) is not easy as summing a noisy signal is a bad idea.
> 
>     * Workaround aka hide the missing data: [Workaround for #619: no barometric sensor => no gain/loss in IntervalStatistics #791](https://github.com/OpenTracksApp/OpenTracks/issues/791)
> 
>     * Actual fix (do some magic math): [elevation gain/loss without barometer #619](https://github.com/OpenTracksApp/OpenTracks/issues/619)

I opened a PR with the workaround.

> 
> PS: The German translations are kind of hard on the layout.
> I guess, I should use OpenTracks in German for some weeks :|

A word with 17 letters and only 4 vowels!!!! It blows up spanish people mind :rofl: :rofl:
