### ISSUE TITLE
Replace UUID with ULID

### ISSUE THREAD

**Issue by matrixik** [OpenTracksApp/OpenTracks#860]
**Is your feature request related to a problem? Please describe.**
Replace UUID with [ULID](https://github.com/ulid/spec) so exported names can be sorted lexicographically.

**Describe the solution you'd like**
It would fix people complains about wrong order of exported files (like https://github.com/OpenTracksApp/OpenTracks/issues/512#issuecomment-817359415) and still provide unique identifier for tracks.

**Describe alternatives you've considered**
[KSUID](https://github.com/ksuid/ksuid) (more info: https://segment.com/blog/a-brief-history-of-the-uuid/). Differences to ULID: https://github.com/segmentio/ksuid/issues/8.

**Additional context**
More explanation: https://www.honeybadger.io/blog/uuids-and-ulids/

**Comment by dennisguse** [comment]
If those are binary compatible and solve a problem - why not.

Some things to consider:
* Gadgetbridge also needs to be changed as they nowadays generate `opentracks:uuid` as well.
* `opentracks:uuid` in the export/imports is required to be backward compatible

And I am (personally) not a fan of adding external dependencies to OpenTracks as it complicates long-term maintenance.
So, far we managed to just use Androidx.

**Comment by vanous** [comment]
Let us know how you decide to proceed @dennisguse , so we can follow as necessary.

**Comment by dennisguse** [comment]
@vanous Not my problem - if somebody wants it, they have to built it.
Being backward compatible will be kind of painful though.
:man_shrugging: 

@vanous Thanks ;)

**Comment by dennisguse** [comment]
Does not seem that important.
