### ISSUE TITLE
Clink announcement 🔉 for phones without TTS

### ISSUE THREAD

**Issue by vsevjednom-cz** [OpenTracksApp/OpenTracks#862]
**Is your feature request related to a problem? Please describe.**
Phones without TTS can't use voice announcement. #763

**Describe the solution you'd like**
Some sound like sms notification every kilometer for example?

**Additional context**
Something like this: https://www.youtube.com/watch?v=TCMg0J8mfuE

**Comment by vsevjednom-cz** [comment]
I tested it while ride my mountain bike today at `Android 9.1.0`.

Voice announcement plays every 60 seconds when I set 60 minutes.

And what type of sound I must to amplify to hear voice announcement?

**Comment by dennisguse** [comment]
@vsevjednom-cz by time works for me as expected. Tested with 1 and 2min. Regarding channel: the beep is played as MEDIA. Don't know if this is the best choice.

**Comment by rgmf** [comment]
@vsevjednom-cz @dennisguse I think time interval settings are in seconds not in minutes, altough you can see minutes like a unit:

![Screenshot_20210905-181815_OpenTracks_(Debug)](https://user-images.githubusercontent.com/4819612/132134043-4f440cb2-0009-4512-8190-22d0c5a4440a.png)

**Comment by dennisguse** [comment]
That's my fault...

**Comment by rgmf** [comment]
Fixed and push into main. You can see the commit here:

https://github.com/OpenTracksApp/OpenTracks/commit/40aab9444a9410860e3ef647b013bf8b5cf375d4

**Comment by vsevjednom-cz** [comment]
> Regarding channel: the beep is played as MEDIA.

It's too quiet. I have set the maximum volume. I've got my mobile on my back when I ride my bike. Is possible to set more louder announcement? I use it as a check of turned on application.

And another idea: is possible to set announcement of autopause starts and autopause ends? I used this few years ago in Sports Tracker app.

**Comment by dennisguse** [comment]
@vsevjednom-cz No clue. I guess, you need to experiment here yourself. It was literally the first time I used Android's media subsystem. Also the audio file might not be loud enough itself or it might be device dependent...

**Comment by vsevjednom-cz** [comment]
I also think that the low volume of sound is because the media file is not loud. How can I select another sound file?

**Comment by dennisguse** [comment]
> I also think that the low volume of sound is because the media file is not loud. How can I select another media file?

It is the only mp3 that is in OpenTracks.

**Comment by vsevjednom-cz** [comment]
Wow, amazing! I already see the file `tts_fallback.mp3`. It's normalized sound but too quiet. So I "normalized" it with Waves L3 Multimaximizer. I worked in radio as presenter/DJ few years ago - so I still use some plugins for nice normalize.

You can download "normalized" version [here](https://jedu.vsevjednom.cz/tts_fallback_15db.mp3). Try to replace this file.

**Comment by dennisguse** [comment]
@vsevjednom-cz just open a PR 😀 
Have you also tested if it sounds good if you listen to music on the phone using the new announcements?

**Comment by vsevjednom-cz** [comment]
Yes, of course. But better is "normalize" with `Waves L2`, maybe. It's [here](jedu.vsevjednom.cz/tts_fallback_l2.mp3). Don't worry, it normalizes up to 0 db all. Mobile devices plays it without problem.
I can't open PR: `There isn’t anything to compare.`.

**Comment by vsevjednom-cz** [comment]
Yes, of course. But better is "normalize" with `Waves L2`, maybe. It's [here](jedu.vsevjednom.cz/tts_fallback_l2.mp3). Don't worry, it normalizes up to 0 db all. Mobile devices play it without problem.
I can't open PR: `There isn’t anything to compare.`.

**Comment by vsevjednom-cz** [comment]
Yes, of course. But better is "normalize" with `Waves L2`, maybe. It's [here](jedu.vsevjednom.cz/tts_fallback_l2.mp3). Don't worry, it normalizes up to 0 db all. Mobile devices play it without problem.
I can't open PR: `There isn’t anything to compare.`

**Comment by vsevjednom-cz** [comment]
I tried out today at my mountain bike. It's much better but it wants a little bit more volume. [Here is "normalized normalized" sound](https://jedu.vsevjednom.cz/tts_fallback.mp3) 🙃.

**Comment by vsevjednom-cz** [comment]
I tested it out today at my mountain bike. It's much better but it wants a little bit more volume. [Here is "normalized normalized" sound](https://jedu.vsevjednom.cz/tts_fallback.mp3) 🙃.
