### ISSUE TITLE
Statistics: Show pace

### ISSUE THREAD

**Issue by sedrubal** [OpenTracksApp/OpenTracks#87]
**Is your feature request related to a problem? Please describe.**
A common size for runners is the pace (min / km).

**Describe the solution you'd like**
OpenTrack should display it additional to or instead of the speed. You could maybe toggle between speed an pace by tapping on the speed section.

**Comment by dennisguse** [comment]
Would you like to see only the pace or also the avg/min/max?

About toggling: this is usually a functionality that is hard to discover for new users.

**Comment by dennisguse** [comment]
Would you like to see only the pace or also the avg/min/max?

About toggling: this is usually a functionality that is hard to discover for new users.

**Comment by dennisguse** [comment]
And this is blocked by #15.

**Comment by sedrubal** [comment]
I think it would be interesting to see the pace in avg/min/max or even a list of paces for each kilometer?

And you are right that toggling might not be intuitive.

**Comment by dennisguse** [comment]
What do you think about not using either pace or speed but rather pace (yes/no) and speed (yes/no)?

**Comment by dennisguse** [comment]
@rgmf Did we not do something about this?

**Comment by rgmf** [comment]
@dennisguse no, but for runners it's an important feature (I miss it when going out for a run). In TrackRecordedActivity we should add the list of km with its pace. I'm going to look into it...

**Comment by rgmf** [comment]
For run pace is showed several versions ago.

> I think it would be interesting to see the pace in avg/min/max or even a **list of paces for each kilometer**?

I'm going to check it out the possibility of show a list of pace for each km/mi because it's a feature I miss when I'm going out for a run.

**Comment by dennisguse** [comment]
@rgmf I removed this functionality due to technical reasons: statistics were stored as special waypoints. It was quite a while ago (can't search the commit easily on a phone sorry), but the implementation in TrackRecordingService was cool. I just did not like the complexity of storing data. The issue to track this is #134.

**Comment by rgmf** [comment]
@dennisguse my idea is not store anything but show a ListView in TrackRecordedActivity with pace by km, 2km, 3km... or whatever the user select. The pace stats by km can be extracted from TrackPoints.

Anyway I'll read #134 at home.
