### ISSUE TITLE
Make WGS84/EGM2008 configurable by user

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#873]
... just do it.

**Comment by vkbellis** [comment]
Please let us know when testing becomes available.

**Comment by dennisguse** [comment]
@vkbellis Will do; probably next week.
I am just fixing some annoying stuff regarding translations: "copy and paste"-hell :man_shrugging: 



One further question: I would implement this as a setting aka you have to go to the settings page and set it there.
Does this work you?

**Comment by vkbellis** [comment]
Makes sense to me :)
