### ISSUE TITLE
small typo in italian interface

### ISSUE THREAD

**Issue by andrearicci** [OpenTracksApp/OpenTracks#879]
**Describe the bug**
there' a typo in italian translation:
in any track record screen, top-right corner "PEDISTANZA" I guess it should be "PER DISTANZA" (by distance?)
![opentrack-typo](https://user-images.githubusercontent.com/1193266/125187429-e64bce00-e22f-11eb-9a8d-e5f1ac800f27.jpeg)

(I wanted to fix it but I couldn't find the right file)

**Comment by dennisguse** [comment]
Thanks - it was in `src/main/res/values-it/strings.xml`.

You can also use our weblate setup to work translations: https://weblate.bubu1.eu/projects/OpenTracks/
