### ISSUE TITLE
Share pictures from marker

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#89]
**Describe the solution you'd like**
If a picture marker was created, the picture itself cannot be shared alone from the `MarkerDetailFragment`.

**Describe alternatives you've considered**
Add a share-button as for tracks.

**Comment by dennisguse** [comment]
@rgmf If you would have time, this would be a great contribution :)

**Comment by rgmf** [comment]
The markers cannot be share right now, isn't it? Ok, I'll check it out next week ;)
