### ISSUE TITLE
Sensor: support shoe pod sensors  (RSCS) for running (distance/ speed)

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#891]
Time to add another class of sensors :partying_face: 

For testing, I will use a Polar Stride.

* [x] implement data parsing
* [x] implement settings
* [x] implement passing data to UI
* [x] actual testing

**Comment by qntnlq** [comment]
Hello Dennis, 

By any chance, is the Coros Pod supported by the commits related to this issue ? Or at least, is there any reason why pods other than the Polar Strides could not be supported ?

Thanks in advance,

**Comment by dennisguse** [comment]
@qntnlq Other sensors might works as well if they support standard protocols.
For the Coro Pod, this is not documented on there webpage.
So, please check with them beforehand.

Known working sensors and some details can be found here: https://github.com/OpenTracksApp/OpenTracks/blob/main/README_TESTED_SENSORS.md#0x1814-running-cadence-and-speed
