### ISSUE TITLE
Cannot change a type of an activity while pause

### ISSUE THREAD

**Issue by vsevjednom-cz** [OpenTracksApp/OpenTracks#898]
**Describe the bug**
Cannot change a type of an activity while tracking is paused.

**To Reproduce**
1. Start tracking.
2. Tap to the pause.
3. Try to change a type of an activity (from walk to run for example).
4. The icon of activity doesn't change until you tap to the continue.

**Technical information**
 - Device: Honor KSA-LX9
 - OS: Android
 - Version 9.1.0

**Comment by dennisguse** [comment]
This UI is going to be replaced soonish: https://github.com/OpenTracksApp/OpenTracks/pull/842
So, no need to fix this....

PS: Thanks for the report!

PPS: Version is for the OpenTracks version ;)
