### ISSUE TITLE
Bindings in red color in Android Studio

### ISSUE THREAD

**Issue by vsevjednom-cz** [OpenTracksApp/OpenTracks#905]
**Describe the bug**
Android Studio shows `*Binding` in red color. Everything still works without problem 🤪.

**To Reproduce**
1. Get project version: https://github.com/OpenTracksApp/OpenTracks
2. Click to the `AboutActivity` for example.
3. `de.dennisguse.opentracks.databinding` and `AboutBinding` are in red color with  this error: `Package not found: de.dennisguse.opentracks.databinding`
4. But error is gone if you replace `JavaVersion.VERSION_11`  with `JavaVersion.VERSION_1_8` in `build.gradle` - I figured it out after too much testing.

**Technical information**
 - Device: Honor KSA-LX9
 - OS: Android
 - Version: v3.19.0

Or is this some problem on my side?

**Comment by dennisguse** [comment]
I don't know/
Somehow AndroidStudio is not figuring (somtimes) that this code is autogenerated...

You can try to Build -> Rebuild Project.

I also have this sometime :man_shrugging:

**Comment by vsevjednom-cz** [comment]
This is some problem in Android studio with Java 11: https://issuetracker.google.com/issues/180946610 🤪

**Comment by rgmf** [comment]
> This is some problem in Android studio with Java 11: https://issuetracker.google.com/issues/180946610 zany_face

Same issue with Android Studio Arctic Fox 2020.3.1... so waiting for a new Studio release. It's not a problem for developing but an it's a little bit uncomfortable.

**Comment by vsevjednom-cz** [comment]
It's fixed in version 2020.3.1.24~focal+0 in Ubuntu 🥳.
