### ISSUE TITLE
Distance based voice annoucements not being made on v3.19.* 

### ISSUE THREAD

**Issue by slackline** [OpenTracksApp/OpenTracks#925]
**Describe the bug**
Voice announcements do not occur when distance based option of 1km selected.

I noticed this first with v3.19.0 but it persists with v3.19.1.

To investigate I set it to announce every 1 minute and was told statistics for the first two minutes, I then stopped cycling and switched to 1km and didn't hear any announcements after roughly 2km (regular route so I know the distance), I stopped and exported a log, `dmesg`and device info (attached) and then continued with it on 1km but didn't hear voice announcements for the remainder of the 28km cycle. Previously no problems with announcement at all, volume had not been changed

**To Reproduce**
1. Go to Settings
2. Click on Voice Frequency
3. Scroll down to 1km
4. Start recording a track with GPS tracking.

If applicable:

Logcat (filtered for `opentracks`)

[logcat.txt](https://github.com/OpenTracksApp/OpenTracks/files/7048767/logcat.txt)
[device_info.txt](https://github.com/OpenTracksApp/OpenTracks/files/7048770/device_info.txt)
[dmesg.txt](https://github.com/OpenTracksApp/OpenTracks/files/7048772/dmesg.txt)

**Technical information**
 - Device: Motorola G7 Plus
 - OS: LineageOS 16.0
 - Version v3.19.*

**Comment by dennisguse** [comment]
I reworked the whole voice announcements part in #922 (just merged into main).
Happy using it :)

**Comment by slackline** [comment]
Brilliant, thank you, look forward to giving it a whirl :+1:

**Comment by slackline** [comment]
Bit late reporting back but I tried distance based announcements again recently and was pleased to find they are working fine again. Thank you for all the work done on this app its great.

**Comment by dennisguse** [comment]
Great to hear and thanks for the feedback :D
