### ISSUE TITLE
Cadence sensor: 0rpm instead of None

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#931]
**Is your feature request related to a problem? Please describe.**
I'd prefer to see 0rpm instead of None when I stop pedaling my bike.

**Describe the solution you'd like**
When cadence sensor is connected never shows "None" like a value but "0 rpm".

**Comment by dennisguse** [comment]
Should it be value_unknown?

**Comment by rgmf** [comment]
> Should it be value_unknown?

IMHO I should be value_unknown when cadence sensor is not connected and 0rpm if it's connected.

But I don't know very well how sensors work. Does cadence sensor send 0 when cyclist is not pedaling? If so, I don't understand where None value comes from.

**Comment by dennisguse** [comment]
You are right that are two cases.

Regarding the data: those sensors only send data when they measured something (like the wheel rotated).
If nothing is happening, then they don't send data.
So, the timeout occurs OpenTrack invalidates the data (5s timeout) and then the data is null resulting and `StringUtils.formatCadence()` returns None.

So, the invalidation should actually set them 0 and on disconnect to null.
