### ISSUE TITLE
Feature Request: manually enter total distance

### ISSUE THREAD

**Issue by convolutionbbs** [OpenTracksApp/OpenTracks#937]
I was wondering if anybody else would be interested in using opentracks to log treadmill runs.  I would like to use it to log my HR via BT and have the ability to edit the distance after the recording.  This would allow the stats to be included in total metrics.

**Comment by dennisguse** [comment]
To log sensor data without GPS is handled by #500. Should be ready in October. 
Adding data by hand is not yet on the roadmap.

Does the treadmill provide data via Bluetooth?

**Comment by convolutionbbs** [comment]
Thanks for the reply.  No, my treadmill doesn't have bluetooth.  I have a HR monitor that is bluetooth and it works really well with OpenTracks.  I was thinking that the user would connect the HR monitor and begin and log a workout just like if I ran outside.  After I was done, I could hit the edit button and manually type in how long the treadmill thought I ran.  That way I could see the HR data and the long term stats would capture the distance.

**Comment by dennisguse** [comment]
That's doable. 
What must be done is to set the total distance as the distance of the final TrackPoint and then re-create the TrackStatistics. 

And it could be done for recordings for which 0 distance was recorded.

Intermediate solution: use of a shoe-based running sensor.
Then the overall distance will taken from that there.
Until #500 is resolved only the one TrackPoint is stored (ie. no intermediate values from HR/ shoe sensor).

**Comment by brianjmurrell** [comment]
This would be really cool.  A lot of my workouts are on the treadmill.

**Comment by MrS1R1US** [comment]
> What must be done is to set the total distance as the distance of the final TrackPoint and then re-create the TrackStatistics.

I don't understand how to do it. Where to click? Tell me please

**Comment by dennisguse** [comment]
@MrS1R1US this functionality is not implemented.
It is just the description how it could be done.
