### ISSUE TITLE
Include option for changing workout that is being recorded.

### ISSUE THREAD

**Issue by slackline** [OpenTracksApp/OpenTracks#938]
**Is your feature request related to a problem? Please describe.**

I like the new customisable layout when recording tracks, however I could not see the ability to add a button/cell that allows you to choose what activity you are recording. That is now only accessible via the menus.

**Describe the solution you'd like**

Restore the button that allows the user to choose what activity they are recording, but as a configurable option in-keeping with the new layout.

**Comment by dennisguse** [comment]
@rgmf :partying_face:
