### ISSUE TITLE
Nightly improvements

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#952]
* [ ] install git
* [x] use black icon background
* [ ] (also for debug) change background Color of splash screen
* [x] append nightly to app name

**Comment by pstorch** [comment]
I've got the build to run on my little vserver and setup a cronjob for 1 a.m. to check for new commits and build a new nightly apk.
Let's see if it is working.
In case someone has already installed the first test nightly from my repo, you need to uninstall it first. I had to change the signing key.

Repo (still beta): https://fdroid.storchp.de/fdroid/repo/

**Comment by dennisguse** [comment]
@pstorch :heart_eyes: 
Just installed the nightly on my phone (in parallel the other two installations ><).
Now I am curiously waiting for the next just released version...

**Comment by pstorch** [comment]
First successful build via cronjob last night 🎉

**Comment by dennisguse** [comment]
@pstorch Got the update in the morning!
Nice work;

**Comment by dennisguse** [comment]
Now we have a black background for the launcher icon, so I distinguish all three variants :D
Staying tuned for the new nightly build :partying_face:

**Comment by pstorch** [comment]
I got a black icon 🎉

**Comment by dennisguse** [comment]
@pstorch PR for the webpage welcome :D
