### ISSUE TITLE
Promo codes for Google Play Store (until 2021-03-31)

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#97]
Promo codes to install OpenTracks from the [Google Play store](https://play.google.com/store/apps/details?id=de.dennisguse.opentracks.playstore) for free.

Either use the links to Play Store (works also in the browser as well as on Android phones) or redeem the code manually on an Android phone (instructions can be found [here](https://support.google.com/googleplay/answer/3422659)).

All gone for now.

**Comment by pes4murai** [comment]
Dear Dennis,
thank you for the Promo Code.
I've used 4PB65AKX36DJCQRQEGJR0HQ but I can't mark it in your list.
Thank you so much!

**Comment by noodle-** [comment]
I used this one: WNGQC4B682DLNN1CZYAUTUD
Thank you!

**Comment by audunmg** [comment]
Thank you! I used this one: 13PSK97EJY3UN9U1CR7ES2D

**Comment by Dabombber** [comment]
Used 209GRG9RA6R7M7TCKG2CCA5, thanks.

**Comment by GajenderY** [comment]
Thank you, I used HQ9GY71FD14MUJXCYT0XC4P but wasn't able to mark it.

**Comment by blackris-github** [comment]
Thanks, tried the f-droid version but it couldn't get a GPS signal. I will play around with the settings a bit and try out the Play Store version. Used the code:

WVWTVLQGAW2A7QDRSS9RAUF

**Comment by dennisguse** [comment]
@blackris-github The PlayStore release is identical to the F-Droid release.
If you have any problems just open a new issue - and we can try some troubleshooting.

**Comment by xax** [comment]
Used `HZUPAZLKGGFH32TQSQBTQER`; found `66WLM97429YYT1P8UHVVNH4`
 having been used previously.

Thanks a lot.

**Comment by SHMAUS-Carter** [comment]
Used 4GPSDEYNZGW67LMDHYB318M

**Comment by lannetscan** [comment]
Used MQB58N3UBY6TW68UEK2TC2K
I really enjoy your app, but the fdroid package could not be parsed (android 11)

**Comment by sttoma** [comment]
Thank you, I used 
2Q1E6CDJGVGRWFP2NUZ6EEJ
but I can't mark it in your list.

**Comment by MarcoDjallo** [comment]
4ELML5L5NRHE9XP0APK325L used! Thank you

**Comment by nemeises** [comment]
hello dear dennis please give me gift card google play i very very need to this
please 🙏
tank you

**Comment by nemeises** [comment]
nemesises94@gmail.com

**Comment by frqusg** [comment]
please give me gift card google play i very very need to this
please 🙏💔

**Comment by bedri87** [comment]
please give me gift card google play

**Comment by Ra242** [comment]
Hey bro please give me unused promo code

**Comment by kiraci03** [comment]
Can you give me one that work of them please? I went through a lot and all (or nearly i guess) are used

**Comment by jackprink** [comment]
I have list of code that work and real. but you need to spend your time and complete some basic task so you earn points and get your google play gift card reward.
follow below link to get it now -[https://www.freereward.net/google-play/](https://www.freereward.net/google-play/)
