### ISSUE TITLE
"Bad characters" in file name

### ISSUE THREAD

**Issue by mega-stoffel** [OpenTracksApp/OpenTracks#975]
Hej there!
Just today I tried to sync all my tracks to my Windows laptop.
But Windows can't work with colons (:) in the file name, which is used to divide hours:minutes.

Would it be possible to avoid such "bad" characters in file names?

Thanks. :-)

**Comment by dennisguse** [comment]
Duplicate of #254.

**Comment by dennisguse** [comment]
@mega-stoffel PS/ would you would have some time to look into this that would be awesome!
