### ISSUE TITLE
Allow track creation without starting recording

### ISSUE THREAD

**Issue by vlmendz** [OpenTracksApp/OpenTracks#983]
**Is your feature request related to a problem? Please describe.**
I use the automatic track export feature at the end of the recording. If I forget to edit the track during the recording (put the name, type of activity, etc.) it is exported without this data.

**Describe the solution you'd like**
Add in the menu an alternative option to the current one to create a track (it could be called "New Track"). So being still at home you could create and edit the track more easily, and already outdoors, with better GPS positioning just start the recording.

**Describe alternatives you've considered**
Keep it as is

**Comment by dennisguse** [comment]
#824 describes a different solution for the same problem.

**Comment by dennisguse** [comment]
Does #1094 solve this issue for you?
Now you get prompted before finishing  a track to set the name / description.
The new UI is not yet release (i.e., only in the nightly).

**Comment by vlmendz** [comment]
Yes, it works for me (however, I would like to be able to edit the metadata of a track before starting recording).

**Comment by dennisguse** [comment]
Rather unlikely to get implemented.
