### ISSUE TITLE
Error in pace shown while running

### ISSUE THREAD

**Issue by kurihoro** [OpenTracksApp/OpenTracks#990]
While running, the actual pace shown in the statistics is always wrong. It jumps to any value between 4:00 and 8:00 min/Km while I know I'm running at 4:30 - 4:50 min/Km all the time. The value shown is usually higher than my real pace. After the run, the values shown in the intervals tab are right.
I've been using OpenTracks since its beginning (more or less) and this didn't use to happen. I noticed this error many months ago; I don't know exactly when.

Sorry for my bad English and thanks for your great job.

**To Reproduce**
1. Record a run, try to keep a constant pace and compare the values for the actual pace with the average pace.

**Technical information**
 - Devices: Samsung Galaxy A50 and Xiaomi Redmi Note 7.
 - SO: Android and LineageOS respectively.
 - Version: v3.20.2

**Comment by dennisguse** [comment]
That is kind of expected (on how we compute the pace currently).
While recording, we use the speed from reported by the GPS to compute the pace.
The GPS reported speed is very noise and we apply some filtering, but that only helps so much.

Later in the intervals tab, we use the actual distance vs time to compute the speed.
And here the noise is already canceled out as the minimal interval is 1km.

__Potential solution:__ do not use the filtered GPS speed to compute pace, but rather the actual distance vs. time.
This has the drawback that rapid changes in speed/pace, would not be immediately reported. 

PS/ thanks :D
