### ISSUE TITLE
Export track to CSV

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#999]
Mainly for analytics purpose and debugging: it would be great to export the trackpoints into a really simple CSV format.

Import is optional.

**Comment by pstorch** [comment]
Just curios: is it for your own development purposes? You know you can directly access the database via the AppInspector from AndroidStudio, while you debug the app, query the trackpoints table of with a trackid and export as CSV.

**Comment by dennisguse** [comment]
Yes it is - sometimes AppInspector is just not enough:
* I have some devices with development mode disabled (for reasons)
* I don't always carry my development machine with me

For weird cases, I often use a spreadsheet program and then CSV is choice to go.
That would even work on the phone itself :sunglasses:

**Comment by pstorch** [comment]
Ah yes, I already guessed that you have a special usecase for this. Just wanted to make sure you know that AppInspector DB access. Because I found out rather late 😉

**Comment by dennisguse** [comment]
@pstorch +1
actually, I did not use the AppInspector that often so far :)

**Comment by MrS1R1US** [comment]
It's very good idea!! It would be nice to choose the export method to csv, broken down by activity and time week / month / year

**Comment by dennisguse** [comment]
@MrS1R1US That was not the intention, but we could also include something like this.

**Comment by brianjmurrell** [comment]
How do you include all of the various extension items that may or may not exist from one track to another?

**Comment by dennisguse** [comment]
@brianjmurrell Give me 5min and then you will see :)
